#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process');
const ROOT=process.cwd();
function read(name,f=null){try{return JSON.parse(fs.readFileSync(path.join(ROOT,name),'utf8'))}catch(_){return f}}
function git(args){const r=cp.spawnSync('git',args,{cwd:ROOT,encoding:'utf8'});return String(r.stdout||'').trim()}
const cfg=read('data/quiet-quality-autopilot.json',{});
const record={recordedAt:new Date().toISOString(),runId:process.env.GITHUB_RUN_ID||null,sha:process.env.GITHUB_SHA||git(['rev-parse','HEAD'])||null,ref:process.env.GITHUB_REF||null,autopilot:read('QUIET_AUTOPILOT_REPORT.json'),canary:read('QUALITY_AB_CANARY_REPORT.json'),multiRegion:read('QUALITY_MULTI_REGION_REPORT.json'),realDeviceRum:read('QUALITY_REAL_DEVICE_RUM_REPORT.json'),geographicDevice:read('QUALITY_GEOGRAPHIC_DEVICE_REPORT.json'),mobileGpu:read('QUALITY_MOBILE_GPU_REPORT.json'),otel:read('QUALITY_OTEL_BRIDGE_REPORT.json'),rollout:read('QUALITY_PROGRESSIVE_ROLLOUT_REPORT.json'),proof:read('QUALITY_PROOF_GATE.json'),production:read('PRODUCTION_QUALITY_REPORT.json'),master:read('QUALITY_MASTER_REPORT.json'),cost:read('QUALITY_COST_DECISION.json'),learning:read('QUALITY_LEARNING_REPORT.json'),distributed:read('QUALITY_DISTRIBUTED_COORDINATOR.json'),patchOutcome:read('QUALITY_PATCH_OUTCOME.json'),state:read('.quality-autopilot-state/state.json')};
fs.writeFileSync(path.join(ROOT,'QUALITY_TELEMETRY_RECORD.json'),JSON.stringify(record,null,2)+'\n');
(async()=>{const url=(process.env.SUPABASE_URL||'').replace(/\/$/,''),key=process.env.SUPABASE_SERVICE_ROLE_KEY||'',table=cfg.telemetry?.supabase?.table||'world_server_quality_telemetry';if(!url||!key||cfg.telemetry?.supabase?.enabledWhenSecretsPresent===false){console.log('[QUALITY_TELEMETRY] local record written; Git telemetry branch fallback active');return}try{const r=await fetch(`${url}/rest/v1/${encodeURIComponent(table)}`,{method:'POST',headers:{'content-type':'application/json',apikey:key,authorization:`Bearer ${key}`,prefer:'return=minimal'},body:JSON.stringify({recorded_at:record.recordedAt,run_id:record.runId,git_sha:record.sha,payload:record}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`Supabase ${r.status}: ${await r.text()}`);console.log('[QUALITY_TELEMETRY] Supabase durable append OK')}catch(e){record.supabaseError=String(e.message||e);fs.writeFileSync(path.join(ROOT,'QUALITY_TELEMETRY_RECORD.json'),JSON.stringify(record,null,2)+'\n');console.warn('[QUALITY_TELEMETRY] Supabase append failed; Git branch fallback remains active')}})().catch(e=>{console.error(e);process.exit(51)});
