#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const {ROOT,STATE_DIR,readJSON,writeJSON,ensureDir,nowIso}=require('./integration-utils.cjs');
const lifecycle=require('./orchestrator-monitor-lifecycle.cjs');
const repro=require('./orchestrator-minimal-repro.cjs');
const basePolicy=readJSON(path.join(ROOT,'data/orchestrator-supervisor-policy.json'),{});
const stateDir=path.join(STATE_DIR,'supervisor');ensureDir(stateDir);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function mergePolicy(o={}){return{...basePolicy,...o}}
function jitter(ms,pct=20,r=Math.random){const d=ms*(Number(pct)||0)/100;return Math.max(0,Math.round(ms-d+r()*2*d))}
function nextBackoff(attempt,p=basePolicy){return Math.min(Number(p.maxBackoffMs||60000),Number(p.initialBackoffMs||1000)*Math.pow(Number(p.backoffMultiplier||2),Math.max(0,attempt-1)))}
function crashLoop(restarts,now=Date.now(),p=basePolicy){const w=Number(p.restartWindowMs||300000),max=Number(p.maxRestartsPerWindow||5);return restarts.filter(t=>now-t<=w).length>=max}
function normalizeError(s){return String(s||'').toLowerCase().replace(/0x[0-9a-f]+/g,'0x*').replace(/\b\d{4,}\b/g,'#').replace(/[a-f0-9]{32,64}/g,'<hash>').replace(/\\/g,'/').replace(/\s+/g,' ').trim().slice(-4000)}
function fingerprint(exitCode,signal,stderr){return crypto.createHash('sha256').update(`${exitCode??'null'}|${signal||''}|${normalizeError(stderr)}`).digest('hex').slice(0,24)}
function statePath(id){return path.join(stateDir,`${String(id).replace(/[^a-z0-9._-]+/gi,'-')}.json`)}
function loadState(id){return readJSON(statePath(id),{schemaVersion:'7.2.0',id,restarts:[],incidents:[],circuit:'CLOSED',generation:0})}
function saveState(id,s,p=basePolicy){s.schemaVersion='7.2.0';s.id=id;s.updatedAt=nowIso();const cap=Math.max(10,Number(p.incidentRingSize||50));s.incidents=(s.incidents||[]).slice(-cap);s.restarts=(s.restarts||[]).slice(-Math.max(cap,Number(p.maxRestartsPerWindow||5)*3));writeJSON(statePath(id),s);return s}
function identityAllowed(id,command,args,p=basePolicy){const svc=(Array.isArray(p.managedServices)?p.managedServices:[]).find(x=>x.id===id);if(!svc)return p.requireManagedServiceIdentity!==true;const expected=String(svc.command||'').toLowerCase();return !expected||String(command||'').toLowerCase().endsWith(expected.toLowerCase())}
function boundedAppend(s,chunk,max=65536){s+=String(chunk||'');return s.length>max?s.slice(-max):s}
async function runChildOnce(id,command,args,p,generation){return new Promise((resolve,reject)=>{let stdout='',stderr='',settled=false,heartbeatTimer=null;const started=Date.now();let child;try{child=cp.spawn(command,args,{cwd:ROOT,env:{...process.env,WORLD_SERVER_SUPERVISOR_ID:id,WORLD_SERVER_SUPERVISOR_GENERATION:String(generation)},stdio:['ignore','pipe','pipe'],windowsHide:true})}catch(e){return reject(e)}
 child.stdout?.on('data',d=>stdout=boundedAppend(stdout,d,p.maxCapturedLogBytes||65536));child.stderr?.on('data',d=>stderr=boundedAppend(stderr,d,p.maxCapturedLogBytes||65536));
 const heartbeatFile=process.env.WORLD_SERVER_HEARTBEAT_FILE||'';const timeout=Number(p.heartbeatTimeoutMs||0),checkEvery=Math.max(250,Number(p.heartbeatCheckMs||5000));if(timeout>0&&heartbeatFile){heartbeatTimer=setInterval(()=>{try{const age=Date.now()-fs.statSync(heartbeatFile).mtimeMs;if(age>timeout){stderr=boundedAppend(stderr,`\n[SUPERVISOR] heartbeat stale age=${age}`);child.kill('SIGTERM');setTimeout(()=>{try{if(!settled)child.kill('SIGKILL')}catch{}},Math.min(5000,Number(p.gracefulShutdownMs||15000))).unref?.()}}catch{}},checkEvery);heartbeatTimer.unref?.()}
 const done=(exitCode,signal)=>{if(settled)return;settled=true;if(heartbeatTimer)clearInterval(heartbeatTimer);resolve({exitCode,signal,stdout,stderr,durationMs:Date.now()-started})};child.once('error',e=>{stderr=boundedAppend(stderr,e.stack||e.message);done(null,'SPAWN_ERROR')});child.once('exit',done);
 const shutdown=()=>{try{child.kill('SIGTERM')}catch{}};process.once('SIGTERM',shutdown);process.once('SIGINT',shutdown);child.once('exit',()=>{process.removeListener('SIGTERM',shutdown);process.removeListener('SIGINT',shutdown)})})}
function circuitReport(id,state,p,reason,last={}){state.circuit='OPEN';state.openedAt=nowIso();state.reason=reason;const rr=p.minimalReproOnCircuitOpen===false?null:repro.create({reason,serviceId:id,generation:state.generation,exitCode:last.exitCode,signal:last.signal,fingerprint:last.fingerprint,command:last.command,stderr:last.stderr,stdout:last.stdout});const report={schemaVersion:'7.2.0',generatedAt:nowIso(),pass:false,id,status:'CRASH_LOOP_CIRCUIT_OPEN',circuitBreaker:true,restartBudgetExhausted:true,stablePreserved:true,lastKnownGoodProtected:true,generationLease:true,minimalRepro:rr?.file||null,attempts:state.restarts.length,incidents:state.incidents};writeJSON(path.join(ROOT,'ORCHESTRATOR_SUPERVISOR_STATUS.json'),report);saveState(id,state,p);return report}
async function supervise(id,command,args=[],override={}){const p=mergePolicy(override);if(!identityAllowed(id,command,args,p))throw new Error(`service-identity-mismatch:${id}`);let state=loadState(id);if(state.circuit==='OPEN'&&p.allowAutomaticCircuitReset!==true)throw new Error(`circuit-open:${id}`);let attempt=0;for(;;){const now=Date.now();state.restarts=(state.restarts||[]).filter(t=>now-t<=Number(p.restartWindowMs||300000));if(crashLoop(state.restarts,now,p)){const r=circuitReport(id,state,p,'restart-budget-exhausted');const e=new Error(`crash-loop:${id}`);e.report=r;throw e}attempt++;const token=lifecycle.begin(`service:${id}`,id,{settleMs:Number(p.startupSettleMs||0)});state.generation=token.generation;saveState(id,state,p);const r=await runChildOnce(id,command,args,p,token.generation);if(r.exitCode===0){lifecycle.cancel(`service:${id}`,'clean-exit');state.circuit='CLOSED';state.lastCleanExitAt=nowIso();state.lastHealthyDurationMs=r.durationMs;if(r.durationMs>=Number(p.minHealthyMs||0))state.restarts=[];saveState(id,state,p);const report={schemaVersion:'7.2.0',generatedAt:nowIso(),pass:true,id,status:'EXITED_CLEAN',attempts:attempt,durationMs:r.durationMs,stablePreserved:true,generation:token.generation,incidents:state.incidents};writeJSON(path.join(ROOT,'ORCHESTRATOR_SUPERVISOR_STATUS.json'),report);return report}
 lifecycle.cancel(`service:${id}`,'child-exit');const fp=fingerprint(r.exitCode,r.signal,r.stderr);const incident={at:nowIso(),attempt,generation:token.generation,exitCode:r.exitCode,signal:r.signal,fingerprint:fp,durationMs:r.durationMs,stderr:String(r.stderr||'').slice(-2000)};state.restarts.push(Date.now());state.incidents.push(incident);state.lastFingerprint=fp;const same=(state.incidents||[]).filter(x=>x.fingerprint===fp).length;if(same>=Number(p.sameFingerprintQuarantineThreshold||3)){const rr=circuitReport(id,state,p,'repeated-crash-fingerprint',{...r,fingerprint:fp,command:[command,...args]});const e=new Error(`quarantined-crash-fingerprint:${id}:${fp}`);e.report=rr;throw e}saveState(id,state,p);if(crashLoop(state.restarts,Date.now(),p)){const rr=circuitReport(id,state,p,'restart-budget-exhausted',{...r,fingerprint:fp,command:[command,...args]});const e=new Error(`crash-loop:${id}`);e.report=rr;throw e}const backoff=jitter(nextBackoff(attempt,p),p.jitterPercent||20);await sleep(backoff)}}
function reset(id){const s=loadState(id);s.circuit='CLOSED';s.restarts=[];s.resetAt=nowIso();saveState(id,s);lifecycle.cancel(`service:${id}`,'manual-reset');return{pass:true,id,circuit:'CLOSED'}}
function health(){const services=Array.isArray(basePolicy.managedServices)?basePolicy.managedServices:[];const report={schemaVersion:'7.2.0',generatedAt:nowIso(),pass:true,watchdog:true,crashLoopProtection:true,restartBudget:true,circuitBreaker:true,exponentialBackoff:true,jitter:true,persistentIncidents:true,crashFingerprinting:true,generationLease:true,staleMonitorCancellation:true,startupStabilization:true,heartbeatTimeoutSupport:Number(basePolicy.heartbeatTimeoutMs||0)>0,minimalReproOnCircuitOpen:basePolicy.minimalReproOnCircuitOpen!==false,stablePreserved:true,managedServiceCount:services.length};writeJSON(path.join(ROOT,'ORCHESTRATOR_SUPERVISOR_STATUS.json'),report);return report}
async function selftest(){const p={...basePolicy,maxRestartsPerWindow:2,restartWindowMs:60000,initialBackoffMs:1,maxBackoffMs:2,jitterPercent:0,sameFingerprintQuarantineThreshold:99,minimalReproOnCircuitOpen:true,startupSettleMs:0,minHealthyMs:0,requireManagedServiceIdentity:false};let blocked=false,reproFile=null;try{await supervise(`selftest-${process.pid}`,process.execPath,['-e','process.stderr.write("boom 12345\\n");process.exit(7)'],p)}catch(e){blocked=/crash-loop/.test(e.message);reproFile=e.report?.minimalRepro||null}const fp1=fingerprint(7,null,'Error at 12345'),fp2=fingerprint(7,null,'Error at 99999');const ok=blocked&&fp1===fp2&&Boolean(reproFile);return{pass:ok,crashLoopBlocked:blocked,normalizedFingerprintStable:fp1===fp2,minimalReproCreated:Boolean(reproFile)}}
if(require.main===module){const [cmd='health',id,bin,...args]=process.argv.slice(2);(async()=>{let r;if(cmd==='health')r=health();else if(cmd==='selftest')r=await selftest();else if(cmd==='run'){if(!id||!bin)throw new Error('usage run <id> <command> [args...]');r=await supervise(id,bin,args)}else if(cmd==='reset'){if(!id)throw new Error('usage reset <id>');r=reset(id)}else throw new Error('health | selftest | run <id> <command> [args...] | reset <id>');console.log(JSON.stringify(r,null,2));if(r.pass===false)process.exitCode=2})().catch(e=>{console.error('[SUPERVISOR] FAIL',e.stack||e.message);process.exit(2)})}
module.exports={jitter,nextBackoff,crashLoop,normalizeError,fingerprint,identityAllowed,supervise,reset,health,selftest};
