#!/usr/bin/env node
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('@playwright/test');
function arg(n, f=null){ const i=process.argv.indexOf(n); return i>=0 && process.argv[i+1] && !process.argv[i+1].startsWith('--') ? process.argv[i+1] : f; }
function writeJson(f,v){ fs.mkdirSync(path.dirname(f),{recursive:true}); fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n'); }
async function shot(page,url,viewport){ await page.setViewportSize(viewport); await page.goto(url,{waitUntil:'networkidle',timeout:30000}); await page.waitForTimeout(800); return page.screenshot({fullPage:false}); }
async function compare(page,a,b){ return page.evaluate(async ({a,b})=>{ const load=s=>new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src='data:image/png;base64,'+s;}); const [ia,ib]=await Promise.all([load(a),load(b)]); const w=Math.min(ia.width,ib.width),h=Math.min(ia.height,ib.height); const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true}); x.drawImage(ia,0,0,w,h);const A=x.getImageData(0,0,w,h).data;x.clearRect(0,0,w,h);x.drawImage(ib,0,0,w,h);const B=x.getImageData(0,0,w,h).data;let sum=0,bad=0,n=0;const step=Math.max(1,Math.floor((w*h)/250000));for(let p=0;p<w*h;p+=step){const i=p*4;const d=(Math.abs(A[i]-B[i])+Math.abs(A[i+1]-B[i+1])+Math.abs(A[i+2]-B[i+2]))/(255*3);sum+=d;if(d>0.35)bad++;n++;}return {width:w,height:h,meanDifference:sum/n,badPixelRatio:bad/n}; },{a:a.toString('base64'),b:b.toString('base64')}); }
(async()=>{ const baseline=arg('--baseline',process.env.QUALITY_BASELINE_URL); const candidate=arg('--candidate',process.env.QUALITY_CANDIDATE_URL||'http://localhost:3000'); const route=arg('--route',process.env.QUALITY_VISUAL_ROUTE||'/apps/ai3d-voxel-city/'); const out=arg('--out','data/quality-autopilot/visual-regression.json'); if(!baseline){const r={status:'skipped',ok:false,reason:'QUALITY_BASELINE_URL missing'};writeJson(out,r);console.log('[QUALITY_VISUAL] skipped: baseline URL missing');return;} const browser=await chromium.launch({headless:true}); const page=await browser.newPage(); const results=[]; try{for(const viewport of [{name:'desktop',width:1440,height:900},{name:'mobile',width:390,height:844}]){const a=await shot(page,new URL(route,baseline).toString(),viewport);const b=await shot(page,new URL(route,candidate).toString(),viewport);const diff=await compare(page,a,b);results.push({...viewport,...diff});}}finally{await browser.close();} const maxMean=Number(process.env.QUALITY_VISUAL_MAX_MEAN||0.12),maxBad=Number(process.env.QUALITY_VISUAL_MAX_BAD||0.20);const ok=results.every(r=>r.meanDifference<=maxMean&&r.badPixelRatio<=maxBad);const report={status:ok?'pass':'regressed',ok,baseline,candidate,route,maxMean,maxBad,results};writeJson(out,report);console.log(`[QUALITY_VISUAL] ok=${ok}`);if(!ok)process.exitCode=2;})().catch(e=>{console.error(e);process.exitCode=2;});
