'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const path=require('path');const cf=require('../lib/creature-factory');
const POLICY=path.join(__dirname,'..','data','creature-lod-policy.json');
function asset(seed='alpha',extra={}){return{format:'zero-signal-procedural-asset-v1',category:'creature',params:{seed,detail:1.2},materialSettings:{shaderPreset:1},object:{geometries:[{uuid:'g1'}]},...extra};}
test('both procedural editor formats accepted',()=>{assert.equal(cf.validateFormat(asset()).ok,true);assert.equal(cf.validateFormat({...asset(),format:'zero-signal-godot-procedural-asset-v1'}).ok,true);});
test('exact 13 categories accepted',()=>{assert.equal(cf.CATEGORIES.length,13);for(const category of cf.CATEGORIES)assert.equal(cf.validateFormat({...asset(),category}).ok,true);});
test('recipe is deterministic and seed-aware',()=>{const a=cf.buildRecipe(asset()),b=cf.buildRecipe(asset()),c=cf.buildRecipe(asset('beta'));assert.equal(a.hash,b.hash);assert.equal(cf.recipeHash(a),a.hash);assert.notEqual(a.hash,c.hash);});
test('heavy source is stripped but bounded metadata remains',()=>{const r=cf.buildRecipe(asset());const s=JSON.stringify(r);assert.equal(s.includes('geometries'),false);assert.equal(typeof r.metadata.sourceHash,'string');assert.ok(r.metadata.sourceBytes>0);});
test('oversize source fails closed',()=>{assert.throws(()=>cf.buildRecipe(asset('x',{object:{blob:'x'.repeat(cf.MAX_SOURCE_BYTES+1)}})),/exceeds/);});
test('instancing key stable per recipe+lod',()=>{const r=cf.buildRecipe(asset());assert.equal(cf.instancingKey(r,'full'),cf.instancingKey(r,'full'));assert.notEqual(cf.instancingKey(r,'full'),cf.instancingKey(r,'medium'));});
test('LOD monotonic and low tier never ticks',()=>{const p=cf.loadPolicy(POLICY),order=p.tierOrder;let prev=-1;for(const d of [0,30,31,60,61,100,101,160,300]){const rank=order.indexOf(cf.getLodTier(d,p));assert.ok(rank>=prev);prev=rank;}assert.equal(cf.shouldTick(999,'low',p),false);});
test('offscreen sleeps and uses impostor',()=>{const q=cf.planCreatureQuality({visible:false,distance:1},POLICY);assert.equal(q.tier,'low');assert.equal(q.sleep,true);assert.equal(q.useImpostor,true);assert.equal(q.animationHz,0);});
test('mobile/cpu/frame pressure cannot improve quality',()=>{const p=cf.loadPolicy(POLICY),order=p.tierOrder;const a=cf.planCreatureQuality({distance:20,targetFps:60},POLICY),b=cf.planCreatureQuality({distance:20,targetFps:60,mobile:true,cpuPressure:.9,frameTimeMs:30},POLICY);assert.ok(order.indexOf(b.tier)>=order.indexOf(a.tier));assert.ok(b.animationHz<=a.animationHz);});
test('animation scheduler caps frame work and remains fair',()=>{const s=new cf.AnimationScheduler({maxPerFrame:32}),ids=Array.from({length:100},(_,i)=>`c${i}`),seen=new Set();for(let i=0;i<4;i++)for(const id of s.schedule(ids))seen.add(id);assert.equal(seen.size,100);});
test('LOD hysteresis blocks one-frame flapping',()=>{const h=new cf.LodHysteresis({hysteresisFrames:3});assert.equal(h.record('x','full'),'full');assert.equal(h.record('x','high'),'full');assert.equal(h.record('x','full'),'full');assert.equal(h.record('x','high'),'full');assert.equal(h.record('x','high'),'full');assert.equal(h.record('x','high'),'high');});
