'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),cf=require('../lib/creature-factory');
function asset(seed='a',withObject=false){return{format:'zero-signal-procedural-asset-v1',category:'creature',params:{seed,detail:1.2},materialSettings:{shaderPreset:1},...(withObject?{object:{geometry:[1,2,3]}}:{})};}
test('runtime identity cache reuses heavy editor object safely',()=>{const rt=cf.createCreatureRuntime(),a=asset('x',true);const r1=rt.recipe(a),r2=rt.recipe(a);assert.strictEqual(r1,r2);assert.equal(rt.snapshot().telemetry.counters.recipeBuilds,1);assert.equal(rt.snapshot().telemetry.counters.recipeIdentityHits,1);});
test('runtime LRU reuses structurally identical source-less recipes',()=>{const rt=cf.createCreatureRuntime();const r1=rt.recipe(asset('x')),r2=rt.recipe(asset('x'));assert.equal(r1.hash,r2.hash);assert.ok(rt.optimizer.recipeCache.stats().hits>=1);});
test('different heavy editor objects never alias by structural cache',()=>{const rt=cf.createCreatureRuntime(),a=asset('x',true),b=asset('x',true);b.object.geometry=[9];assert.notEqual(rt.recipe(a).metadata.sourceHash,rt.recipe(b).metadata.sourceHash);});
test('frame pressure lowers animation budget and feeds quality pressure',()=>{const rt=cf.createCreatureRuntime({frameBudget:{smoothing:1,maxAnimationBudget:32,minAnimationBudget:8}});rt.observeFrame(40);assert.ok(rt.optimizer.controller.snapshot().animationBudget<32);const p=rt.plan(asset('p'),{distance:5,targetFps:60});assert.ok(['high','medium','low'].includes(p.quality.tier));});
test('scheduler follows adaptive budget',()=>{const rt=cf.createCreatureRuntime({frameBudget:{smoothing:1,maxAnimationBudget:32,minAnimationBudget:8}});rt.observeFrame(50);const budget=rt.optimizer.controller.snapshot().animationBudget;assert.ok(rt.scheduleAnimations(Array.from({length:100},(_,i)=>String(i))).length<=budget);});
test('parity signature remains deterministic',()=>{const rt=cf.createCreatureRuntime(),a=asset('p');const ctx={distance:30,targetFps:60},tr={x:1,y:2,z:3,ry:.5};assert.equal(rt.parity(a,ctx,tr,'idle'),rt.parity(a,ctx,tr,'idle'));});
