import test from'node:test';import assert from'node:assert/strict';
import{principleForStep,tierForStep,planMetrics,childExplain,PUBLIC_PRINCIPLES,H3_CAUSAL_FAMILIES,selectH3CausalFamily}from'../shared/dark-void-science-journey.mjs';
import{hash32,SurpriseEngine,AdaptiveTeacher}from'../shared/dark-void-infinite-runtime.mjs';
import{ScienceEvidenceRecorder}from'../shared/dark-void-science-evidence.mjs';
test('public journey exposes only H1-H3 for 10k steps',()=>{assert.deepEqual(PUBLIC_PRINCIPLES.map(x=>x.id),['H1','H2','H3']);for(let i=0;i<10000;i++)assert.ok(['H1','H2','H3'].includes(principleForStep(i).id))});
test('unbounded tier growth remains finite and slow',()=>{assert.ok(tierForStep(1e6)>tierForStep(100));assert.ok(tierForStep(1e6)<30);assert.ok(Number.isFinite(tierForStep(Number.MAX_SAFE_INTEGER)))});
test('H1 compactness metric beats recipe bytes',()=>{const blocks=Array.from({length:500},(_,i)=>({x:i%10,y:i%5,z:i%17,blockType:3})),m=planMetrics({intent:{type:'tower',seed:7},origin:{x:0,y:0,z:0},blocks});assert.ok(m.compactness>10);assert.ok(m.recipeBytes<m.explicitBytes)});
test('child-facing science is English and excludes H4',()=>{for(const id of['H1','H2','H3']){const s=childExplain({id},{blocks:20,compactness:5,types:3,density:.2},{predictedBlocks:20});assert.equal(/[А-Яа-яЁё]/.test(s),false);assert.equal(/multi.?ai|specialized ai|H4/i.test(s),false)}});
test('hash stable and sensitive',()=>{assert.equal(hash32('abc'),hash32('abc'));assert.notEqual(hash32('abc'),hash32('abd'))});
test('SurpriseEngine avoids immediate repeats',()=>{const e=new SurpriseEngine(),seen=new Set();for(let i=0;i<6;i++){const x=e.choose(i,0),k=x.principle+'|'+x.prompt;assert.equal(seen.has(k),false);seen.add(k)}});
test('AdaptiveTeacher changes depth',()=>{const t=new AdaptiveTeacher();for(let i=0;i<6;i++)t.observe('why confused what does this mean?');assert.equal(t.style(),'very-simple')});
test('science evidence summary aggregates H1-H3',()=>{const r=new ScienceEvidenceRecorder();r.rows=[];r.add({h:'H1',compactness:10});r.add({h:'H2',blocks:30,types:3});r.add({h:'H3',match:true,delta:0});const s=r.summary();assert.equal(s.H1.n,1);assert.equal(s.H2.n,1);assert.equal(s.H3.matchRate,1)});

test('H2 production metrics preserve organized-vs-shuffled negative/positive evidence',()=>{const blocks=Array.from({length:120},(_,i)=>({x:i,y:0,z:0,blockType:i<60?1:2})),m=planMetrics({intent:{type:'wall',seed:77},origin:{x:0,y:0,z:0},blocks});assert.equal(m.topologyComponents,1);assert.ok(m.meanDegree>1.9);assert.ok(m.runCompressibility>=60);assert.ok(m.mutualInformation>m.shuffledMutualInformation);assert.ok(m.organizedLift>0);assert.ok(Number.isFinite(m.entropyRate));const r=new ScienceEvidenceRecorder();r.rows=[];r.recordH2(1,m);const s=r.summary().H2;assert.equal(s.n,1);assert.equal(s.meanTopologyComponents,1);assert.ok(s.meanOrganizedLift>0)});

test('H3 causal-family selection is blind, deterministic, and bounded',()=>{assert.deepEqual(H3_CAUSAL_FAMILIES.map(x=>x.id),['scale-up','scale-down','seed-shift']);const intent={type:'tower',seed:7,scale:1},a=selectH3CausalFamily(5,intent),b=selectH3CausalFamily(5,{...intent,actual:999,matchRate:0,blocks:[1,2,3]});assert.equal(a.id,b.id);assert.equal(a.selectionHash,b.selectionHash);assert.equal(a.selectionBlind,true);assert.ok(Number.isInteger(a.selectionHash));const out=a.apply(intent);assert.notDeepEqual(out,intent);assert.ok(out.scale!==1||out.seed!==7)});
test('H3 evidence records blind family selection before outcome',()=>{const r=new ScienceEvidenceRecorder();r.rows=[];r.recordH3Prediction(8,{beforeManifestation:true,expected:12,predictionHash:55,modelFamily:'seed-shift',selectionBlind:true,selectionHash:77});const row=r.rows[0];assert.equal(row.phase,'prediction');assert.equal(row.selectionBlind,true);assert.equal(row.selectionHash,77);assert.equal(row.actual,undefined)});
