'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..'),txt=p=>fs.readFileSync(path.join(root,p),'utf8');
test('V10 temporal artifact detector scores ghosting flicker shimmer',()=>{const s=txt('shared/procedural-quality-temporal-artifacts.js');for(const x of ['ghosting','flicker','shimmer','meanDiff'])assert.ok(s.includes(x),x)});
test('V10 frame pacing tracks p95 p99 jank stutter',()=>{const s=txt('shared/procedural-quality-frame-pacing.js');for(const x of ['p95','p99','jankRate','stutterRate'])assert.ok(s.includes(x),x)});
test('V10 resource watchdog detects heap/canvas growth',()=>{const s=txt('shared/procedural-quality-resource-watchdog.js');for(const x of ['heapGrowth','canvasGrowth','possibleLeak'])assert.ok(s.includes(x),x)});
test('V10 thermal governor has hidden save-data low-battery pressure policies',()=>{const s=txt('shared/procedural-quality-thermal-governor.js');for(const x of ['hidden','save-data','low-battery','thermal-or-main-thread-pressure'])assert.ok(s.includes(x),x)});
test('V10 shader prewarm supports Three compileAsync and budget',()=>{const s=txt('shared/procedural-quality-shader-prewarm.js');assert.ok(s.includes('compileAsync'));assert.ok(s.includes('budgetMs'))});
test('V10 replay benchmark is seeded and deterministic interface exists',()=>{const s=txt('shared/procedural-quality-replay-benchmark.js');for(const x of ['1664525','seed','record','play'])assert.ok(s.includes(x),x)});
test('V10 canary requires runtime health and production evidence',()=>{const s=txt('shared/procedural-quality-canary.js');for(const x of ['temporal-artifacts','frame-pacing','resource-leak','physical-device-certification','golden-baseline'])assert.ok(s.includes(x),x)});
test('V10 profile exposes all new policies',()=>{const p=require('../lib/api-handlers/procedural-quality-profile.js').buildProfile({webgpu:'1',webgl2:'1',memory:16,cores:16,dpr:1});assert.equal(p.version,10);for(const k of ['temporalArtifactDetector','framePacingGovernor','resourceLeakWatchdog','thermalMobileGovernor','shaderPrewarm','deterministicReplay','canaryPromotion'])assert.equal(p.policy[k],true,k)});
test('V10 migration has canary and runtime health tables',()=>{const s=txt('supabase/procedural_quality_v10.sql');assert.ok(s.includes('procedural_quality_canary_runs'));assert.ok(s.includes('procedural_quality_runtime_health'))});
test('V10 doctor has 12-round non-stop repair policy',()=>{const s=txt('scripts/procedural-quality-doctor.js');assert.ok(s.includes('maxRounds=12'));assert.ok(s.includes('fix every reproducible unresolved error manually'))});
test('V10 evidence graph includes temporal pacing leak thermal shader replay canary',()=>{const s=txt('scripts/procedural-quality-evidence-orchestrator.js');for(const x of ['runtimeToTemporalQA','runtimeToFramePacing','runtimeToLeakWatchdog','runtimeToThermal','runtimeToShaderPrewarm','replayToRegression','promotionToCanary'])assert.ok(s.includes(x),x)});

