'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');const root=path.resolve(__dirname,'..');
function load(rel,extra={}){const code=fs.readFileSync(path.join(root,rel),'utf8');const ctx={globalThis:{},console,Math,performance:{now:()=>0},Uint8Array,Float32Array,...extra};ctx.globalThis.globalThis=ctx.globalThis;vm.createContext(ctx);vm.runInContext(code,ctx);return ctx.globalThis}
test('V6 renderer contract validates native frame and jitter',async()=>{const g=load('shared/procedural-quality-renderer-contract.js'),c={width:100,height:50};g.WorldProceduralRendererContract.register(c,{backend:'test',captureFrame:()=>({width:100,height:50,depth:{width:100,height:50},normal:{width:100,height:50},motion:{width:100,height:50},semantic:{width:100,height:50}})});const f=await g.WorldProceduralRendererContract.capture(c);assert.equal(f.native,true);assert.equal(g.WorldProceduralRendererContract.validateFrame(f).ok,true);assert.notEqual(f.jitter.x,0)});
test('V6 TSR source detects reactive and disocclusion pixels',()=>{const g=load('shared/procedural-quality-tsr-source.js').WorldProceduralTSRSource,a=new Uint8Array([0,0,0,255,255,255,255,255]),b=new Uint8Array([0,0,0,255,0,0,0,255]);assert.ok(g.reactiveMask(a,b)[1]>0);const d=g.disocclusionMask(new Float32Array([.1,.8]),new Float32Array([.1,.2]));assert.equal(d[1],255)});
test('V6 DDGI propagates and samples radiance',()=>{const D=load('shared/procedural-quality-ddgi.js').WorldProceduralDDGI,v=D.create({resolution:[2,2,2]});for(let i=0;i<v.probes.length;i++)v.updateProbe(i,{rgb:[i===0?1:0,0,0],visibility:1},{history:0});v.bounce(2);const s=v.sample([-1,-1,-1]);assert.ok(s[0]>.5)});
test('V6 framegraph honors budget and deps',async()=>{const F=load('shared/procedural-quality-framegraph.js').WorldProceduralFrameGraph,g=F.create({budgetMs:5});g.add('base',{critical:true,costMs:2});g.add('gi',{deps:['base'],costMs:10,quality:2});const p=g.plan();assert.ok(p.passes.includes('base'));assert.ok(!p.passes.includes('gi'))});
test('V6 budget controller responds to p95 pressure',()=>{const B=load('shared/procedural-quality-budget-controller.js').WorldProceduralBudgetController,b=B.create({targetFps:60});for(let i=0;i<60;i++)b.frame(25);assert.equal(b.decide(5000).change,-1)});
test('V6 style calibration preserves low-key mood',()=>{const S=load('shared/procedural-quality-style-calibration.js').WorldProceduralStyleCalibration,d=new Uint8Array(400);for(let i=0;i<400;i+=4){d[i]=20;d[i+1]=20;d[i+2]=20;d[i+3]=255}const s=S.analyzeRGBA(d),t=S.target(s);assert.equal(t.lowKey,true);assert.ok(t.exposure<=1.08)});
test('V6 API/profile and migration artifacts exist',()=>{for(const f of ['shared/procedural-quality-native-bridge.js','shared/procedural-quality-perceptual.js','scripts/procedural-quality-production-verify.js','scripts/procedural-quality-native-audit.js','supabase/procedural_quality_v6.sql','PROCEDURAL_MODEL_MANIFEST.json'])assert.ok(fs.existsSync(path.join(root,f)),f);const p=require('../lib/api-handlers/procedural-quality-profile.js').buildProfile({webgpu:'1',memory:8,cores:8,dpr:2});assert.ok(p.version>=6);assert.equal(p.policy.rendererContract,true)});

