const test=require('node:test'),assert=require('node:assert/strict');
const {errorsForEvidence}=require('../lib/user-link-delivery-policy');
const now=Date.parse('2026-09-09T04:30:00Z');
const good={verifiedAt:'2026-09-09T04:29:30Z',httpStatus:200,bodySample:'<canvas id="game"></canvas>',appReady:true,browserVerified:true,playableWorld:true,deliveryRole:'final',ephemeralPreview:false};
test('fresh stable playable link passes',()=>assert.deepEqual(errorsForEvidence(good,now),[]));
test('HTTP 404 is hard-blocked',()=>assert.ok(errorsForEvidence({...good,httpStatus:404},now).some(x=>x.includes('2xx'))));
test('Netlify Site not found is hard-blocked even with HTTP 200',()=>assert.ok(errorsForEvidence({...good,bodySample:'Site not found'},now).some(x=>x.includes('Site not found'))));
test('stale evidence is hard-blocked',()=>assert.ok(errorsForEvidence({...good,verifiedAt:'2026-09-09T04:20:00Z'},now).some(x=>x.includes('stale'))));
test('browser-ready evidence is mandatory for playable links',()=>assert.ok(errorsForEvidence({...good,browserVerified:false},now).some(x=>x.includes('browser'))));
test('ephemeral preview cannot be final user link',()=>assert.ok(errorsForEvidence({...good,ephemeralPreview:true},now).some(x=>x.includes('preview'))));
