'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');const ROOT=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');const learning=require('../lib/world-google-learning'),registry=require('../lib/world-function-registry'),gdd=require('../lib/world-game-design-spec');

test('Google runtime signal normalization strips identifiers from route and bounds telemetry',()=>{const s=learning.normalizeRuntimeSignal({slot:'navigator',route:'/world/1234567890/item/abcdef123456?token=secret',status:700,latencyMs:-1,traceparent:'bad'});assert.equal(s.route,'/world/:id/item/:id');assert.equal(s.status,599);assert.equal(s.latencyMs,0);assert.equal(s.traceparent,'')});
test('Google learning aggregates by route/revision and creates guarded candidates',()=>{const a=learning.aggregateRuntimeSignals([{route:'/api/a',revision:'r1',status:500,latencyMs:2000},{route:'/api/a',revision:'r1',status:200,latencyMs:2200}]);assert.equal(a.samples,2);assert.equal(a.routes[0].key,'/api/a');const c=learning.developmentCandidates(a,{errorRate:.1,slowMs:1500});assert.ok(c.length);assert.ok(c.every(x=>x.automaticMutation===false))});
test('Cloud Run wrapper emits structured privacy-minimized learning logs with immutable revision identity',()=>{const s=read('google-ai-studio/cloudrun-entry.cjs');for(const x of ['world_runtime_signal','K_REVISION','K_SERVICE','K_CONFIGURATION','x-world-revision','coldStart','/api/google-learning-meta'])assert.match(s,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(s,/requestBody|chatText|feedbackText/)});
test('Google learning reuses root cause, regression, replay, feedback and release systems',()=>{const s=read('scripts/world-google-deployment-learning-loop.cjs');for(const x of ['quality:root-cause','quality:generate-tests','quality:tournament','integration:record-replay','world:feedback:full','release:gate'])assert.match(s,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(s,/automaticMutation:false/)});
test('Canary plan keeps exactly existing slots and uses gradual immutable revision rollout',()=>{const s=read('scripts/world-google-canary-plan.cjs');assert.match(s,/Never create a third AI Studio app/);for(const p of [1,5,25,50,100])assert.match(s,new RegExp(`trafficPercent:${p}`));assert.match(s,/last-green/);assert.match(s,/rollback/)});

test('Function manifest requires GDD linkage, semver, immutable revision install and allowlisted capabilities',()=>{const manifest={id:'hello-world',name:'Hello',version:'1.2.3',runtime:'server',entry:'handler.js',installMode:'revision',hotCode:false,rollbackSafe:true,gameDesignSections:['coreLoop'],acceptance:['works'],capabilities:['world.read']};assert.equal(registry.validateManifest(manifest).ok,true);assert.equal(registry.validateManifest({...manifest,gameDesignSections:[]}).ok,false);assert.equal(registry.validateManifest({...manifest,capabilities:['secrets.read']}).ok,false);assert.equal(registry.validateManifest({...manifest,installMode:'hot'}).ok,false)});
test('Function source audit rejects eval, process env, child process and arbitrary network URLs',()=>{for(const src of ['eval("x")','process.env.SECRET','require("child_process")','fetch("https://evil.example")'])assert.equal(registry.auditSource(src).ok,false,src);assert.equal(registry.auditSource("exports.run=async(ctx,input)=>({ok:true})").ok,true)});
test('Bundled world-spec-summary package passes registry audit',()=>{const p=registry.inspectPackage(path.join(ROOT,'world-functions/world-spec-summary'));assert.equal(p.ok,true);assert.equal(p.manifest.installMode,'revision');assert.deepEqual(p.manifest.capabilities,['world.spec.read'])});
test('Function APIs never implement runtime code download or eval',()=>{for(const f of ['api/function-catalog.js','api/function-invoke.js','api/function-install-request.js','api/function-admin.js']){const s=read(f);assert.doesNotMatch(s,/eval\s*\(|new Function|download.*code|https?:\/\/[^'\"]+/i)}assert.match(read('api/function-invoke.js'),/world_function_installations/);assert.match(read('api/function-install-request.js'),/automaticInstall:false/)});
test('Function database schema separates requests from installations and gives clients no installation write policy',()=>{const s=read('supabase/migration_templates/world_functions_v5.sql');for(const t of ['world_function_catalog','world_function_installations','world_function_requests','world_function_events'])assert.match(s,new RegExp(t));assert.match(s,/users create own function requests/);assert.doesNotMatch(s,/policy[^\n]*installations[^\n]*for\s+(insert|update|delete)/i)});

test('Game Design baseline preserves Create/Join, Eye controls, Navigator, shared world and outcome',()=>{const s=gdd.loadBaseline(ROOT),raw=JSON.stringify(s);for(const x of ['Create','Join','Eye','Navigator','shared','left joystick','right joystick'])assert.match(raw,new RegExp(x,'i'));assert.ok(s.outcome.length>=4);assert.ok(s.multiplayer.interactions.length>=8)});
test('Game Design baseline contains all six creative layers from the prior design method',()=>{const ids=new Set(gdd.loadBaseline(ROOT).creativeEventLayers.map(x=>x.id));for(const x of ['mechanic','visual','audio','riskReward','progression','story'])assert.ok(ids.has(x))});
test('Game Design validator and acceptance derivation are deterministic enough for gates',()=>{const s=gdd.loadBaseline(ROOT),v=gdd.validateSpec(s),a=gdd.deriveAcceptanceTests({...s,specHash:gdd.hashSpec(s)});assert.equal(v.ok,true);assert.ok(a.tests.length>=8);assert.ok(a.tests.some(x=>x.type==='multiplayer'));assert.ok(a.tests.some(x=>x.type==='deployment'))});
test('Navigator dialogue creates only draft Game Design specs, never stable directly',()=>{const s=read('api/game-design-spec.js');assert.match(s,/status:'draft'/);assert.match(s,/navigator-dialogue/);assert.match(s,/automaticPromotion:false/);assert.doesNotMatch(s,/status:'stable'/)});
test('Game Design Supabase policy allows draft creation but no client stable promotion',()=>{const s=read('supabase/migration_templates/world_game_design_v5.sql');assert.match(s,/status='draft'/);assert.match(s,/No client policy promotes candidate\/stable/);assert.doesNotMatch(s,/for update to authenticated/i)});
test('Feedback and Google evidence become Game Design change candidates without automatic mutation',()=>{const s=read('scripts/world-game-design-feedback-bridge.cjs');assert.match(s,/feedback-semantic-clusters/);assert.match(s,/google-development-candidates/);assert.match(s,/automaticSpecMutation:false/);for(const x of ['sandbox','canary','release gate'])assert.match(s,new RegExp(x,'i'))});
test('Game Design feedback mapper routes controls, multiplayer, performance and story to different sections',()=>{assert.equal(gdd.feedbackSection({text:'iPhone joystick movement broken'}),'start.controls');assert.equal(gdd.feedbackSection({text:'translated multiplayer chat voice'}),'multiplayer');assert.equal(gdd.feedbackSection({text:'FPS lag memory'}),'quality');assert.equal(gdd.feedbackSection({text:'Navigator story quest emotion'}),'coreLoop')});

test('V5 mutual reinforcement loop links Google, GDD, feedback, functions, sandbox, canary and rollback',()=>{const s=read('scripts/world-v5-system-loop.cjs');for(const x of ['world-google-deployment-learning-loop','world-game-design-feedback-bridge','world-feedback-development-bridge','world-function-delivery-gate','world-google-canary-plan','sandbox','canary','last-green','rollback'])assert.match(s,new RegExp(x,'i'));assert.match(s,/automaticProductionMutation:false/)});
test('V5 readiness requires independent live proof for Google learning, functions, GDD, canary and V4 community',()=>{const s=read('scripts/world-v5-readiness.cjs');for(const x of ['WORLD_GOOGLE_LEARNING_LIVE_VERIFIED','WORLD_FUNCTION_DELIVERY_LIVE_VERIFIED','WORLD_GAME_DESIGN_LIVE_VERIFIED','WORLD_GOOGLE_CANARY_LIVE_VERIFIED','WORLD_V4_LIVE_VERIFIED'])assert.match(s,new RegExp(x));assert.match(s,/staticPercent\*\.55\+livePercent\*\.45/)});
test('AI Studio prompts make GitHub two-way sync and same-slot revision delivery explicit',()=>{const s=read('google-ai-studio/AI_STUDIO_NAVIGATOR_PROMPT.md')+read('google-ai-studio/AI_STUDIO_SANDBOX_PROMPT.md');assert.match(s,/two-way sync/i);assert.match(s,/Game Design Spec/i);assert.match(s,/function/i);assert.match(s,/revision/i);assert.match(s,/third.*slot|third.*app/i)});

test('V5 system graph is mutually reinforcing rather than isolated',()=>{const g=JSON.parse(read('google-ai-studio/v5-system-graph.json'));const adj=new Map(g.nodes.map(n=>[n,[]]));for(const[a,b]of g.edges)adj.get(a).push(b);function reach(a){const seen=new Set([a]),q=[a];while(q.length){for(const b of adj.get(q.shift())||[])if(!seen.has(b)){seen.add(b);q.push(b)}}return seen}for(const start of ['navigator-dialogue','feedback','google-runtime','release']){const r=reach(start);for(const x of ['game-design-spec','function-registry','sandbox','tests-replay','navigator-canary','release','feedback','google-runtime'])assert.ok(r.has(x),`${start}->${x}`)}});
test('Function admin can activate only bundled revision code and Navigator rollout requires evidence',()=>{const s=read('api/function-admin.js');assert.match(s,/requireAdminUser/);assert.match(s,/Navigator rollout requires evidenceRef/);assert.match(s,/codeInstall:false/);assert.match(s,/immutableRevisionRequired:true/);assert.doesNotMatch(s,/eval\s*\(|new Function/)});
test('Function and Game Design world ids use text to match existing World_server world identifiers',()=>{assert.match(read('supabase/migration_templates/world_functions_v5.sql'),/world_id text/);assert.match(read('supabase/migration_templates/world_game_design_v5.sql'),/world_id text/);});

test('Installed V5 exposes function and Game Design APIs and all V5 gates',()=>{const pkg=JSON.parse(read('package.json')),server=read('server.js');for(const x of ['world:v5:gate','world:readiness:v5','world:google:learning','world:functions:delivery-gate','world:gdd:gate','world:v5:loop','world:v5:connectivity'])assert.ok(pkg.scripts?.[x],x);for(const route of ['function-catalog','function-invoke','function-install-request','function-admin','game-design-spec'])assert.match(server,new RegExp(route))});
