'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');const ROOT=path.resolve(__dirname,'..'),aoi=require('../lib/world-spatial-aoi'),prov=require('../lib/world-function-provenance'),reg=require('../lib/world-function-registry');const read=f=>fs.readFileSync(path.join(ROOT,f),'utf8');
test('V6 graph closes Google evidence, GDD, functions, release and feedback loop',()=>{const g=JSON.parse(read('google-ai-studio/v6-system-graph.json'));for(const n of ['google-cloud-evidence','game-design-spec','capability-planner','function-provenance','sandbox','tests-replay','release-promotion','last-green-rollback','feedback'])assert.ok(g.nodes.includes(n));assert.ok(g.edges.length>=20)});
test('Google evidence collector uses real gcloud logging and Cloud Run service description without request bodies',()=>{const s=read('scripts/world-google-cloud-evidence.cjs');for(const x of ['gcloud','logging','read','world_runtime_signal','run','services','describe'])assert.match(s,new RegExp(x));assert.doesNotMatch(s,/requestBody|chatText|feedbackText/)});
test('Rollback controller is evidence driven and cannot mutate traffic without explicit approval',()=>{const s=read('scripts/world-google-rollback-controller.cjs');assert.match(s,/WORLD_ALLOW_GOOGLE_TRAFFIC_WRITE/);assert.match(s,/update-traffic/);assert.match(s,/--to-revisions/);assert.match(s,/operatorApprovalRequired:true/);assert.match(s,/automaticTrafficMutation:false/)});
test('Function provenance reuses existing SBOM and supply-chain systems instead of second signer',()=>{const s=read('scripts/world-function-provenance.cjs');assert.match(s,/integration:sbom/);assert.match(s,/integration:supply-chain/);assert.match(s,/SUPPLY_CHAIN_SIGNATURE_STATUS/);assert.doesNotMatch(s,/generateKeyPairSync|crypto\.sign/)});
test('Function provenance envelope binds code, manifest, GDD and acceptance hashes',()=>{const pkg=reg.inspectPackage(path.join(ROOT,'world-functions/world-spec-summary')),e=prov.envelope(ROOT,pkg);for(const k of ['manifestSha256','sourceSha256','gddSha256'])assert.match(String(e[k]),/^[a-f0-9]{64}$/);assert.equal(e.installMode,'revision')});
test('GDD capability planner is reuse-first and never auto generates code',()=>{const s=read('scripts/world-gdd-capability-planner.cjs');assert.match(s,/REUSE/);assert.match(s,/REQUEST_MINIMAL_FUNCTION/);assert.match(s,/automaticCodeGeneration:false/);assert.match(read('game-design/capability-map-v6.json'),/reuse-before-create/)});
test('Generated GDD tests cover Navigator, multiplayer, languages, feedback, functions, Google and AOI',()=>{const s=read('scripts/world-gdd-generated-test-runner.cjs');for(const x of ['Navigator','multiplayer','11-language','feedback','safe functions','Google slots','AOI'])assert.match(s,new RegExp(x,'i'))});
test('Spatial AOI reduces replication set and adaptive tick decreases with distance/background',()=>{const ents=[{id:1,position:{x:0,z:0}},{id:2,position:{x:500,z:500}}];assert.deepEqual(aoi.selectVisible(ents,{position:{x:0,z:0}},{cellSize:32,radiusCells:1}).map(x=>x.id),[1]);assert.equal(aoi.recommendedHz({distance:5,roomSize:5}),20);assert.equal(aoi.recommendedHz({distance:200,roomSize:100}),3);assert.equal(aoi.recommendedHz({background:true}),2)});
test('Distributed limiter migration has no browser grants and uses server RPC',()=>{const sql=read('supabase/migration_templates/world_rate_limit_v6.sql');assert.match(sql,/world_consume_rate_limit_v6/);assert.match(sql,/enable row level security/);assert.match(sql,/revoke all.*anon, authenticated/i);assert.match(read('lib/world-distributed-rate-limit.js'),/\.rpc\('world_consume_rate_limit_v6'/)});
test('Function admin console separates code install from rollout and exposes staged percentages',()=>{const s=read('apps/function-admin/index.html');for(const x of ['0,1,5,25,50,100','immutable revision','evidenceRef','Disable / rollback function'])assert.match(s,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.doesNotMatch(s,/eval\s*\(|new Function/)});
test('Cost optimizer is quality first and sandbox only',()=>{const s=read('scripts/world-google-cost-quality-optimizer.cjs');assert.match(s,/qualityFirst:true/);assert.match(s,/sandbox only/);assert.match(s,/automaticCloudMutation:false/)});
test('V6 readiness keeps static and live proof independent',()=>{const s=read('scripts/world-v6-readiness.cjs');for(const x of ['WORLD_GOOGLE_CLOUD_EVIDENCE_LIVE_VERIFIED','WORLD_GOOGLE_ROLLBACK_DRILL_LIVE_VERIFIED','WORLD_FUNCTION_PROVENANCE_LIVE_VERIFIED','WORLD_AOI_MULTIPLAYER_LIVE_VERIFIED','WORLD_V5_LIVE_VERIFIED'])assert.match(s,new RegExp(x));assert.match(s,/staticPercent\*\.55\+livePercent\*\.45/)});
test('V6 system loop routes evidence through GDD, provenance, sandbox/canary and rollback',()=>{const s=read('scripts/world-v6-system-loop.cjs');for(const x of ['world-google-cloud-evidence','world-gdd-capability-planner','world-function-provenance','world-authoritative-aoi-gate','world-google-canary-plan','world-google-rollback-controller'])assert.match(s,new RegExp(x));assert.match(s,/automaticProductionMutation:false/)});

test('Cloud Run logging is queryable by event and correlates to Google Cloud Trace',()=>{const s=read('google-ai-studio/cloudrun-entry.cjs');assert.match(s,/event:'world_runtime_signal'/);assert.match(s,/logging.googleapis.com\/trace/);assert.match(s,/x-cloud-trace-context/);assert.match(s,/controllerVersion: 6/)});
test('Monitoring and Trace collector uses official read-only APIs',()=>{const s=read('scripts/world-google-monitoring-trace-pull.cjs');assert.match(s,/monitoring.googleapis.com\/v3\/projects/);assert.match(s,/cloudtrace.googleapis.com\/v1\/projects/);for(const m of ['run.googleapis.com/request_count','run.googleapis.com/request_latencies','run.googleapis.com/container/startup_latencies'])assert.match(s,new RegExp(m.replace(/[.\/]/g,'\\$&')));assert.match(s,/auth','print-access-token/)});
test('WASI sandbox keeps untrusted functions out of Node and reuses existing Wasmtime toolchain',()=>{const gate=read('scripts/world-function-wasi-sandbox-gate.cjs'),runner=read('scripts/world-wasi-runner.cjs');assert.match(gate,/integration:toolchain/);assert.match(gate,/integration:wit/);assert.match(gate,/untrustedFutureFunctions:'WASM\/WASI only'/);assert.match(runner,/wasmtime/);assert.match(runner,/world-functions-wasm/);assert.doesNotMatch(runner,/shell:true/)});
test('Feedback Resolution Ledger requires post-release outcome verification',()=>{const s=read('scripts/world-feedback-resolution-ledger.cjs'),sql=read('supabase/migration_templates/world_feedback_resolution_v6.sql');for(const x of ['feedback/cluster','GDD change candidate','commit SHA','sandbox revision','production revision','post-release outcome verification'])assert.match(s,new RegExp(x,'i'));assert.match(s,/shipping code alone is not resolution/i);assert.match(sql,/verified_better/);assert.match(sql,/reopened/)});
test('LiveKit SFU token stays server-side and uses opaque room/user identities',()=>{const s=read('api/livekit-token.js'),c=JSON.parse(read('google-ai-studio/voice-scale-contract-v6.json'));assert.match(s,/requireUser/);assert.match(s,/LIVEKIT_API_SECRET/);assert.match(s,/crypto.createHash/);assert.match(s,/ttl:'10m'/);assert.match(s,/apiSecretExposed:false/);assert.doesNotMatch(s,/sendJson\([^\n]*secret/);assert.equal(c.largeRoomMode,'livekit-sfu')});
test('Voice router uses mesh for small rooms, SFU for large rooms, text fallback without SFU',()=>{const r=require('../shared/multiplayer/world-voice-router');assert.equal(r.chooseVoiceTransport({participants:4,sfuAvailable:true}).mode,'mesh');assert.equal(r.chooseVoiceTransport({participants:12,sfuAvailable:true}).mode,'livekit-sfu');assert.equal(r.chooseVoiceTransport({participants:12,sfuAvailable:false}).mode,'text-fallback')});
test('Authoritative core consumes input intent and AOI snapshots hide distant players',()=>{const {AuthorityCore}=require('../services/world-authority/authority-core'),a=new AuthorityCore();a.join('a');a.join('b',{x:500,z:500});const before=a.players.get('a').position.x;assert.equal(a.applyInput('a',{seq:1,dt:.05,x:1,z:0}).ok,true);assert.ok(a.players.get('a').position.x>before);assert.deepEqual(a.snapshotFor('a').players.map(x=>x.id),['a']);assert.equal(a.applyInput('a',{seq:1,dt:.05,x:1,z:0}).reason,'stale-input')});
test('Distributed limiter is actually wired into multiplayer, GDD, votes and function delivery writes',()=>{for(const f of ['api/community-message.js','api/game-design-spec.js','api/feature-vote.js','api/function-install-request.js','api/function-admin.js','api/livekit-token.js']){const s=read(f);assert.match(s,/world-distributed-rate-limit/);assert.match(s,/await consume\(/)}});
test('Existing supply-chain signing policy is extended to sign function provenance bundle',()=>{const policyPath=path.join(ROOT,'data/supply-chain-signing-policy.json');if(fs.existsSync(policyPath)){const policy=JSON.parse(fs.readFileSync(policyPath,'utf8'));assert.ok(policy.artifacts.includes('WORLD_FUNCTION_PROVENANCE_BUNDLE.json'));assert.ok(policy.artifacts.includes('SYSTEM_INTEGRATION_REPORT.json'))}else{const installer=fs.readFileSync(path.resolve(ROOT,'../apply.cjs'),'utf8');assert.match(installer,/patchSupplyChainPolicy/);assert.match(installer,/WORLD_FUNCTION_PROVENANCE_BUNDLE\.json/);assert.match(installer,/policy\.artifacts\.push\(artifact\)/)}});

test('V6 Cloud evidence contract explicitly protects private user content',()=>{const c=JSON.parse(read('google-ai-studio/google-cloud-evidence-contract-v6.json'));assert.ok(c.privacy.includes('no chat text'));assert.ok(c.privacy.includes('no feedback text'));assert.match(c.hardRule,/explicit operator approval/)});

test('Cloud Run allows same-origin microphone for voice while camera and geolocation remain denied',()=>{const s=read('google-ai-studio/cloudrun-entry.cjs');assert.match(s,/camera=\(\), microphone=\(self\), geolocation=\(\)/);assert.doesNotMatch(s,/microphone=\(\)/)});
