from __future__ import annotations

import hashlib
import json
import math
import statistics
from pathlib import Path
from typing import Any, Iterable

SCHEMA_VERSION = 12


def _ratio_score(value: Any) -> float:
    if isinstance(value, bool):
        return 1.0 if value else 0.0
    if isinstance(value, (int, float)):
        return max(0.0, min(float(value), 1.0))
    if isinstance(value, dict):
        if "passed" in value:
            return 1.0 if bool(value.get("passed")) else 0.0
        if "confidence" in value:
            return max(0.0, min(float(value.get("confidence") or 0.0), 1.0))
        if "confidencePercent" in value:
            return max(0.0, min(float(value.get("confidencePercent") or 0.0) / 100.0, 1.0))
    return 0.0


def _percentile(values: list[float], q: float) -> float:
    if not values:
        return 0.0
    vals = sorted(float(v) for v in values)
    if len(vals) == 1:
        return vals[0]
    pos = max(0.0, min(1.0, q)) * (len(vals) - 1)
    lo = int(math.floor(pos))
    hi = int(math.ceil(pos))
    if lo == hi:
        return vals[lo]
    f = pos - lo
    return vals[lo] * (1.0 - f) + vals[hi] * f


def artifact_hygiene_gate_v12(root_or_paths: Path | str | Iterable[Path | str], policy: dict | None = None) -> dict:
    p = dict(policy or {})
    forbidden_dirs = set(p.get("forbiddenDirs") or ["__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"])
    forbidden_suffixes = set(p.get("forbiddenSuffixes") or [".pyc", ".pyo", ".swp", ".swo", ".tmp", ".bak"])
    forbidden_names = set(p.get("forbiddenNames") or [".DS_Store", "Thumbs.db"])

    if isinstance(root_or_paths, (str, Path)):
        root = Path(root_or_paths)
        paths = list(root.rglob("*")) if root.is_dir() else [root]
    else:
        paths = [Path(x) for x in root_or_paths]

    violations: list[dict] = []
    for path in paths:
        parts = set(path.parts)
        if parts & forbidden_dirs:
            violations.append({"path": str(path), "reason": "forbidden_generated_directory"})
            continue
        if path.suffix.lower() in forbidden_suffixes:
            violations.append({"path": str(path), "reason": "forbidden_generated_suffix"})
        elif path.name in forbidden_names:
            violations.append({"path": str(path), "reason": "forbidden_generated_file"})

    return {
        "schemaVersion": SCHEMA_VERSION,
        "status": "CLEAN" if not violations else "DIRTY_RELEASE_ARTIFACTS",
        "passed": not violations,
        "violations": violations,
        "rule": "Generated bytecode/cache/temp artifacts are forbidden in distributable patch payloads.",
    }


def compatibility_matrix_gate_v12(rows: list[dict], policy: dict | None = None) -> dict:
    p = dict(policy or {})
    required = [str(x).lower() for x in (p.get("requiredEngines") or ["blender", "godot"])]
    require_smoke = bool(p.get("requireSmoke", True))
    expected_prefixes = {str(k).lower(): [str(v) for v in vals] for k, vals in (p.get("acceptedVersionPrefixes") or {}).items()}
    normalized = []
    for row in rows or []:
        engine = str(row.get("engine") or "").strip().lower()
        if not engine:
            continue
        version = str(row.get("version") or "").strip()
        available = bool(row.get("available", True))
        smoke = bool(row.get("smokePassed", row.get("passed", False)))
        version_ok = bool(version)
        if engine in expected_prefixes and expected_prefixes[engine]:
            version_ok = any(version.startswith(prefix) for prefix in expected_prefixes[engine])
        normalized.append({**row, "engine": engine, "version": version, "available": available, "smokePassed": smoke, "versionAccepted": version_ok})

    failures = []
    coverage = {}
    for engine in required:
        candidates = [r for r in normalized if r["engine"] == engine]
        accepted = [r for r in candidates if r["available"] and r["versionAccepted"] and (r["smokePassed"] or not require_smoke)]
        coverage[engine] = {"tested": len(candidates), "accepted": len(accepted), "versions": sorted({r["version"] for r in candidates if r["version"]})}
        if not accepted:
            failures.append(f"{engine}:no_verified_compatible_runtime")
    # Any explicitly tested known version that fails smoke is a regression signal.
    smoke_failures = [r for r in normalized if r["available"] and r["versionAccepted"] and not r["smokePassed"]]
    if require_smoke and smoke_failures:
        failures.extend(f"{r['engine']}:{r['version']}:smoke_failed" for r in smoke_failures)

    passed = not failures
    return {
        "schemaVersion": SCHEMA_VERSION,
        "status": "COMPATIBLE_MATRIX_VERIFIED" if passed else ("UNVERIFIED_COMPATIBILITY" if not normalized else "COMPATIBILITY_FAILURE"),
        "passed": passed,
        "requiredEngines": required,
        "coverage": coverage,
        "rows": normalized,
        "failures": failures,
    }


def shader_stutter_gate_v12(samples: list[dict], policy: dict | None = None) -> dict:
    p = dict(policy or {})
    min_samples = max(1, int(p.get("minSamples", 60)))
    warmup_frames = max(0, int(p.get("warmupFrames", 30)))
    target_frame_ms = float(p.get("targetFrameMs", 33.34))
    max_p95 = float(p.get("maxP95FrameMs", target_frame_ms * 1.5))
    max_p99 = float(p.get("maxP99FrameMs", target_frame_ms * 2.0))
    stutter_threshold = float(p.get("stutterFrameMs", max(target_frame_ms * 2.0, 50.0)))
    max_stutter_ratio = float(p.get("maxStutterRatio", 0.01))
    max_postwarmup_compiles = max(0, int(p.get("maxPostWarmupShaderCompileEvents", 0)))
    require_compile_observability = bool(p.get("requireShaderCompileObservability", True))

    rows = [r for r in (samples or []) if isinstance(r, dict) and isinstance(r.get("frameTimeMs"), (int, float))]
    measured = rows[warmup_frames:] if len(rows) > warmup_frames else []
    frame_times = [float(r["frameTimeMs"]) for r in measured]
    compile_events = [r for r in measured if bool(r.get("shaderCompileEvent")) or (isinstance(r.get("shaderCompileMs"),(int,float)) and float(r.get("shaderCompileMs") or 0.0) > 0.0)]
    compile_observable = any(str(r.get("shaderCompileTelemetry") or "").upper() in {"INSTRUMENTED","ENGINE","VENDOR","MEASURED"} for r in measured)
    stutters = [v for v in frame_times if v > stutter_threshold]
    ratio = len(stutters) / len(frame_times) if frame_times else 1.0
    p95 = _percentile(frame_times, 0.95)
    p99 = _percentile(frame_times, 0.99)
    enough = len(frame_times) >= min_samples
    passed = enough and p95 <= max_p95 and p99 <= max_p99 and ratio <= max_stutter_ratio and len(compile_events) <= max_postwarmup_compiles and (compile_observable or not require_compile_observability)
    failures = []
    if not enough: failures.append("insufficientMeasuredFrames")
    if frame_times and p95 > max_p95: failures.append("p95FrameTimeTooHigh")
    if frame_times and p99 > max_p99: failures.append("p99FrameTimeTooHigh")
    if frame_times and ratio > max_stutter_ratio: failures.append("stutterRatioTooHigh")
    if len(compile_events) > max_postwarmup_compiles: failures.append("postWarmupShaderCompilationDetected")
    if require_compile_observability and not compile_observable: failures.append("shaderCompileTelemetryUnobservable")
    return {
        "schemaVersion": SCHEMA_VERSION,
        "status": "SHADER_STUTTER_PASS" if passed else ("UNVERIFIED_NO_RUNTIME_SAMPLES" if not rows else "SHADER_STUTTER_FAIL"),
        "passed": passed,
        "measuredFrames": len(frame_times),
        "warmupFramesExcluded": min(warmup_frames, len(rows)),
        "p95FrameMs": round(p95, 4),
        "p99FrameMs": round(p99, 4),
        "stutterRatio": round(ratio, 6),
        "postWarmupShaderCompileEvents": len(compile_events),
        "shaderCompileObservable": compile_observable,
        "failures": failures,
    }


def thermal_memory_pressure_gate_v12(samples: list[dict], policy: dict | None = None) -> dict:
    p = dict(policy or {})
    min_samples = max(2, int(p.get("minSamples", 30)))
    max_fps_drop = float(p.get("maxFpsDropRatio", 0.20))
    max_rss_growth = float(p.get("maxRssGrowthRatio", 0.25))
    max_vram_growth = float(p.get("maxVramGrowthRatio", 0.30))
    max_temp_c = float(p.get("maxTemperatureC", 90.0))
    severe_states = {str(x).lower() for x in (p.get("severeThermalStates") or ["serious", "critical", "shutdown"])}
    critical_memory = {str(x).lower() for x in (p.get("criticalMemoryPressure") or ["critical", "oom", "out_of_memory"])}

    rows = [r for r in (samples or []) if isinstance(r, dict)]
    fps = [float(r["fps"]) for r in rows if isinstance(r.get("fps"), (int, float)) and float(r["fps"]) > 0]
    if not fps:
        fps = [1000.0/float(r["frameTimeMs"]) for r in rows if isinstance(r.get("frameTimeMs"),(int,float)) and float(r["frameTimeMs"])>0]
    rss = [float(r["rssMb"]) for r in rows if isinstance(r.get("rssMb"), (int, float)) and float(r["rssMb"]) >= 0]
    vram = [float(r["vramMb"]) for r in rows if isinstance(r.get("vramMb"), (int, float)) and float(r["vramMb"]) >= 0]
    temps = [float(r["temperatureC"]) for r in rows if isinstance(r.get("temperatureC"), (int, float))]

    def edge_drop(values: list[float]) -> float:
        if len(values) < 4:
            return 0.0
        n = max(1, len(values) // 4)
        a = statistics.median(values[:n])
        b = statistics.median(values[-n:])
        return max(0.0, (a - b) / a) if a > 0 else 0.0

    def growth(values: list[float]) -> float:
        if len(values) < 2:
            return 0.0
        base = statistics.median(values[:max(1, len(values)//4)])
        end = statistics.median(values[-max(1, len(values)//4):])
        return max(0.0, (end - base) / max(base, 1e-9))

    fps_drop = edge_drop(fps)
    rss_growth = growth(rss)
    vram_growth = growth(vram)
    severe = [r for r in rows if str(r.get("thermalState") or "").lower() in severe_states]
    memory_critical = [r for r in rows if str(r.get("memoryPressure") or "").lower() in critical_memory]
    state_signal = any(str(r.get("thermalState") or "").upper() not in {"","UNAVAILABLE","UNKNOWN"} or str(r.get("memoryPressure") or "").upper() not in {"","UNAVAILABLE","UNKNOWN"} for r in rows)
    pressure_observable = bool(rss or vram or temps or state_signal)
    failures = []
    if len(rows) < min_samples: failures.append("insufficientPressureSamples")
    if not pressure_observable: failures.append("noMemoryOrThermalPressureMetric")
    if fps and fps_drop > max_fps_drop: failures.append("sustainedFpsDegradation")
    if rss and rss_growth > max_rss_growth: failures.append("rssGrowthTooHigh")
    if vram and vram_growth > max_vram_growth: failures.append("vramGrowthTooHigh")
    if temps and max(temps) > max_temp_c: failures.append("temperatureTooHigh")
    if severe: failures.append("severeThermalStateObserved")
    if memory_critical: failures.append("criticalMemoryPressureObserved")
    passed = not failures
    return {
        "schemaVersion": SCHEMA_VERSION,
        "status": "PRESSURE_PASS" if passed else ("UNVERIFIED_PRESSURE" if not rows else "PRESSURE_FAIL"),
        "passed": passed,
        "samples": len(rows),
        "fpsDropRatio": round(fps_drop, 6),
        "rssGrowthRatio": round(rss_growth, 6),
        "vramGrowthRatio": round(vram_growth, 6),
        "maxTemperatureC": max(temps) if temps else None,
        "pressureObservable": pressure_observable,
        "failures": failures,
    }


def adversarial_corpus_gate_v12(results: list[dict], policy: dict | None = None) -> dict:
    p = dict(policy or {})
    required = list(p.get("requiredFaultClasses") or [
        "bad_magic", "truncated_glb", "length_mismatch", "missing_bin_chunk",
        "nan_vertex", "index_oob", "degenerate_mesh", "invalid_material_numeric",
        "invalid_rig_weights", "animation_nan",
    ])
    by_class = {str(r.get("faultClass")): r for r in (results or []) if isinstance(r, dict)}
    missing = [name for name in required if name not in by_class]
    undetected = [name for name in required if name in by_class and not (bool(by_class[name].get("detected")) and bool(by_class[name].get("detectorFailedClosed", True)))]
    passed = not missing and not undetected
    return {
        "schemaVersion": SCHEMA_VERSION,
        "status": "ADVERSARIAL_CORPUS_PASS" if passed else "ADVERSARIAL_CORPUS_FAIL",
        "passed": passed,
        "requiredFaultClasses": required,
        "missing": missing,
        "undetected": undetected,
        "results": list(results or []),
    }


def autofix_progress_gate_v12(attempts: list[dict], policy: dict | None = None) -> dict:
    p = dict(policy or {})
    stall_limit = max(1, int(p.get("stallLimit", 3)))
    rows = [r for r in (attempts or []) if isinstance(r, dict)]
    if not rows:
        return {"schemaVersion": SCHEMA_VERSION, "status": "NO_ATTEMPTS", "passed": False, "continueRequired": True, "attempts": 0}
    latest = rows[-1]
    remaining = list(latest.get("openAfter") or [])
    all_checks = bool(latest.get("checksPassed", False))
    converged = not remaining and all_checks
    sets = [tuple(sorted(str(x) for x in (r.get("openAfter") or []))) for r in rows]
    same_tail = 1
    for i in range(len(sets)-2, -1, -1):
        if sets[i] == sets[-1]: same_tail += 1
        else: break
    new_errors = sum(len(r.get("introducedNew") or []) for r in rows)
    if converged:
        status = "AUTOFIX_CONVERGED"
    elif same_tail >= stall_limit:
        status = "ROOT_CAUSE_ESCALATION_REQUIRED"
    else:
        status = "CONTINUE_AUTOFIX_LOOP"
    return {
        "schemaVersion": SCHEMA_VERSION,
        "status": status,
        "passed": converged,
        "continueRequired": not converged,
        "attempts": len(rows),
        "remainingFingerprints": remaining,
        "sameFailureSetTail": same_tail,
        "introducedNewCount": new_errors,
        "rule": "Never report completion while continueRequired=true. Stalls require broader root-cause/impact analysis, not repeated identical patches.",
    }


def quality_confidence_v12(layers: dict, policy: dict | None = None) -> dict:
    p = dict(policy or {})
    critical = list(p.get("criticalLayers") or [
        "static", "zeroErrors", "regression", "adversarial", "compatibility",
        "shaderStutter", "pressure", "runtime", "fleet", "profiler", "roblox",
    ])
    scores = {name: _ratio_score((layers or {}).get(name)) for name in critical}
    minimum = min(scores.values(), default=0.0)
    geometric = 0.0
    if scores:
        safe = [max(v, 1e-9) for v in scores.values()]
        geometric = math.prod(safe) ** (1.0 / len(safe))
    confidence = min(minimum, geometric)
    passed = all(v >= 0.999999 for v in scores.values())
    return {
        "schemaVersion": SCHEMA_VERSION,
        "status": "V12_FULL_EVIDENCE" if passed else "V12_EVIDENCE_INCOMPLETE",
        "passed": passed,
        "confidencePercent": round(confidence * 100.0, 4),
        "layerScores": scores,
        "missingOrFailing": [k for k, v in scores.items() if v < 0.999999],
        "model": "non-compensating minimum bounded by geometric mean",
    }


def convergence_gate_v12(*, v11: dict, artifact_hygiene: dict, adversarial: dict, compatibility: dict, shader_stutter: dict, pressure: dict, autofix: dict | None = None, external_blockers: list[dict] | None = None, policy: dict | None = None) -> dict:
    p = dict(policy or {})
    required = {
        "v11": bool((v11 or {}).get("passed")),
        "artifactHygiene": bool((artifact_hygiene or {}).get("passed")),
        "adversarial": bool((adversarial or {}).get("passed")),
    }
    if bool(p.get("requireCompatibility", False)): required["compatibility"] = bool((compatibility or {}).get("passed"))
    if bool(p.get("requireShaderStutter", False)): required["shaderStutter"] = bool((shader_stutter or {}).get("passed"))
    if bool(p.get("requirePressure", False)): required["pressure"] = bool((pressure or {}).get("passed"))
    if autofix is not None: required["autofix"] = bool(autofix.get("passed"))
    blockers = list(external_blockers or [])
    if all(required.values()) and not blockers:
        status = "CONVERGED_ZERO_KNOWN_ERRORS_V12"
        passed = True
    elif blockers and bool((v11 or {}).get("passed")):
        status = "EXTERNALLY_BLOCKED_NOT_FULLY_VERIFIED_V12"
        passed = False
    else:
        status = "CONTINUE_FIX_LOOP_V12"
        passed = False
    return {
        "schemaVersion": SCHEMA_VERSION,
        "status": status,
        "passed": passed,
        "requiredGates": required,
        "externalBlockers": blockers,
        "rule": "Do not stop while status is CONTINUE_FIX_LOOP_V12. External blockers never count as verification PASS.",
    }


def write_v12_runtime_pack(job_dir: Path, policy: dict | None = None) -> list[Path]:
    """Emit real target-side collectors for V12 shader stutter and pressure evidence.

    Unsupported counters remain null/UNAVAILABLE; collectors never infer GPU timings from FPS.
    """
    root = Path(job_dir)
    root.mkdir(parents=True, exist_ok=True)
    web = root / "web_runtime_collector_v12.js"
    web.write_text(r'''export function createAI3DV12Collector({warmupFrames=30,maxFrames=600}={}){
  const rows=[]; let frame=0,last=performance.now(); let shaderCompileFlag=false,shaderCompileMs=0;
  const longTasks=[];
  let observer=null;
  try{ observer=new PerformanceObserver(list=>{for(const e of list.getEntries()) longTasks.push({startTime:e.startTime,duration:e.duration});}); observer.observe({entryTypes:['longtask']}); }catch(_e){}
  function markShaderCompile(durationMs=0){shaderCompileFlag=true;shaderCompileMs+=Number(durationMs)||0;}
  function sample(now=performance.now()){
    const dt=now-last; last=now; frame++;
    const mem=(performance && performance.memory)?performance.memory:null;
    rows.push({
      frameTimeMs:dt,
      shaderCompileEvent:shaderCompileFlag,
      shaderCompileMs,
      rssMb:mem?Number(mem.usedJSHeapSize)/1048576:null,
      vramMb:null,
      temperatureC:null,
      thermalState:'UNAVAILABLE',
      memoryPressure:'UNAVAILABLE',
      telemetrySource:'browser-performance-api',
      shaderCompileTelemetry:'INSTRUMENTED',
      warmup:frame<=warmupFrames
    });
    shaderCompileFlag=false; shaderCompileMs=0;
    if(rows.length<maxFrames) requestAnimationFrame(sample);
  }
  return {rows,longTasks,markShaderCompile,start(){requestAnimationFrame(sample);},result(){return {schemaVersion:12,executedInTarget:true,target:'web',rows,longTasks};}};
}
''', encoding="utf-8")

    godot = root / "godot_runtime_collector_v12.gd"
    godot.write_text(r'''extends Node
var samples:Array = []
var warmup_frames := 30
var max_frames := 600
var frame := 0
func _ready():
    RenderingServer.viewport_set_measure_render_time(get_viewport().get_viewport_rid(), true)
func _process(_delta):
    frame += 1
    var rid=get_viewport().get_viewport_rid()
    var fps=float(Performance.get_monitor(Performance.TIME_FPS))
    var process_s=float(Performance.get_monitor(Performance.TIME_PROCESS))
    var row={
        "frameTimeMs": process_s*1000.0,
        "fps": fps,
        "gpuFrameMs": RenderingServer.viewport_get_measured_render_time_gpu(rid),
        "cpuRenderMs": RenderingServer.viewport_get_measured_render_time_cpu(rid),
        "rssMb": float(Performance.get_monitor(Performance.MEMORY_STATIC))/1048576.0,
        "vramMb": float(Performance.get_monitor(Performance.RENDER_VIDEO_MEM_USED))/1048576.0,
        "shaderCompileEvent": null,
        "shaderCompileMs": null,
        "shaderCompileTelemetry": "UNAVAILABLE",
        "temperatureC": null,
        "thermalState": "UNAVAILABLE",
        "memoryPressure": "UNAVAILABLE",
        "telemetrySource": "Godot Performance + RenderingServer",
        "warmup": frame<=warmup_frames
    }
    samples.append(row)
    if samples.size()>=max_frames:
        print("[AI3D_V12_RUNTIME]"+JSON.stringify({"schemaVersion":12,"executedInTarget":true,"target":"godot","rows":samples}))
        get_tree().quit()
''', encoding="utf-8")

    contract = root / "runtime-evidence-contract-v12.json"
    contract.write_text(json.dumps({
        "schemaVersion": 12,
        "requiredMeasuredFields": ["frameTimeMs"],
        "optionalMeasuredFields": ["gpuFrameMs", "cpuRenderMs", "rssMb", "vramMb", "temperatureC", "thermalState", "memoryPressure", "shaderCompileEvent", "shaderCompileMs"],
        "forbiddenEvidenceKinds": ["synthetic", "estimated", "placeholder"],
        "rule": "Null/UNAVAILABLE is allowed for unsupported counters. Fabricated substitutes are forbidden.",
    }, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return [web, godot, contract]
