create table if not exists public.gap_closure_registry (
  id bigint generated by default as identity primary key,
  gap_key text not null unique,
  domain text not null,
  severity text not null check (severity in ('info','warning','major','blocker')),
  source text not null,
  title text not null,
  description text not null default '',
  status text not null default 'detected' check (status in ('detected','queued','fixing','verifying','canary','closed','blocked')),
  auto_fixable boolean not null default false,
  attempts integer not null default 0,
  max_attempts integer not null default 3,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  next_check_at timestamptz,
  closed_at timestamptz,
  evidence jsonb not null default '{}'::jsonb,
  fix_strategy jsonb not null default '{}'::jsonb,
  last_error text
);
create index if not exists gap_closure_registry_status_idx on public.gap_closure_registry(status, severity, last_seen_at desc);
create index if not exists gap_closure_registry_domain_idx on public.gap_closure_registry(domain, status);

create table if not exists public.gap_closure_evidence (
  id bigint generated by default as identity primary key,
  gap_key text not null references public.gap_closure_registry(gap_key) on delete cascade,
  evidence_type text not null,
  source text not null,
  passed boolean not null,
  payload jsonb not null default '{}'::jsonb,
  observed_at timestamptz not null default now()
);
create index if not exists gap_closure_evidence_gap_idx on public.gap_closure_evidence(gap_key, observed_at desc);

create table if not exists public.gap_closure_runs (
  id bigint generated by default as identity primary key,
  trigger text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  detected integer not null default 0,
  reopened integer not null default 0,
  closed integer not null default 0,
  queued integer not null default 0,
  blocked integer not null default 0,
  result jsonb not null default '{}'::jsonb
);

alter table public.gap_closure_registry enable row level security;
alter table public.gap_closure_evidence enable row level security;
alter table public.gap_closure_runs enable row level security;
revoke all on public.gap_closure_registry from anon, authenticated;
revoke all on public.gap_closure_evidence from anon, authenticated;
revoke all on public.gap_closure_runs from anon, authenticated;

do $$
begin
  if exists (select 1 from pg_roles where rolname='service_role') then
    grant select, insert, update, delete on public.gap_closure_registry to service_role;
    grant select, insert, update, delete on public.gap_closure_evidence to service_role;
    grant select, insert, update, delete on public.gap_closure_runs to service_role;
    grant usage, select on all sequences in schema public to service_role;
  end if;
end $$;

create or replace function private.gap_closure_sync_gap(
  p_gap_key text,
  p_domain text,
  p_severity text,
  p_title text,
  p_description text,
  p_present boolean,
  p_auto_fixable boolean,
  p_evidence jsonb,
  p_fix_strategy jsonb,
  p_now timestamptz
) returns integer
language plpgsql
security definer
set search_path = public, private, pg_catalog
as $$
declare
  v_was_closed boolean := false;
begin
  select status='closed' into v_was_closed from public.gap_closure_registry where gap_key=p_gap_key;
  if p_present then
    insert into public.gap_closure_registry(
      gap_key, domain, severity, source, title, description, status, auto_fixable,
      first_seen_at, last_seen_at, next_check_at, closed_at, evidence, fix_strategy, last_error
    ) values (
      p_gap_key, p_domain, p_severity, 'db-cycle', p_title, p_description,
      case when p_auto_fixable then 'queued' else 'detected' end,
      p_auto_fixable, p_now, p_now, p_now + interval '10 minutes', null,
      coalesce(p_evidence,'{}'::jsonb), coalesce(p_fix_strategy,'{}'::jsonb), null
    )
    on conflict (gap_key) do update set
      domain=excluded.domain,
      severity=excluded.severity,
      source=excluded.source,
      title=excluded.title,
      description=excluded.description,
      status=case when public.gap_closure_registry.status='closed' then excluded.status else public.gap_closure_registry.status end,
      auto_fixable=excluded.auto_fixable,
      last_seen_at=p_now,
      next_check_at=p_now + interval '10 minutes',
      closed_at=null,
      evidence=excluded.evidence,
      fix_strategy=excluded.fix_strategy,
      last_error=null;
    insert into public.gap_closure_evidence(gap_key,evidence_type,source,passed,payload,observed_at)
    values(p_gap_key,'detector','db-cycle',false,coalesce(p_evidence,'{}'::jsonb),p_now);
    return case when v_was_closed then 2 else 1 end;
  end if;

  update public.gap_closure_registry
  set status='closed', closed_at=p_now, last_seen_at=p_now, next_check_at=null,
      evidence=coalesce(p_evidence,evidence), last_error=null
  where gap_key=p_gap_key and status <> 'closed';
  if found then
    insert into public.gap_closure_evidence(gap_key,evidence_type,source,passed,payload,observed_at)
    values(p_gap_key,'verification','db-cycle',true,coalesce(p_evidence,'{}'::jsonb),p_now);
    return -1;
  end if;
  return 0;
end;
$$;
revoke all on function private.gap_closure_sync_gap(text,text,text,text,text,boolean,boolean,jsonb,jsonb,timestamptz) from public, anon, authenticated;

create or replace function public.run_gap_closure_db_cycle(p_trigger text default 'scheduled')
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_catalog
as $$
declare
  v_run_id bigint;
  v_detected integer := 0;
  v_reopened integer := 0;
  v_closed integer := 0;
  v_queued integer := 0;
  v_change integer := 0;
  v_latest_telemetry timestamptz;
  v_profiles bigint := 0;
  v_manifests bigint := 0;
  v_device_reports bigint := 0;
  v_stuck_jobs bigint := 0;
  v_anon_definer bigint := 0;
  v_auth_definer bigint := 0;
  v_now timestamptz := now();
  v_job_key text;
begin
  insert into public.gap_closure_runs(trigger) values(coalesce(nullif(p_trigger,''),'scheduled')) returning id into v_run_id;

  select max(created_at) into v_latest_telemetry from public.quality_telemetry;
  v_change := private.gap_closure_sync_gap(
    'runtime.telemetry.stale','observability','major','Runtime telemetry is stale',
    'Fresh production telemetry is required before runtime quality can be considered verified.',
    v_latest_telemetry is null or v_latest_telemetry < v_now - interval '20 minutes',true,
    jsonb_build_object('latestTelemetryAt',v_latest_telemetry,'requiredFreshnessMinutes',20),
    jsonb_build_object('action','refresh-runtime-probe','closeOnlyAfter','fresh quality_telemetry evidence'),v_now);
  if v_change=1 then v_detected:=v_detected+1; elsif v_change=2 then v_detected:=v_detected+1; v_reopened:=v_reopened+1; elsif v_change=-1 then v_closed:=v_closed+1; end if;

  select count(*) into v_profiles from public.pixel_animation_profiles;
  select count(*) into v_manifests from public.pixel_animation_atlas_manifests;
  v_change := private.gap_closure_sync_gap(
    'pixel.animation.atlas.missing','animation','major','Pixel animation atlas is not materialized',
    'Animation profiles exist but no atlas manifest is recorded.',
    v_profiles > 0 and v_manifests = 0,true,
    jsonb_build_object('profiles',v_profiles,'atlasManifests',v_manifests),
    jsonb_build_object('action','build-pixel-atlas','closeOnlyAfter','manifest count > 0 and verification pass'),v_now);
  if v_change=1 then v_detected:=v_detected+1; elsif v_change=2 then v_detected:=v_detected+1; v_reopened:=v_reopened+1; elsif v_change=-1 then v_closed:=v_closed+1; end if;

  select count(*) into v_device_reports from public.procedural_quality_device_reports;
  v_change := private.gap_closure_sync_gap(
    'runtime.real-device.evidence.missing','devices','major','Physical device evidence is missing',
    'Production readiness must include evidence from real iOS and Android devices, not emulation only.',
    v_device_reports = 0,false,
    jsonb_build_object('deviceReports',v_device_reports),
    jsonb_build_object('action','run-real-device-provider','required','verified iOS + Android samples'),v_now);
  if v_change=1 then v_detected:=v_detected+1; elsif v_change=2 then v_detected:=v_detected+1; v_reopened:=v_reopened+1; elsif v_change=-1 then v_closed:=v_closed+1; end if;

  select count(*) into v_stuck_jobs
  from public.quality_worker_jobs
  where status in ('queued','running') and updated_at < v_now - interval '15 minutes';
  v_change := private.gap_closure_sync_gap(
    'quality.worker.queue.stuck','automation','blocker','Quality worker queue has stale jobs',
    'Queued or running quality work has not progressed within the allowed lease window.',
    v_stuck_jobs > 0,true,
    jsonb_build_object('staleJobs',v_stuck_jobs,'thresholdMinutes',15),
    jsonb_build_object('action','lease-recovery-and-requeue','closeOnlyAfter','no stale queued/running jobs'),v_now);
  if v_change=1 then v_detected:=v_detected+1; elsif v_change=2 then v_detected:=v_detected+1; v_reopened:=v_reopened+1; elsif v_change=-1 then v_closed:=v_closed+1; end if;

  select count(*) into v_anon_definer
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where p.prosecdef and n.nspname='public' and has_function_privilege('anon',p.oid,'EXECUTE')
    and p.proname <> 'run_gap_closure_db_cycle';
  select count(*) into v_auth_definer
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where p.prosecdef and n.nspname='public' and has_function_privilege('authenticated',p.oid,'EXECUTE')
    and p.proname <> 'run_gap_closure_db_cycle';
  v_change := private.gap_closure_sync_gap(
    'supabase.security.security-definer-exposure','security','major','SECURITY DEFINER functions have exposed EXECUTE grants',
    'Privileged database functions callable by anon/authenticated roles require explicit review and least-privilege grants.',
    v_anon_definer > 0 or v_auth_definer > 0,false,
    jsonb_build_object('anonExecutable',v_anon_definer,'authenticatedExecutable',v_auth_definer),
    jsonb_build_object('action','review-and-revoke-unnecessary-execute','autoRevoke',false),v_now);
  if v_change=1 then v_detected:=v_detected+1; elsif v_change=2 then v_detected:=v_detected+1; v_reopened:=v_reopened+1; elsif v_change=-1 then v_closed:=v_closed+1; end if;

  if v_latest_telemetry is null or v_latest_telemetry < v_now - interval '20 minutes' then
    v_job_key := 'gap-runtime-telemetry-' || to_char(v_now,'YYYYMMDDHH24');
    insert into public.quality_worker_jobs(job_key,kind,priority,required_capabilities,payload,status,attempts,max_attempts,created_at,updated_at)
    select v_job_key,'runtime.telemetry.refresh',100,'[]'::jsonb,jsonb_build_object('gapKey','runtime.telemetry.stale'),'queued',0,3,v_now,v_now
    where not exists(select 1 from public.quality_worker_jobs where job_key=v_job_key);
    if found then v_queued := v_queued + 1; end if;
  end if;

  if v_profiles > 0 and v_manifests = 0 then
    v_job_key := 'gap-pixel-atlas-' || to_char(v_now,'YYYYMMDD');
    insert into public.quality_worker_jobs(job_key,kind,priority,required_capabilities,payload,status,attempts,max_attempts,created_at,updated_at)
    select v_job_key,'pixel.atlas.build',80,'[]'::jsonb,jsonb_build_object('gapKey','pixel.animation.atlas.missing'),'queued',0,3,v_now,v_now
    where not exists(select 1 from public.quality_worker_jobs where job_key=v_job_key);
    if found then v_queued := v_queued + 1; end if;
  end if;

  update public.gap_closure_runs
  set finished_at=v_now, detected=v_detected, reopened=v_reopened, closed=v_closed, queued=v_queued,
      result=jsonb_build_object(
        'latestTelemetryAt',v_latest_telemetry,
        'pixelProfiles',v_profiles,
        'pixelAtlasManifests',v_manifests,
        'deviceReports',v_device_reports,
        'staleWorkerJobs',v_stuck_jobs,
        'anonSecurityDefinerExecute',v_anon_definer,
        'authenticatedSecurityDefinerExecute',v_auth_definer)
  where id=v_run_id;

  return jsonb_build_object('ok',true,'runId',v_run_id,'detected',v_detected,'reopened',v_reopened,'closed',v_closed,'queued',v_queued);
end;
$$;
revoke all on function public.run_gap_closure_db_cycle(text) from public, anon, authenticated;
do $$ begin if exists (select 1 from pg_roles where rolname='service_role') then grant execute on function public.run_gap_closure_db_cycle(text) to service_role; end if; end $$;
