#!/usr/bin/env node
'use strict';const fs=require('fs'),path=require('path');const source=path.resolve(__dirname,'..'),repo=path.resolve(process.argv[2]||process.cwd());
function cpDir(name){const s=path.join(source,name),d=path.join(repo,name);if(!fs.existsSync(s))return;fs.mkdirSync(d,{recursive:true});for(const e of fs.readdirSync(s,{withFileTypes:true})){const a=path.join(s,e.name),b=path.join(d,e.name);if(e.isDirectory())fs.cpSync(a,b,{recursive:true,force:true});else fs.copyFileSync(a,b)}}
for(const d of ['shared','api','scripts','test','supabase'])cpDir(d);fs.mkdirSync(path.join(repo,'apps'),{recursive:true});
for(const app of ['procedural-quality-lab','procedural-quality-certification'])if(fs.existsSync(path.join(source,'apps',app)))fs.cpSync(path.join(source,'apps',app),path.join(repo,'apps',app),{recursive:true,force:true});
for(const f of ['DESKTOP_AI_PROCEDURAL_QUALITY.md','README.md','PROCEDURAL_MODEL_MANIFEST.json','SUPABASE_PROCEDURAL_QUALITY_STATUS.json'])if(fs.existsSync(path.join(source,f)))fs.copyFileSync(path.join(source,f),path.join(repo,f));
const pp=path.join(repo,'package.json'),pkg=JSON.parse(fs.readFileSync(pp,'utf8').replace(/^\uFEFF/,''));pkg.scripts=pkg.scripts||{};pkg.dependencies=pkg.dependencies||{};pkg.devDependencies=pkg.devDependencies||{};
pkg.dependencies['@mediapipe/tasks-vision']=pkg.dependencies['@mediapipe/tasks-vision']||'^1.0.1';pkg.devDependencies['pngjs']=pkg.devDependencies['pngjs']||'^7.0.0';
Object.assign(pkg.scripts,{
'procedural:vision:build':'node scripts/build-procedural-vision.js','procedural:models':'node scripts/fetch-procedural-models.js','procedural:models:verify':'node scripts/verify-procedural-models.js',
'procedural:inject':'node scripts/inject-procedural-quality-runtime.js','procedural:three-patch':'node scripts/procedural-quality-three-patcher.js','procedural:native-audit':'node scripts/procedural-quality-native-audit.js',
'procedural:readiness':'node scripts/procedural-quality-readiness.js','procedural:critic':'node scripts/procedural-quality-visual-critic.js','procedural:tournament':'node scripts/procedural-quality-tournament.js',
'procedural:device-matrix':'node scripts/procedural-quality-v7-device-matrix.js','procedural:device-certification':'node scripts/procedural-quality-device-certification.js',
'procedural:rollback-check':'node scripts/procedural-quality-rollback.js','procedural:golden:record':'node scripts/procedural-quality-golden-baselines.js','procedural:golden:verify':'node scripts/procedural-quality-golden-verify.js',
'procedural:evidence':'node scripts/procedural-quality-evidence-orchestrator.js','procedural:doctor':'node scripts/procedural-quality-doctor.js --fix','procedural:canary':'node scripts/procedural-quality-canary-gate.js',
'procedural:canary:production':'node scripts/procedural-quality-canary-gate.js --production','procedural:verify:prod':'node scripts/procedural-quality-production-verify.js','procedural:check':'node scripts/procedural-quality-v10-gate.js'});
if(!String(pkg.scripts.build||'').includes('inject-procedural-quality-runtime.js'))pkg.scripts.build=(String(pkg.scripts.build||'').trim()?pkg.scripts.build+' && ':'')+'node scripts/inject-procedural-quality-runtime.js';
let rg=String(pkg.scripts['release:gate']||'npm run check').replace(/^npm run procedural:check\s*&&\s*/,'');pkg.scripts['release:gate']='npm run procedural:check && '+rg;fs.writeFileSync(pp,JSON.stringify(pkg,null,2)+'\n');
const vp=path.join(repo,'vercel.json');if(fs.existsSync(vp)){const v=JSON.parse(fs.readFileSync(vp,'utf8').replace(/^\uFEFF/,'')),cmd=String(v.buildCommand||'').trim();if(!cmd.includes('inject-procedural-quality-runtime.js'))v.buildCommand=cmd?cmd+' && node scripts/inject-procedural-quality-runtime.js':'node scripts/inject-procedural-quality-runtime.js';fs.writeFileSync(vp,JSON.stringify(v,null,2)+'\n')}
const ci=path.join(repo,'.github/workflows/ci.yml');if(fs.existsSync(ci)){let y=fs.readFileSync(ci,'utf8');y=y.replace(/      - name: Procedural Quality V[4-9] gate \(hard\)\n        run: npm run procedural:check\n/g,'');if(!y.includes('Procedural Quality V10 gate')){const needle='      - run: npm run check',ins='      - name: Procedural Quality V10 gate (hard)\n        run: npm run procedural:check\n';if(y.includes(needle))y=y.replace(needle,ins+needle)}fs.writeFileSync(ci,y,'utf8')}
console.log('PROCEDURAL QUALITY V10 INSTALLED');
