#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),cp=require('child_process'),os=require('os');
const here=__dirname,manifest=JSON.parse(fs.readFileSync(path.join(here,'PATCH_MANIFEST.json'),'utf8'));
const args=process.argv.slice(2),repo=path.resolve(args.find(x=>!x.startsWith('--'))||process.cwd());const APPLY=args.includes('--apply'),ALL=args.includes('--phase=all')||args.includes('--all'),AONLY=args.includes('--phase=A');
function run(cmd,a,cwd=repo,allow=false){const r=cp.spawnSync(cmd,a,{cwd,stdio:'inherit',encoding:'utf8'});if(r.status!==0&&!allow)throw new Error(`${cmd} ${a.join(' ')} failed (${r.status})`);return r.status===0;}
function git(...a){return cp.spawnSync('git',a,{cwd:repo,encoding:'utf8'}).stdout?.trim()||'';}
function ensureRepo(){for(const f of ['package.json','shared','services/ai3d-worker'])if(!fs.existsSync(path.join(repo,f)))throw new Error('Not World_server root: missing '+f);}
function branch(){const dirty=git('status','--porcelain');if(dirty)throw new Error('Refusing dirty worktree. Commit/stash unrelated work first.');let b=git('branch','--show-current');if(['master','main'].includes(b)){b='ai/desktop/core-loop-graphics-integration-v1-'+Date.now();run('git',['checkout','-b',b]);}return b;}
function copy(rel){const s=path.join(here,'core',rel),d=path.join(repo,rel);fs.mkdirSync(path.dirname(d),{recursive:true});fs.copyFileSync(s,d);}
function patchPackage(){const f=path.join(repo,'package.json'),p=JSON.parse(fs.readFileSync(f,'utf8'));p.scripts=p.scripts||{};p.scripts['iw:graphics:audit']='node scripts/iw-graphics-audit.cjs . --write';p.scripts['iw:core-loop:test']='node --test test/answer-world-engine.test.cjs';fs.writeFileSync(f,JSON.stringify(p,null,2)+'\n');}
function extract(zip,dst){fs.rmSync(dst,{recursive:true,force:true});fs.mkdirSync(dst,{recursive:true});if(process.platform==='win32'){const esc=s=>s.replace(/'/g,"''");return run('powershell',['-NoProfile','-ExecutionPolicy','Bypass','-Command',`Expand-Archive -LiteralPath '${esc(zip)}' -DestinationPath '${esc(dst)}' -Force`],repo);}for(const py of ['python3','python']){const r=cp.spawnSync(py,['-m','zipfile','-e',zip,dst],{cwd:repo,stdio:'inherit'});if(r.status===0)return true;}return run('unzip',['-q',zip,'-d',dst],repo);}
function commandFor(m,stage){if(!m.install)return null;let root=m.stageRoot?path.join(stage,m.stageRoot):stage;let parts=m.install.map(x=>x.replace('{repo}',repo));let cmd=parts.shift();if(cmd==='python'){const pys=process.platform==='win32'?['python','py']:['python3','python'];for(const p of pys){if(cp.spawnSync(p,['--version'],{stdio:'ignore'}).status===0){cmd=p;break;}}}let cwd=(m.cwd||root).replace('{repo}',repo);parts=parts.map((x,i)=>i===0&&!path.isAbsolute(x)&&['node','python','python3','py'].includes(cmd)?path.join(root,x):x);return{cmd,parts,cwd};}
function audit(){const rows=manifest.modules.map(m=>{const found=(m.sentinels||[]).filter(r=>fs.existsSync(path.join(repo,r)));return{id:m.id,phase:m.phase||'-',status:found.length===(m.sentinels||[]).length&&found.length?'INSTALLED':found.length?'PARTIAL':'MISSING',found,sentinels:m.sentinels||[]};});console.log(JSON.stringify({repo,observedMasterSha:manifest.observedMasterSha,currentHead:git('rev-parse','HEAD'),rows},null,2));return rows;}
ensureRepo();if(!APPLY){audit();console.log('\nAudit only. Run with --apply --phase=all from a clean World_server worktree to install staged modules.');process.exit(0)}
const b=branch(),base=git('rev-parse','HEAD');console.log(`[IW] branch=${b} base=${base}`);
for(const rel of ['shared/world-graphics-bus.js','shared/answer-world-engine.js','shared/improve-world-graphics-bootstrap.js','data/answer-world-schema.json','data/graphics-integration-manifest.json','scripts/iw-graphics-audit.cjs','test/answer-world-engine.test.cjs'])copy(rel);patchPackage();run(process.execPath,['--test','test/answer-world-engine.test.cjs']);
const stages=path.join(repo,'.iw-graphics-staging');fs.mkdirSync(stages,{recursive:true});const before=audit();
for(const m of manifest.modules){if(!m.zip||!m.phase)continue;if(m.phase==='B'&&!ALL)continue;if(m.phase==='C'&&!ALL)continue;const row=before.find(x=>x.id===m.id);if(row?.status==='INSTALLED'){console.log(`[IW] skip installed ${m.id}`);continue;}const zip=path.join(here,'payloads',m.zip);if(!fs.existsSync(zip)){console.log(`[IW] payload missing ${m.zip}`);continue;}const stage=path.join(stages,m.id);extract(zip,stage);const c=commandFor(m,stage);if(!c){console.log(`[IW] staged ${m.id}; manual guarded install required: ${m.manualInstall||'see module instructions'}`);continue;}console.log(`[IW] install ${m.id}`);run(c.cmd,c.parts,c.cwd);console.log(`[IW] installed candidate ${m.id}; Desktop AI must run its own verification gate before proceeding/promotion.`);}
run(process.execPath,['scripts/iw-graphics-audit.cjs','.', '--write']);console.log('\n[IW] INSTALL STAGING COMPLETE. Do NOT claim production completion until module gates + npm run release:gate + real desktop/mobile browser verification pass.');
