begin;

create table if not exists private.quality_improvement_cycles (
  id bigint generated by default as identity primary key,
  run_id text not null unique,
  project_id text not null,
  mode text not null check (mode in ('observe','candidate','autopilot')),
  focus_lane text not null check (focus_lane in ('automation','graphics','animation','code','mixed')),
  status text not null,
  baseline jsonb not null default '{}'::jsonb,
  candidate jsonb not null default '{}'::jsonb,
  decision jsonb not null default '{}'::jsonb,
  protected_gate jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists quality_improvement_cycles_project_created_idx
  on private.quality_improvement_cycles (project_id, created_at desc);

create table if not exists private.quality_optimizer_memory (
  id bigint generated by default as identity primary key,
  fingerprint text not null unique,
  project_id text not null,
  lane text not null check (lane in ('automation','graphics','animation','code','mixed')),
  issue_key text not null,
  outcome text not null check (outcome in ('unknown','rejected','accepted','golden')),
  attempts integer not null default 0 check (attempts >= 0),
  score_delta double precision not null default 0,
  last_reason text,
  metadata jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create index if not exists quality_optimizer_memory_project_lane_idx
  on private.quality_optimizer_memory (project_id, lane, outcome, last_seen_at desc);

revoke all on table private.quality_improvement_cycles from public, anon, authenticated;
revoke all on table private.quality_optimizer_memory from public, anon, authenticated;
revoke all on sequence private.quality_improvement_cycles_id_seq from public, anon, authenticated;
revoke all on sequence private.quality_optimizer_memory_id_seq from public, anon, authenticated;

alter table private.quality_improvement_cycles enable row level security;
alter table private.quality_optimizer_memory enable row level security;

commit;
