#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process');
const PATCH=__dirname,PAYLOAD=path.join(PATCH,'payload');
const args=process.argv.slice(2),has=x=>args.includes(x);function argValue(name){const i=args.indexOf(name);return i>=0?args[i+1]:null}
function isRepo(p){return p&&fs.existsSync(path.join(p,'package.json'))&&fs.existsSync(path.join(p,'apps'))&&fs.existsSync(path.join(p,'AGENTS.md'))}
function findRepo(){const explicit=argValue('--repo')||process.env.WORLD_SERVER_ROOT;if(explicit&&isRepo(path.resolve(explicit)))return path.resolve(explicit);for(const c of[process.cwd(),path.dirname(PATCH),path.join(path.dirname(PATCH),'World_server'),path.join(os.homedir(),'Desktop','World_server')])if(isRepo(c))return path.resolve(c);throw new Error('World_server repository not found. Run inside the repo or pass --repo <path>.')}
const ROOT=findRepo();
function run(cmd,a=[],opts={}){return cp.execFileSync(cmd,a,{cwd:ROOT,encoding:'utf8',stdio:opts.capture?['ignore','pipe','pipe']:'inherit',...opts})}
function git(...a){return run('git',a,{capture:true}).trim()}
function write(p,s){const f=path.join(ROOT,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,s,'utf8')}
function read(p){return fs.readFileSync(path.join(ROOT,p),'utf8')}
function copyPayload(){function walk(dir,rel=''){for(const ent of fs.readdirSync(dir,{withFileTypes:true})){if(ent.name==='__pycache__')continue;const src=path.join(dir,ent.name),r=path.join(rel,ent.name).replace(/\\/g,'/');if(ent.isDirectory())walk(src,r);else write(r,fs.readFileSync(src,'utf8'))}}walk(PAYLOAD)}
function injectBefore(text,needle,insert,label){if(text.includes(insert.trim()))return text;if(!text.includes(needle))throw new Error(`Patch anchor not found: ${label}`);return text.replace(needle,insert+needle)}
function replaceOnce(text,needle,repl,label){if(text.includes(repl.trim()))return text;if(!text.includes(needle))throw new Error(`Patch anchor not found: ${label}`);return text.replace(needle,repl)}
function ensureBranch(){let branch='';try{branch=git('branch','--show-current')}catch(e){if(!has('--no-branch'))throw new Error('Git repository/branch check failed: '+(e.message||e));return}const dirty=git('status','--porcelain');if(dirty&&!has('--allow-dirty'))throw new Error('Working tree is not clean. Save/commit existing changes before installing.');if(branch==='master'||branch==='main'){const target=argValue('--branch-name')||'ai/desktop/world-quality-autopilot-v6';try{run('git',['checkout','-b',target])}catch{run('git',['checkout',target])}branch=target}if((branch==='master'||branch==='main')&&!has('--no-branch'))throw new Error('Refusing to modify master/main.')}
function archiveAndWriteWip(stage,evidence='Pending verification'){const existing=fs.existsSync(path.join(ROOT,'WORK_IN_PROGRESS.md'))?read('WORK_IN_PROGRESS.md'):'';if(existing&&!fs.existsSync(path.join(ROOT,'docs','wip-history','WORLD_SERVER_PRE_WORLD_QUALITY_AUTOPILOT_V6.md')))write('docs/wip-history/WORLD_SERVER_PRE_WORLD_QUALITY_AUTOPILOT_V6.md',existing);const pct=stage==='verified'?99:stage==='failed'?70:45;write('WORK_IN_PROGRESS.md',`# WORK IN PROGRESS — WORLD_QUALITY_AUTOPILOT_V6\n\n## Task\nInstall V6 of the non-destructive World Quality Autopilot: importance-budgeted semantic voxel detail, multiview visual proof, semantic texture bake contracts, streaming topology, shader-cost auditing, deterministic replay, animation LOD, quality SLO/error budgets, causality guard, canary release planning and regression-safe evolution.\n\n## Why\nGeneric Golden/Quality automation already exists. V6 adds the technology-aware world-specific closed loop that decides where detail matters, adds it only behind the reference-facing shell, classifies material intent, adapts rendering/animation to runtime pressure and records machine-readable evidence.\n\n## Current state\n- Existing release, Golden, regression, risk/cost, visual critic, patch tournament and device-gate systems must be preserved.\n- Graphics Technology Scout must run first on every cycle and compare the actual repository/runtime technologies with the adapter registry.\n- Every runtime graphics technology must have BOTH detail and optimization adapters; unknown graphics packages block release until reviewed.\n- CPU-first/free-local optimization is preferred; GPU routes stay optional.\n- V6 includes V5 semantic detail indexing and adds mandatory graphics-technology scouting, detail+optimization adapters, CPU-first routing, technology drift detection and evidence provenance. V6 also preserves, deterministic PBR candidate synthesis, texture/sector visibility budgets, sustained-pressure thermal proxy, retarget/root-motion/two-hand contracts, importance budgets, multiview visual gate, streaming topology/prefetch, shader-cost audit, animation LOD, deterministic input/state replay, quality SLO/error budgets, causality guard, canary release plan, feedback learner, candidate lab, baseline promotion guard and evidence ledger.\n\n## Target state\n- Reference-facing projection remains byte-equivalent while hidden/side volume gains deterministic detail.\n- AI3D worker and Vercel fallback use the same V6 policy.\n- 3D/orbit/playable views can use adaptive PBR, while Front Exact remains unmodified.\n- Runtime adapts DPR/LOD/shadows/particles/lights/animation/material/geometry budgets using FPS, frame p95, GPU time, long tasks, memory and device capability.\n- New visual baselines can never self-approve.
- Promotion is blocked by deterministic replay/SLO/causality evidence and must pass staged canary evidence when a deployment provider is configured.\n\n## Files / systems involved\n- api/ai3d-voxel-generate.js\n- lib/world-quality-voxel-enhancer.js\n- lib/world-quality-semantic-detail.js\n- lib/world-quality-material-profiler.js\n- services/ai3d-worker/ai3d/runner.py\n- services/ai3d-worker/ai3d/plugins/world_quality.py\n- shared/world-quality-autopilot.js\n- apps/ai3d-voxel-city/*\n- apps/voxel-world/*\n- data/world-quality-autopilot.json\n- scripts/world-*.js\n- .github/workflows/world-quality-autopilot.yml\n- package.json\n\n## Golden systems that must be preserved\n- Approved graphics/assets and Golden components.\n- Canonical desktop/mobile controls, collisions, grounding and step-up.\n- AI3D front-reference fidelity and Final Delivery gates.\n- Deny-by-default release policy.\n\n## Exact patch plan\n1. Work only in a new AI branch and update this WIP before project edits.\n2. Install semantic server/worker detail enhancement with hard front-projection invariant and voxel budget.\n3. Install material profiler and adaptive PBR hooks without changing Front Exact.\n4. Install frame/GPU/long-task/device-aware runtime budgets and animation semantic rules.\n5. Install baseline candidates + explicit promotion guard, device matrix and evidence ledger.\n6. Run targeted tests, quality:world and full release gate.\n7. Reject/rollback any candidate that regresses controls, collisions, mobile behavior, visuals or performance.\n\n## Known risks\n- Aesthetic 100% still requires approved screenshots.\n- Animation 100% still requires real rig playback evidence.\n- Optimization 100% still requires physical iOS/Android evidence.\n- GitHub/Vercel winner-only writes and staged canary traffic require external credentials/provider access.
- Semantic texture baker contract is installed, but destructive texture baking still requires an actual baker/runtime and explicit evidence.\n\n## Current progress\n- ${pct}% — ${stage}.\n\n## Next action\n${stage==='verified'?'Inspect git diff/status; run full release gate if not already run; commit/push AI branch; open PR; verify Vercel preview on desktop + mobile; do not auto-merge.':'Fix the failing gate. Do not commit/deploy a failed installation.'}\n\n## Completion criteria\n- Targeted V6 tests PASS.\n- quality:world produces readiness >= 85 with no hard gate failure.\n- release:gate PASS before PR merge/deploy.\n- Front Exact projection unchanged.\n- Desktop/mobile controls and collisions remain protected.\n- New evidence ledger generated.\n- Desktop AI must not stop while any reproducible required-gate error remains. Fix, rerun, and repeat until all required gates pass. External blockers must be documented explicitly and completion must not be claimed.\n\n## Final evidence\n${evidence}\n`)}
function patchPackage(){const p=path.join(ROOT,'package.json'),j=JSON.parse(fs.readFileSync(p,'utf8'));j.scripts=j.scripts||{};Object.assign(j.scripts,{
 'quality:world:tech-scout':'node scripts/world-graphics-technology-scout.js','quality:world:tech-candidates':'node scripts/world-technology-candidate-intake.js','quality:world:runtime-resilience':'node scripts/world-runtime-dependency-resilience.js','quality:world:tech-integrate':'node scripts/world-graphics-technology-integrator.js','quality:world:tech-drift':'node scripts/world-technology-drift-gate.js','quality:world:tech-accept':'node scripts/world-technology-drift-gate.js --accept-current','quality:world:cpu':'node scripts/world-cpu-first-graphics-optimizer.js','quality:world:evidence-provenance':'node scripts/world-evidence-provenance-guard.js','quality:world:tech-route':'node scripts/world-graphics-quality-router.js',
 'quality:world:analyze':'node scripts/world-quality-analyzer.js','quality:world:animation':'node scripts/world-animation-semantic-validator.js','quality:world:animation-lod':'node scripts/world-animation-lod-controller.js','quality:world:retarget':'node scripts/world-retarget-contract.js','quality:world:runtime':'node scripts/world-runtime-quality-profiler.js','quality:world:baselines':'node scripts/world-visual-baseline-candidates.js','quality:world:multiview':'node scripts/world-multiview-visual-gate.js','quality:world:baseline:promote':'node scripts/world-visual-baseline-promote.js','quality:world:semantic':'node scripts/world-semantic-detail-indexer.js','quality:world:materials':'node scripts/world-material-synthesis.js','quality:world:shader-cost':'node scripts/world-shader-cost-auditor.js','quality:world:visibility':'node scripts/world-visibility-optimizer.js','quality:world:streaming':'node scripts/world-streaming-topology.js','quality:world:devices':'node scripts/world-device-profile-matrix.js','quality:world:replay':'node scripts/world-deterministic-replay.js','quality:world:slo':'node scripts/world-quality-slo.js','quality:world:causality':'node scripts/world-quality-causality.js','quality:world:canary':'node scripts/world-canary-release.js','quality:world:scheduler':'node scripts/world-quality-scheduler.js','quality:world:feedback':'node scripts/world-feedback-learner.js','quality:world:candidates':'node scripts/world-candidate-lab.js','quality:world:evidence':'node scripts/world-quality-evidence-ledger.js','quality:world':'node scripts/world-quality-autopilot.js','quality:world:full':'node scripts/world-quality-autopilot.js --full','quality:world:evolve':'node scripts/world-quality-autopilot.js --evolve'});if(j.scripts['release:gate']&&!j.scripts['release:gate'].includes('quality:world'))j.scripts['release:gate']+=' && npm run quality:world';fs.writeFileSync(p,JSON.stringify(j,null,2)+'\n')}
function patchApi(){let s=read('api/ai3d-voxel-generate.js');if(!s.includes("require('../lib/world-quality-voxel-enhancer')"))s=injectBefore(s,'const MAX_INPUT_BYTES = 58 * 1024;',"const { enhanceVoxelWorld } = require('../lib/world-quality-voxel-enhancer');\n\n",'api enhancer require');if(!s.includes('enhanceVoxelWorld(generateWorld(body)'))s=replaceOnce(s,'  const world=generateWorld(body);\n',"  const world=enhanceVoxelWorld(generateWorld(body),{rootDir:process.cwd(),enabled:body.qualityAutopilot!==false,seed:Number(body.qualitySeed)||undefined});\n",'api enhancer call');write('api/ai3d-voxel-generate.js',s)}
function patchRunner(){let s=read('services/ai3d-worker/ai3d/runner.py');if(!s.includes('from .plugins.world_quality import WorldQualityEnhancer'))s=injectBefore(s,'from ai3d_voxel_verifier.verifier import verify_voxel_city\n','from .plugins.world_quality import WorldQualityEnhancer\n','runner enhancer import');if(!s.includes('self.world_quality = WorldQualityEnhancer()'))s=replaceOnce(s,'        self.mesh_optimizer = MeshQualityOptimizer()\n','        self.mesh_optimizer = MeshQualityOptimizer()\n        self.world_quality = WorldQualityEnhancer()\n','runner enhancer init');if(!s.includes('world_quality.enhance_voxel_world')){const re=/(^[ \t]*)files\.append\(file_meta\(world_path, ["']voxel_world["']\)\)/m,m=s.match(re);if(!m)throw new Error('Patch anchor not found: runner enhancer call');s=s.replace(re,`${m[1]}world_path = self.world_quality.enhance_voxel_world(world_path, voxel_params)\n$&`)}write('services/ai3d-worker/ai3d/runner.py',s)}
function patchIndexes(){for(const p of['apps/ai3d-voxel-city/index.html','apps/voxel-world/index.html']){let s=read(p);if(!s.includes('/shared/world-quality-autopilot.js'))s=injectBefore(s,'</body>','<script src="/shared/world-quality-autopilot.js"></script>\n',`${p} runtime script`);write(p,s)}}
function patchAi3dClient(){let s=read('apps/ai3d-voxel-city/client.js');const marker='  host.replaceChildren(renderer.domElement);\n';if(!s.includes("registerRenderer('ai3d-voxel-city'")){const block=marker+`  window.WorldQualityAutopilot?.registerRenderer('ai3d-voxel-city',renderer,{\n    initialTier:matchMedia('(pointer:coarse)').matches?'BALANCED':'HIGH',targetFps:matchMedia('(pointer:coarse)').matches?43:55,\n    onQualityChange(q){if(!adaptive)return;profileName=q.tier==='SAFE'?'SAFE':q.tier==='ULTRA'?'ULTRA':'HIGH';dynamicPixelRatio=Math.min(devicePixelRatio||1,Number(q.dpr)||profile().pixelRatio);renderer.setPixelRatio(dynamicPixelRatio);renderer.setSize(host.clientWidth,host.clientHeight,false);if(typeof setWorldMaterialQuality==='function')setWorldMaterialQuality(q.pbrQuality||0);if(world){applyFog();updateStreaming(true)}},\n    getStats(){return{fps:measuredFps,calls:renderer.info.render.calls,triangles:renderer.info.render.triangles}}\n  });\n`;s=replaceOnce(s,marker,block,'ai3d runtime registration')}
 if(!s.includes('function setWorldMaterialQuality(')){
  const matMarker="  const detailMatTemplate={vertexColors:true,side:THREE.FrontSide};\n";
  const matBlock=matMarker+`  let requestedWorldMaterialQuality=0;\n  function makeWorldDetailMaterial(){return(!frontMode&&requestedWorldMaterialQuality>0)?new THREE.MeshStandardMaterial({vertexColors:true,side:THREE.FrontSide,roughness:requestedWorldMaterialQuality>1?.72:.82,metalness:.05}):new THREE.MeshBasicMaterial(detailMatTemplate)}\n  function applyWorldMaterialMode(){for(const o of chunkObjects.values()){const old=o.detail.material;o.detail.material=makeWorldDetailMaterial();old?.dispose?.()}}\n  function setWorldMaterialQuality(q){requestedWorldMaterialQuality=Math.max(0,Math.min(2,Number(q)||0));applyWorldMaterialMode()}\n`;
  s=replaceOnce(s,matMarker,matBlock,'ai3d material functions');
  s=s.replace("    const detail=new THREE.Mesh(buildGeometry(c),new THREE.MeshBasicMaterial(detailMatTemplate));","    const detail=new THREE.Mesh(buildGeometry(c),makeWorldDetailMaterial());");
  s=s.replace("  g.computeBoundingBox();g.computeBoundingSphere();","  g.computeBoundingBox();g.computeBoundingSphere();g.computeVertexNormals();");
  s=s.replace("  frontMode=true;activeCamera=ortho;scene.fog=null;","  frontMode=true;activeCamera=ortho;scene.fog=null;applyWorldMaterialMode();");
  s=s.replace("  frontMode=false;activeCamera=persp;$('viewMode').textContent='3D ORBIT · STREAMED LOD';","  frontMode=false;activeCamera=persp;applyWorldMaterialMode();$('viewMode').textContent='3D ORBIT · STREAMED LOD';");
  s=s.replace("  frontMode=false; playableMode=true; activeCamera=persp;","  frontMode=false; playableMode=true; activeCamera=persp; applyWorldMaterialMode();");
  if(s.includes("const host=$('viewer');scene=new THREE.Scene();")&&!s.includes('worldQualityHemi'))s=s.replace("const host=$('viewer');scene=new THREE.Scene();","const host=$('viewer');scene=new THREE.Scene();const worldQualityHemi=new THREE.HemisphereLight(0xc9b2d6,0x241d22,.95);scene.add(worldQualityHemi);const worldQualitySun=new THREE.DirectionalLight(0xffc28a,1.15);worldQualitySun.position.set(-80,90,120);scene.add(worldQualitySun);");
 }
 write('apps/ai3d-voxel-city/client.js',s)}
function patchVoxelClient(){let s=read('apps/voxel-world/client.js');if(!s.includes("registerRenderer('voxel-world'")){const marker='const hemi=new THREE.HemisphereLight(0xbfe1ff,0x31412c,1.15); scene.add(hemi);\n',block=marker+`window.WorldQualityAutopilot?.registerRenderer('voxel-world',renderer,{initialTier:matchMedia('(pointer:coarse)').matches?'BALANCED':'HIGH',targetFps:matchMedia('(pointer:coarse)').matches?40:55,onQualityChange(q){renderer.shadowMap.enabled=q.shadowQuality>0;const shadowSize=q.shadowQuality>1?1024:512;if(sun?.shadow?.mapSize){sun.shadow.mapSize.set(shadowSize,shadowSize);sun.shadow.needsUpdate=true}},getStats(){return{calls:renderer.info.render.calls,triangles:renderer.info.render.triangles}}});\n`;s=replaceOnce(s,marker,block,'voxel-world runtime registration')}write('apps/voxel-world/client.js',s)}
function validatePayloadSyntax(){for(const p of['lib/world-quality-voxel-enhancer.js','lib/world-quality-semantic-detail.js','lib/world-quality-material-profiler.js','lib/world-quality-pbr-synthesizer.js','lib/world-quality-detail-budget.js','lib/world-quality-texture-baker-contract.js','shared/world-quality-autopilot.js','scripts/world-animation-semantic-validator.js','scripts/world-animation-lod-controller.js','scripts/world-retarget-contract.js','scripts/world-runtime-quality-profiler.js','scripts/world-visual-baseline-candidates.js','scripts/world-multiview-visual-gate.js','scripts/world-visual-baseline-promote.js','scripts/world-semantic-detail-indexer.js','scripts/world-material-synthesis.js','scripts/world-shader-cost-auditor.js','scripts/world-device-profile-matrix.js','scripts/world-visibility-optimizer.js','scripts/world-streaming-topology.js','scripts/world-deterministic-replay.js','scripts/world-quality-slo.js','scripts/world-quality-causality.js','scripts/world-canary-release.js','scripts/world-quality-scheduler.js','scripts/world-feedback-learner.js','scripts/world-candidate-lab.js','scripts/world-quality-evidence-ledger.js','scripts/world-graphics-technology-scout.js','scripts/world-technology-candidate-intake.js','scripts/world-runtime-dependency-resilience.js','scripts/world-graphics-technology-integrator.js','scripts/world-technology-drift-gate.js','scripts/world-cpu-first-graphics-optimizer.js','scripts/world-evidence-provenance-guard.js','scripts/world-graphics-quality-router.js','scripts/world-quality-analyzer.js','scripts/world-detail-planner.js','scripts/world-quality-autopilot.js'])run(process.execPath,['--check',path.join(ROOT,p)]);try{run('python',['-m','py_compile',path.join(ROOT,'services/ai3d-worker/ai3d/plugins/world_quality.py')])}catch{try{run('py',['-3','-m','py_compile',path.join(ROOT,'services/ai3d-worker/ai3d/plugins/world_quality.py')])}catch{console.warn('[WORLD_QUALITY_AUTOPILOT] Python syntax check skipped: Python not available')}}}
function runNpm(args){if(process.platform==='win32')return run(process.env.ComSpec||'cmd.exe',['/d','/s','/c','npm',...args]);return run('npm',args)}
function verify(full){run(process.execPath,['--test',path.join(ROOT,'test','world-quality-autopilot.test.js')]);run(process.execPath,[path.join(ROOT,'scripts','world-quality-autopilot.js')]);run(process.execPath,[path.join(ROOT,'scripts','world-technology-drift-gate.js'),'--accept-current']);run(process.execPath,[path.join(ROOT,'scripts','world-graphics-technology-scout.js')]);run(process.execPath,[path.join(ROOT,'scripts','world-technology-candidate-intake.js')]);run(process.execPath,[path.join(ROOT,'scripts','world-runtime-dependency-resilience.js')]);run(process.execPath,[path.join(ROOT,'scripts','world-graphics-technology-integrator.js')]);run(process.execPath,[path.join(ROOT,'scripts','world-technology-drift-gate.js')]);if(full)runNpm(['run','release:gate'])}
const CORE_TARGETS=['package.json','api/ai3d-voxel-generate.js','services/ai3d-worker/ai3d/runner.py','apps/ai3d-voxel-city/index.html','apps/ai3d-voxel-city/client.js','apps/voxel-world/index.html','apps/voxel-world/client.js'];
function payloadPaths(){const out=[];function walk(dir,rel=''){for(const ent of fs.readdirSync(dir,{withFileTypes:true})){if(ent.name==='__pycache__')continue;const src=path.join(dir,ent.name),r=path.join(rel,ent.name).replace(/\\/g,'/');if(ent.isDirectory())walk(src,r);else out.push(r)}}walk(PAYLOAD);return out}
function validateAnchors(){for(const p of CORE_TARGETS)if(!fs.existsSync(path.join(ROOT,p)))throw new Error(`Required file missing: ${p}`);const api=read('api/ai3d-voxel-generate.js');if(!api.includes('enhanceVoxelWorld')&&(!api.includes('const MAX_INPUT_BYTES = 58 * 1024;')||!api.includes('const world=generateWorld(body);')))throw new Error('API patch anchors incompatible.');const runner=read('services/ai3d-worker/ai3d/runner.py');if(!runner.includes('world_quality.enhance_voxel_world')&&(!runner.includes('from ai3d_voxel_verifier.verifier import verify_voxel_city')||!runner.includes('self.mesh_optimizer = MeshQualityOptimizer()')||!/[ \t]*files\.append\(file_meta\(world_path, ["']voxel_world["']\)\)/.test(runner)))throw new Error('Python runner anchors incompatible.');const a=read('apps/ai3d-voxel-city/client.js');if(!a.includes("registerRenderer('ai3d-voxel-city'")&&!a.includes('host.replaceChildren(renderer.domElement);'))throw new Error('AI3D client runtime anchor incompatible.');const v=read('apps/voxel-world/client.js');if(!v.includes("registerRenderer('voxel-world'")&&!v.includes('const hemi=new THREE.HemisphereLight(0xbfe1ff,0x31412c,1.15); scene.add(hemi);'))throw new Error('Voxel World runtime anchor incompatible.')}
const REPORTS=['WORLD_QUALITY_AUTOPILOT_REPORT.json','WORLD_QUALITY_AUTOPILOT_PLAN.json','WORLD_QUALITY_AUTOPILOT_STATUS.json','WORLD_ANIMATION_SEMANTIC_REPORT.json','WORLD_RUNTIME_QUALITY_REPORT.json','WORLD_VISUAL_BASELINE_CANDIDATES.json','WORLD_SEMANTIC_DETAIL_REPORT.json','WORLD_DEVICE_PROFILE_MATRIX.json','WORLD_QUALITY_EVIDENCE_LEDGER.json','WORLD_MATERIAL_SYNTHESIS_REPORT.json','WORLD_VISIBILITY_OPTIMIZER_REPORT.json','WORLD_RETARGET_CONTRACT_REPORT.json','WORLD_QUALITY_SCHEDULER_REPORT.json','WORLD_FEEDBACK_LEARNER_REPORT.json','WORLD_CANDIDATE_LAB_REPORT.json','WORLD_MULTIVIEW_VISUAL_GATE_REPORT.json','WORLD_SHADER_COST_REPORT.json','WORLD_STREAMING_TOPOLOGY_REPORT.json','WORLD_ANIMATION_LOD_REPORT.json','WORLD_DETERMINISTIC_REPLAY_REPORT.json','WORLD_QUALITY_SLO_REPORT.json','WORLD_QUALITY_CAUSALITY_REPORT.json','WORLD_CANARY_RELEASE_REPORT.json','WORLD_GRAPHICS_TECHNOLOGY_REPORT.json','WORLD_GRAPHICS_TECHNOLOGY_INTEGRATION_REPORT.json','WORLD_GRAPHICS_TECHNOLOGY_DRIFT_REPORT.json','WORLD_CPU_GRAPHICS_OPTIMIZATION_REPORT.json','WORLD_EVIDENCE_PROVENANCE_REPORT.json','WORLD_GRAPHICS_QUALITY_ROUTING_REPORT.json'];
function snapshot(){const map=new Map();for(const rel of[...CORE_TARGETS,...payloadPaths(),...REPORTS]){const f=path.join(ROOT,rel);map.set(rel,fs.existsSync(f)?fs.readFileSync(f):null)}return map}
function rollback(map){for(const[rel,buf]of map){const f=path.join(ROOT,rel);if(buf===null){try{fs.rmSync(f,{force:true,recursive:false})}catch{}}else{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,buf)}}}
console.log('[WORLD_QUALITY_AUTOPILOT_V6] repo:',ROOT);if(!has('--no-branch'))ensureBranch();validateAnchors();const before=snapshot();archiveAndWriteWip('installing');
try{copyPayload();patchPackage();patchApi();patchRunner();patchIndexes();patchAi3dClient();patchVoxelClient();validatePayloadSyntax();verify(has('--verify-full'));const status=JSON.parse(read('WORLD_QUALITY_AUTOPILOT_STATUS.json'));archiveAndWriteWip('verified',`- V6 targeted tests: PASS.\n- Structural readiness: ${status.readinessPercent}%.\n- Domain readiness: ${JSON.stringify(status.domainPercent)}.\n- Evidence ledger: ${status.evidenceLedgerSha256||'generated'}.\n- Graphics technology connectivity: ${status.technologyConnectivityPercent??'report-generated'}%.\n- Production external-proof coverage: ${status.productionProofPercent??'report-generated'}% (synthetic/emulated evidence does not count as real proof).\n- Full release gate: ${has('--verify-full')?'PASS':'not run by installer; MUST run before PR merge/deploy'}.\n- GitHub push/PR and Vercel preview: pending Desktop AI / CI.`);console.log(`\n[WORLD_QUALITY_AUTOPILOT_V6] INSTALLED. Structural readiness: ${status.readinessPercent}%`);console.log('[WORLD_QUALITY_AUTOPILOT_V6] Next: git diff/status -> full release gate -> commit/push AI branch -> PR -> Vercel desktop/mobile evidence.')}catch(e){rollback(before);archiveAndWriteWip('failed',`- Installer/verification failed and project-file changes were rolled back: ${String(e&&e.message||e).replace(/\n/g,' ')}\n- Do not commit or deploy until fixed.`);throw e}
