create table if not exists public.quality_promotion_attestations_v10 (
  id bigint generated by default as identity primary key,
  chain_id text not null,
  sequence_no integer not null check (sequence_no >= 0),
  record_hash text not null unique,
  previous_hash text,
  commit_sha text not null default '',
  deployment_id text not null default '',
  evidence_hash text not null default '',
  decision text not null check (decision in ('PASS','HOLD','ROLLBACK','REJECT')),
  signature text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(chain_id, sequence_no)
);

create index if not exists quality_promotion_attestations_v10_chain_idx
  on public.quality_promotion_attestations_v10(chain_id, sequence_no desc);

alter table public.quality_promotion_attestations_v10 enable row level security;
revoke all on table public.quality_promotion_attestations_v10 from anon, authenticated;
grant select, insert, update, delete on table public.quality_promotion_attestations_v10 to service_role;

drop policy if exists quality_promotion_attestations_v10_service on public.quality_promotion_attestations_v10;
create policy quality_promotion_attestations_v10_service
on public.quality_promotion_attestations_v10
for all to service_role
using (true)
with check (true);

create table if not exists public.quality_restore_drills_v10 (
  id bigint generated by default as identity primary key,
  project_id text not null,
  scope text not null,
  backup_ref text,
  snapshot_hash text not null,
  restore_hash text not null,
  ok boolean not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists quality_restore_drills_v10_project_idx
  on public.quality_restore_drills_v10(project_id, created_at desc);

alter table public.quality_restore_drills_v10 enable row level security;
revoke all on table public.quality_restore_drills_v10 from anon, authenticated;
grant select, insert, update, delete on table public.quality_restore_drills_v10 to service_role;

drop policy if exists quality_restore_drills_v10_service on public.quality_restore_drills_v10;
create policy quality_restore_drills_v10_service
on public.quality_restore_drills_v10
for all to service_role
using (true)
with check (true);
