begin;
create table if not exists private.quality_autopilot_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  mode text not null,
  status text not null,
  summary jsonb not null default '{}'::jsonb,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists private.quality_regression_kb (
  rule_id text primary key,
  signature text not null,
  rule jsonb not null,
  confidence double precision not null default 0,
  blocked_regressions integer not null default 0,
  updated_at timestamptz not null default now()
);
create table if not exists private.quality_canary_decisions (
  id bigint generated by default as identity primary key,
  project_id text not null,
  release_id text not null,
  stage_percent integer not null check(stage_percent in (1,5,20,50,100)),
  decision text not null check(decision in ('hold','advance','rollback','complete')),
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists quality_canary_release_created_idx on private.quality_canary_decisions(project_id,release_id,created_at desc);
revoke all on schema private from anon, authenticated;
revoke all on all tables in schema private from anon, authenticated;
commit;
