import * as THREE from 'https://unpkg.com/three@0.165.0/build/three.module.js';

const $=id=>document.getElementById(id);
const ui={stage:$('stage'),status:$('status'),manifestInput:$('manifestInput'),loadBtn:$('loadBtn'),playBtn:$('playBtn'),fullscreenBtn:$('fullscreenBtn'),fpsRange:$('fpsRange'),fpsValue:$('fpsValue'),qualitySelect:$('qualitySelect'),gyroBtn:$('gyroBtn'),editorLink:$('editorLink'),registryList:$('registryList'),refreshRegistryBtn:$('refreshRegistryBtn'),hotspots:$('hotspots'),factoryFile:$('factoryFile'),factorySlug:$('factorySlug'),factoryTitle:$('factoryTitle'),factoryFps:$('factoryFps'),factoryPublish:$('factoryPublish'),factoryBuild:$('factoryBuild'),factoryBar:$('factoryBar'),factoryState:$('factoryState'),factoryFiles:$('factoryFiles')};
const S={renderer:null,scene:null,camera:null,sphere:null,material:null,texture:null,canvas:document.createElement('canvas'),ctx:null,manifest:null,yaw:0,pitch:0,fov:75,playing:true,fps:8,frameIndex:0,acc:0,quality:'auto',baseTier:'mobile',targetLevel:null,baseCache:new Map(),tileCache:new Map(),tileUse:new Map(),tileLimit:120,pointers:new Map(),dragId:null,lastDist:0,gyro:false,hotspots:[],session:null,poll:null,renderToken:0};S.ctx=S.canvas.getContext('2d',{alpha:false});
function status(t){ui.status.textContent=t}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function mobile(){return matchMedia('(pointer:coarse)').matches||innerWidth<900}function pad(n){return String(n).padStart(6,'0')}function esc(s=''){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function init(){S.renderer=new THREE.WebGLRenderer({canvas:ui.stage,antialias:false,powerPreference:'high-performance'});
  globalThis.WorldProceduralThreeNative?.attach?.(renderer, THREE);
  if(typeof world!=='undefined'&&typeof activeCamera!=='undefined')globalThis.WorldProceduralVoxelDDGI?.attach?.({renderer:renderer,worldGetter:()=>world,cameraGetter:()=>activeCamera});S.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));S.scene=new THREE.Scene();S.camera=new THREE.PerspectiveCamera(S.fov,innerWidth/innerHeight,.1,2000);const g=new THREE.SphereGeometry(500,64,40);g.scale(-1,1,1);S.texture=new THREE.CanvasTexture(S.canvas);S.texture.colorSpace=THREE.SRGBColorSpace;S.texture.generateMipmaps=false;S.texture.magFilter=THREE.NearestFilter;S.texture.minFilter=THREE.NearestFilter;S.material=new THREE.MeshBasicMaterial({map:S.texture,side:THREE.BackSide});S.sphere=new THREE.Mesh(g,S.material);S.scene.add(S.sphere);resize()}
function resize(){S.camera.aspect=innerWidth/innerHeight;S.camera.fov=S.fov;S.camera.updateProjectionMatrix();S.renderer.setSize(innerWidth,innerHeight,false)}
function chooseLevel(){const levels=S.manifest?.multires?.levels||[];if(!levels.length)return null;let wanted=mobile()?1024:2048;if(S.quality==='mobile')wanted=1024;else if(S.quality==='desktop')wanted=2048;else if(S.quality==='hq')wanted=levels.at(-1).width;else if(!mobile()&&innerWidth>1500)wanted=4096;return levels.reduce((best,l)=>Math.abs(l.width-wanted)<Math.abs(best.width-wanted)?l:best,levels[0])}
function baseTier(){if(S.manifest?.mobile)return'mobile';if(S.manifest?.desktop)return'desktop';return'hq'}
async function image(url){if(S.baseCache.has(url))return S.baseCache.get(url);const p=new Promise((resolve,reject)=>{const im=new Image();im.decoding='async';im.onload=()=>resolve(im);im.onerror=()=>reject(new Error(`image failed ${url}`));im.src=url});S.baseCache.set(url,p);return p}
function trimTiles(){if(S.tileCache.size<=S.tileLimit)return;const keys=[...S.tileUse.entries()].sort((a,b)=>a[1]-b[1]).slice(0,S.tileCache.size-S.tileLimit).map(x=>x[0]);for(const k of keys){S.tileCache.delete(k);S.tileUse.delete(k)}}
async function tileImage(url){S.tileUse.set(url,performance.now());if(S.tileCache.has(url))return S.tileCache.get(url);const p=new Promise((resolve,reject)=>{const im=new Image();im.decoding='async';im.onload=()=>resolve(im);im.onerror=()=>reject(new Error(`tile failed ${url}`));im.src=url});S.tileCache.set(url,p);trimTiles();return p}
function visibleTiles(level){const w=level.width,h=level.height,t=level.tileSize,cols=level.cols,rows=level.rows;const nx=(((-S.yaw/(Math.PI*2))%1)+1)%1,ny=clamp(.5-S.pitch/Math.PI,0,1);const cx=nx*w,cy=ny*h;const fovV=THREE.MathUtils.degToRad(S.fov);const fovH=2*Math.atan(Math.tan(fovV/2)*S.camera.aspect);const spanX=Math.max(t*1.5,fovH/(Math.PI*2)*w*1.45),spanY=Math.max(t*1.3,fovV/Math.PI*h*1.45);const y0=clamp(Math.floor((cy-spanY)/t),0,rows-1),y1=clamp(Math.floor((cy+spanY)/t),0,rows-1);const xCount=Math.min(cols,Math.ceil((spanX*2)/t)+2);const center=Math.floor(cx/t);const xs=[];for(let d=-Math.ceil(xCount/2);d<=Math.ceil(xCount/2);d++)xs.push((center+d+cols)%cols);const uniq=[...new Set(xs)];const out=[];for(let y=y0;y<=y1;y++)for(const x of uniq)out.push({x,y});return out}
async function renderFrame(index){if(!S.manifest)return;const token=++S.renderToken;S.baseTier=baseTier();S.targetLevel=chooseLevel();const base=S.manifest[S.baseTier];const baseUrl=base.frames[index%base.frames.length];const im=await image(baseUrl);if(token!==S.renderToken)return;const width=S.targetLevel?.width||base.width,height=S.targetLevel?.height||base.height;S.canvas.width=width;S.canvas.height=height;S.ctx.imageSmoothingEnabled=false;S.ctx.clearRect(0,0,width,height);S.ctx.drawImage(im,0,0,width,height);S.texture.needsUpdate=true;if(S.targetLevel){const tiles=visibleTiles(S.targetLevel);for(const q of tiles){const url=S.targetLevel.template.replace('{frame}',pad(index+1)).replace('{x}',String(q.x)).replace('{y}',String(q.y));tileImage(url).then(tile=>{if(token!==S.renderToken)return;S.ctx.imageSmoothingEnabled=false;S.ctx.drawImage(tile,q.x*S.targetLevel.tileSize,q.y*S.targetLevel.tileSize);S.texture.needsUpdate=true}).catch(()=>{});}prefetchTiles((index+1)%S.manifest.source.frameCount,S.targetLevel,tiles)}}
function prefetchTiles(index,level,tiles){for(const q of tiles.slice(0,12)){const u=level.template.replace('{frame}',pad(index+1)).replace('{x}',String(q.x)).replace('{y}',String(q.y));tileImage(u).catch(()=>{})}}
function updateCamera(){S.pitch=clamp(S.pitch,-Math.PI/2+.001,Math.PI/2-.001);S.camera.rotation.order='YXZ';S.camera.rotation.y=S.yaw;S.camera.rotation.x=S.pitch}
function projectHotspots(){const v=new THREE.Vector3();for(const h of S.hotspots){const r=400,yaw=Number(h.yaw||0),pitch=Number(h.pitch||0);v.set(Math.sin(yaw)*Math.cos(pitch)*r,Math.sin(pitch)*r,Math.cos(yaw)*Math.cos(pitch)*r).project(S.camera);h.el.style.display=v.z<1?'block':'none';h.el.style.left=`${(v.x*.5+.5)*innerWidth}px`;h.el.style.top=`${(-v.y*.5+.5)*innerHeight}px`}}
function renderHotspots(){ui.hotspots.innerHTML='';S.hotspots=(S.manifest?.hotspots||[]).map(h=>{const b=document.createElement('button');b.className='hotspot';b.textContent=h.label||'hotspot';b.onclick=()=>{if(h.targetManifest){ui.manifestInput.value=h.targetManifest;loadFromInput()}};ui.hotspots.appendChild(b);return{...h,el:b}})}
async function loadManifest(url){status('Loading manifest…');const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`manifest ${r.status}`);const m=await r.json();if(m.type!=='pixel-panorama-360')throw new Error('manifest type mismatch');S.manifest=m;S.fps=m.fps||8;ui.fpsRange.value=String(S.fps);ui.fpsValue.textContent=String(S.fps);S.frameIndex=0;S.acc=0;S.baseCache.clear();S.tileCache.clear();S.tileUse.clear();S.tileLimit=mobile()?72:180;renderHotspots();await renderFrame(0);ui.editorLink.href=`./editor.html?manifest=${encodeURIComponent(url)}`;status(`Ready: ${m.title||m.slug} · tiles ${m.multires?.levels?.length||0}`)}
async function loadFromInput(){const url=ui.manifestInput.value.trim();if(!url)return;const loc=new URL(location.href);loc.searchParams.set('manifest',url);history.replaceState({},'',loc);try{await loadManifest(url)}catch(e){status(`Error: ${e.message}`)}}
function pointerDistance(){const a=[...S.pointers.values()];if(a.length<2)return 0;return Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)}
function bind(){window.addEventListener('resize',resize);ui.stage.addEventListener('pointerdown',e=>{S.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});ui.stage.setPointerCapture(e.pointerId);if(S.pointers.size===1){S.dragId=e.pointerId}else if(S.pointers.size===2){S.lastDist=pointerDistance()}});ui.stage.addEventListener('pointermove',e=>{const old=S.pointers.get(e.pointerId);if(!old)return;S.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(S.pointers.size===1&&S.dragId===e.pointerId){S.yaw-=(e.clientX-old.x)*.0055;S.pitch-=(e.clientY-old.y)*.0045}else if(S.pointers.size>=2){const d=pointerDistance();if(S.lastDist){S.fov=clamp(S.fov-(d-S.lastDist)*.045,30,95);resize()}S.lastDist=d}});const end=e=>{S.pointers.delete(e.pointerId);if(S.dragId===e.pointerId)S.dragId=null;if(S.pointers.size<2)S.lastDist=0};ui.stage.addEventListener('pointerup',end);ui.stage.addEventListener('pointercancel',end);ui.stage.addEventListener('wheel',e=>{e.preventDefault();S.fov=clamp(S.fov+Math.sign(e.deltaY)*2.5,30,95);resize()},{passive:false});ui.loadBtn.onclick=loadFromInput;ui.playBtn.onclick=()=>{S.playing=!S.playing;ui.playBtn.textContent=S.playing?'Пауза':'Играть'};ui.fullscreenBtn.onclick=async()=>{if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();else await document.exitFullscreen?.()};ui.fpsRange.oninput=()=>{S.fps=Number(ui.fpsRange.value);ui.fpsValue.textContent=String(S.fps)};ui.qualitySelect.onchange=()=>{S.quality=ui.qualitySelect.value;renderFrame(S.frameIndex)};ui.gyroBtn.onclick=toggleGyro;ui.refreshRegistryBtn.onclick=loadRegistry;ui.factoryBuild.onclick=createJob}
async function toggleGyro(){try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')throw new Error('permission denied')}S.gyro=!S.gyro;ui.gyroBtn.textContent=S.gyro?'Гироскоп ON':'Гироскоп'}catch(e){status(`Gyro: ${e.message}`)}}window.addEventListener('deviceorientation',e=>{if(!S.gyro)return;if(Number.isFinite(e.alpha)&&Number.isFinite(e.beta)){S.yaw=THREE.MathUtils.degToRad(-(e.alpha||0));S.pitch=THREE.MathUtils.degToRad(clamp((e.beta||0)-30,-80,80))}})
async function loadRegistry(){try{const r=await fetch('/api/pixel-panorama?action=registry',{cache:'no-store'});const j=await r.json();ui.registryList.innerHTML='';if(!j.items?.length){ui.registryList.innerHTML='<div class="muted">No projects</div>';return}for(const it of j.items){const d=document.createElement('div');d.className='registryItem';d.innerHTML=`<h3>${esc(it.title||it.slug)}</h3><p>${esc(it.description||'')}</p><button>Открыть</button>`;d.querySelector('button').onclick=()=>{ui.manifestInput.value=it.remoteManifestUrl||it.manifestUrl;loadFromInput()};ui.registryList.appendChild(d)}}catch(e){ui.registryList.innerHTML=`<div class="muted">${esc(e.message)}</div>`}}
async function session(force=false){if(!force&&S.session&&S.session.expiresAt>Date.now()+30000)return S.session;const r=await fetch('/api/ai3d',{cache:'no-store'});const j=await r.json();if(!r.ok||!j.enabled)throw new Error(j.error||j.reason||'AI3D worker unavailable');S.session=j;return j}
async function authFetch(path,opts={}){const s=await session();const h=new Headers(opts.headers||{});h.set('Authorization',`Bearer ${s.token}`);return fetch(`${s.workerUrl}${path}`,{...opts,headers:h})}
function progress(v,label){ui.factoryBar.style.width=`${clamp(Number(v)||0,0,100)}%`;ui.factoryState.textContent=label||''}
async function createJob(){ui.factoryBuild.disabled=true;ui.factoryFiles.innerHTML='';try{const f=ui.factoryFile.files?.[0];if(!f)throw new Error('Выбери файл');const s=await session();const limit=(s.panoramaMaxUploadMb||s.maxUploadMb||100)*1024*1024;if(f.size>limit)throw new Error(`Файл больше лимита ${Math.round(limit/1024/1024)} MB`);const form=new FormData();form.set('mode','pixel_panorama_360');form.set('params',JSON.stringify({slug:ui.factorySlug.value.trim()||f.name.replace(/\.[^.]+$/,''),title:ui.factoryTitle.value.trim()||f.name,fps:Number(ui.factoryFps.value)||8,publishSupabase:ui.factoryPublish.checked}));form.set('file',f,f.name);progress(2,'Creating job');let r=await authFetch('/v1/jobs',{method:'POST',body:form});const j=await r.json();if(!r.ok)throw new Error(j.detail||j.error||'job rejected');pollJob(j.id)}catch(e){progress(0,`Error: ${e.message}`);ui.factoryBuild.disabled=false}}
async function pollJob(id){clearTimeout(S.poll);try{let r=await authFetch(`/v1/jobs/${encodeURIComponent(id)}`);if(r.status===401){await session(true);r=await authFetch(`/v1/jobs/${encodeURIComponent(id)}`)}const j=await r.json();if(!r.ok)throw new Error(j.detail||j.error||'poll failed');progress(j.progress,`${j.status} · ${j.message||''}`);if(j.status==='completed'){ui.factoryBuild.disabled=false;renderResults(j);return}if(j.status==='failed'){ui.factoryBuild.disabled=false;throw new Error(j.error||'worker failed')}S.poll=setTimeout(()=>pollJob(id),1200)}catch(e){progress(0,`Error: ${e.message}`);ui.factoryBuild.disabled=false}}
function renderResults(job){ui.factoryFiles.innerHTML='';if(job.panorama?.remoteManifestUrl){const open=document.createElement('button');open.textContent='Открыть опубликованную панораму';open.onclick=()=>{ui.manifestInput.value=job.panorama.remoteManifestUrl;loadFromInput()};ui.factoryFiles.appendChild(open);}for(const f of job.files||[]){const d=document.createElement('div');d.className='resultFile';const b=document.createElement('button');b.textContent=`Скачать ${f.name}`;b.onclick=async()=>{let r=await authFetch(f.url);if(r.status===401){await session(true);r=await authFetch(f.url)}if(!r.ok)return;const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=f.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),30000)};d.appendChild(b);ui.factoryFiles.appendChild(d)}}
function loop(){let last=performance.now();const tick=now=>{const dt=(now-last)/1000;last=now;if(S.playing&&S.manifest?.source?.frameCount>1){S.acc+=dt;const fd=1/Math.max(1,S.fps);if(S.acc>=fd){S.acc%=fd;S.frameIndex=(S.frameIndex+1)%S.manifest.source.frameCount;renderFrame(S.frameIndex)}}updateCamera();projectHotspots();S.renderer.render(S.scene,S.camera);requestAnimationFrame(tick)};requestAnimationFrame(tick)}
window.PixelPano360={getView:()=>({yaw:S.yaw,pitch:S.pitch,fov:S.fov}),setView:v=>{if(Number.isFinite(v?.yaw))S.yaw=v.yaw;if(Number.isFinite(v?.pitch))S.pitch=v.pitch;if(Number.isFinite(v?.fov)){S.fov=v.fov;resize()}},loadManifestUrl:async u=>{ui.manifestInput.value=u;await loadFromInput()}};
async function boot(){init();bind();loop();await loadRegistry();const q=new URL(location.href).searchParams.get('manifest');if(q){ui.manifestInput.value=q;await loadFromInput()}else status('Ready. Select registry item or manifest.')}boot().catch(e=>status(`Boot error: ${e.message}`));
