#!/usr/bin/env python3
from __future__ import annotations
import json
from quality_common import QUALITY, read_json, write_json

# Engineering readiness: implemented = code/config/path exists; verified = actually executed in this environment.
SYSTEMS=[
 ('immutable-source-fidelity-and-geometry-regression',8,100,100,'source SHA locks + anti-decimation/anti-downscale regression verified'),
 ('spawn-controls-camera-static-world-physics',9,100,96,'fixed 60 Hz capsule/controller invariants verified; full physical browser input remains CI/live-side'),
 ('auto-collider-mesh-gaussian-ply-and-spz',8,100,99,'mesh/Gaussian PLY verified; native legacy SPZ positions verified on real assets; v4 path implemented without attached v4 sample'),
 ('auto-orientation-scale-semantics-navigation',7,100,96,'conservative inference + semantic floor/wall analysis + nav graph + fail-closed fallback'),
 ('lossless-ply-and-static-glb-streaming',6,100,97,'PLY face conservation and static GLB conservation implemented/verified synthetically'),
 ('byte-identical-animated-skinned-morph-glb-range-streaming',6,100,97,'GLB byte-range plan + exact reconstruction path conserves every byte before GLTF parse'),
 ('predictive-nearest-first-streaming',4,100,98,'velocity look-ahead + nearest-first + adaptive concurrency implemented'),
 ('near-field-lossless-fps-optimizer',8,100,100,'near field never loses resolution/source geometry/textures; pressure governor only reduces distant/noncritical work'),
 ('webgl2-safe-occlusion-fallback',3,100,80,'conservative query fallback with >=42m near bypass; browser GPU execution remains external'),
 ('webgpu-private-depth-hzb-visibility',5,100,72,'actual source triangles feed a private depth pass + conservative HZB; fail-visible and near bypass hardcoded; WebGPU browser not available here'),
 ('webgpu-lossless-meshlet-indirect-kernel',4,98,66,'compute-generated drawIndexedIndirect commands preserve source index ranges; full PBR renderer handoff is capability-gated'),
 ('compiled-wasm-simd128-fastpath',4,100,100,'real wasm32 SIMD binary compiled and numerically executed under Node'),
 ('lossless-meshlet-cluster-metadata',4,100,100,'sample-city: 683077 source triangles -> 683077 meshlet triangles, 5337 meshlets'),
 ('immutable-indexeddb-sha-and-bvh-cache',5,100,91,'source hash verification + serialized MeshBVH cache implemented; browser persistence remains CI-side'),
 ('worker-ply-decode-safe-fallback',4,100,91,'binary little-endian worker parser + transferable arrays + PLYLoader fail-safe fallback'),
 ('exact-material-dedup-static-shadow-cache',4,100,96,'exact render signature only; shadows freeze only with zero dynamic shadow casters'),
 ('offline-raytraced-gi-companion',5,100,93,'source-locked voxel ray-traced irradiance companion executes on synthetic meshes; production-world bake delegated to installer/preparer'),
 ('offline-source-locked-reflection-probes',4,100,91,'six-face offline ray-traced cubemap companion executes synthetically with runtime fallback'),
 ('static-lightmap-glb-uv-companion',4,100,96,'UV companion verified synthetic; no-UV safe fallback'),
 ('swept-dynamic-mesh-collision',5,100,92,'exact local MeshBVH + continuous relative translation sweep + conservative AABB fallback wired into controller'),
 ('dynamic-platform-elevator-water',3,100,92,'platform carry, elevator and water runtime remain shared/source-safe'),
 ('atmosphere-fog-haze-mirage-and-wet-style',6,100,95,'far cost concealed by atmosphere; global subtle wet material/post fallback preserves sources'),
 ('network-interest-and-distant-pose-sharing',4,100,94,'near entities/rigs untouched; only distant update cadence is reduced'),
 ('browser-playtest-fuzz-replay',5,100,67,'automation implemented; Playwright dependencies/browser are CI/desktop-side'),
 ('visual-golden-regression',5,100,64,'strict visual diff path implemented; golden capture requires real browser/render target'),
 ('permanent-error-memory-global-fingerprints',8,100,100,'55 protected failure classes compile to prevention rules + mandatory regression tests'),
 ('compiled-global-protection-pack',7,100,100,'every protected incident compiles into one stable cross-project protection hash'),
 ('unknown-error-quarantine',6,100,100,'new fingerprint blocks release until root cause + rule + test + shared fix'),
 ('transactional-known-antipattern-self-heal',5,100,100,'exact known repairs only, backup, full tests, automatic rollback on any failure'),
 ('quality-genome-cross-project-inheritance',7,100,97,'proven traits + protection/runtime hashes are inherited by consumers; external repos unavailable here'),
 ('optimization-promotion-zero-quality-regression',6,100,100,'FPS wins can promote only when visual/source/regression scores stay non-regressed'),
 ('transactional-canary-rollout-auto-rollback',6,100,93,'canary -> verify -> all -> verify with rollback; no external consumers connected here'),
 ('proven-pattern-auto-promotion',5,100,98,'multi-project repeated evidence promotes safe successes into mandatory genome'),
 ('learning-preservation-across-upgrades',4,100,100,'installer merges incidents/patterns/genome/evidence/quarantine/history instead of forgetting'),
 ('global-quality-autopilot',5,100,98,'telemetry import option -> self-heal -> pipeline -> learn -> fix queue -> protection -> canary/global rollout -> verify'),
 ('last-known-good-release-state',4,100,98,'approved runtime/protection hashes retained and rollbackable'),
 ('production-quality-telemetry-api-export-import',5,100,71,'global root-cause fingerprint API/export/import is implemented; no connected durable Neon deployment exists here'),
 ('fix-code-test-rule-global-rollout-agent-interface',5,99,84,'safe repairs autonomous; unknown fixes produce proof-obligation task for desktop code executor rather than guessing'),
 ('gameplay-action-contracts-and-audio-variation',4,98,90,'feet/attack/shield/weapon invariants + reusable gameplay/audio systems implemented'),
 ('ci-cd-quality-wall',6,100,94,'static/unit/protection/local consumer gates PASS; browser/visual and live consumer rollout remain external'),
 ('one-command-world-v10-production-preparation',5,100,100,'new-world ingest attaches V10 CPU-first lossless fastpaths immediately and queues heavy source-locked bakes to the distributed farm'),
 ('source-equivalent-webgpu-pbr-core-and-material-audit',7,99,78,'PBR shader/core + strict source-material semantic audit are runtime-wired; authoritative takeover remains fail-closed until real device/golden parity'),
 ('threaded-wasm-simd-worker-pool',5,100,100,'Node worker_threads + WASM SIMD parity verified on 1.2M items with exact byte-copy parity'),
 ('parallel-exact-bvh-prepass',4,100,88,'exact triangle bounds/centroids worker prepass implemented; browser execution remains device-farm side'),
 ('monotonic-quality-ratchet',7,100,100,'persisted quality floors never decrease; installer preserves max historical floors and any regression blocks release'),
 ('quality-knowledge-graph',6,100,100,'55 protected incidents compile into rule/test/protection/genome graph with zero unprotected incidents'),
 ('content-addressed-distributed-bake-farm',6,100,90,'deterministic shards/cache/source locks and cached artifact materialization verified; full heavy GI shard is delegated to bake nodes'),
 ('sandboxed-unknown-fix-proof-agent',6,99,88,'sandbox/executor/proof/apply boundary implemented; real unknown incident with external code executor not available here'),
 ('representative-device-performance-farm',5,100,65,'real Playwright desktop/mobile/WebGPU matrix is in CI; browser dependencies/device execution unavailable in this container'),
 ('durable-neon-quality-evidence',5,100,62,'migration, APIs and DB smoke tool implemented; no connected Neon project/DATABASE_URL here'),
 ('representative-canary-and-consumer-drift',5,100,91,'representative selection + exact runtime/protection drift blocking implemented; external consumer projects unavailable'),
 ('transactional-v10-installer',7,100,100,'V10 installer is transactional: preserve history/worlds -> migrate -> prepare -> self-heal -> tests -> ratchet -> rollout/drift -> readiness'),
 ('browser-native-shared-memory-zero-copy-decode',5,100,93,'SharedArrayBuffer arena + COOP/COEP contract + safe transferable fallback verified statically/unit; real isolated browser path remains device-farm side'),
 ('webgpu-exact-material-table-bindless-capability',5,100,90,'exact PBR factors/source texture dimensions preserved; bindless remains capability-gated and proven bindgroups are fallback'),
 ('conservative-webgpu-clustered-lighting',5,100,88,'cluster assignment is fail-bright with full-light-list overflow fallback; live GPU parity remains device-farm side'),
 ('full-resolution-virtual-texture-residency',5,100,97,'near pages pinned at source resolution, eviction limited to far/nonvisible pages, whole-source fallback preserves fidelity'),
 ('conservative-portal-room-visibility',4,100,100,'unknown/near rooms fail visible; conservative graph builder and runtime contract tested'),
 ('screen-space-animation-budget-near-exact',4,100,100,'near/interacting rigs retain full update rate and deferred time is accumulated rather than discarded'),
 ('physics-spatial-broadphase-safe-sleep',4,100,100,'spatial broadphase + distant sleeping; near/player-contact bodies are hard-blocked from sleep'),
 ('lossless-network-delta-compression',4,100,99,'changed fields only, no quantization, exact local-player authority contract tested'),
 ('ratchet-approved-per-device-performance-schedules',5,100,100,'learner may tune only whitelisted cost knobs after source/near/visual proof; fidelity knobs are rejected'),
 ('persistent-derived-artifact-cas-local-r2',4,100,90,'local content-addressed cache/source lock verified; R2 upload adapter requires real credentials/service'),
 ('pattern-applicability-firewall',5,100,100,'successful patterns require applicability/capability proof; blind global propagation is forbidden'),
 ('frame-budget-orchestrator-near-critical',4,100,99,'background work is budgeted/deferred while near-critical render/physics work is never traded for FPS'),
 ('p99-hitch-regression-ratchet',4,100,100,'frame-time p99 and >50ms hitch count gate prevents average-FPS wins that worsen stutter'),
 ('durable-performance-evidence-v8',4,100,72,'V8 schema/API records FPS p95/p99/hitches and only quality-safe schedules; live Neon roundtrip not connected here'),
 ('cpu-first-server-no-paid-gpu',7,100,100,'all mandatory preparation/runtime has CPU/cache/client path; server GPU is optional client-side capability only'),
 ('incremental-world-compiler',6,100,100,'content-hash dependency plan rebuilds only affected systems; source unchanged'),
 ('cpu-pvs-hierarchical-visibility-cache',6,100,96,'precomputed PVS + hierarchy + conservative CPU occlusion cache; browser runtime path awaits consumer E2E'),
 ('predictive-streaming-v2',5,100,98,'motion/camera aware prefetch with near-first fidelity lock'),
 ('incremental-cpu-light-shadow-bake',5,100,95,'dirty-region CPU bake plan and cached static shadows; full production bake corpus external'),
 ('nav-collision-source-hash-cache',4,100,100,'cache key binds source SHA and parameters'),
 ('near-exact-simulation-lod',5,100,100,'only distant AI/animation/physics cadence is reduced; near remains exact/full rate'),
 ('cpu-causality-profiler-and-safe-autotuner',6,100,100,'profiler finds CPU bottleneck; tuner whitelist rejects all fidelity knobs and p99/hitch regressions'),
 ('production-deterministic-replay-memory',6,100,96,'normalized replay/fingerprint storage implemented; real production stream connection remains external'),
 ('desktop-ai-no-stop-until-green-protocol',4,100,100,'instructions require diagnose-fix-retest loop until every required gate passes or a proven external hard blocker exists'),
 ('threaded-exact-cpu-import-pool',5,100,94,'worker pool preserves exact source bytes with deterministic single-worker fallback; real browser importer fan-out remains consumer-side'),
 ('bounded-memory-mmap-huge-world-reader',5,100,100,'mmap/windowed reader self-test reconstructs exact bytes without whole-file materialization'),
 ('semantic-conservative-pvs-v10',5,100,100,'semantic room/portal closure tested; unknown and near space fail visible'),
 ('incremental-gi-cell-reuse-v10',5,100,100,'only exact input-hash cells reuse baked output; dirty/new cells rebuild'),
 ('lossless-derived-cache-transport',4,100,100,'Brotli roundtrip SHA parity verified locally; optional zstd path is capability gated'),
 ('service-worker-shared-worker-sha-cache',4,100,88,'version/SHA isolation and source-safe contracts verified statically; real multi-tab/offline browser execution remains device-side'),
 ('content-defined-lossless-chunking',5,100,100,'CDC self-test reconstructs byte-identical payload and SHA'),
 ('exact-derived-binary-delta',4,100,100,'derived-artifact delta self-test reconstructs exact target SHA'),
 ('automatic-cpu-flamegraph-evidence-v10',4,100,100,'cProfile causality evidence executes before autotuning and touches no source assets'),
 ('deterministic-network-physics-replay-farm-v10',5,100,100,'five seeded network/physics simulations repeat to identical hashes'),
 ('code-asset-bake-game-dependency-graph',6,100,100,'dependency graph builds and propagates source-asset impact through derived bakes to game manifests'),

]

INTEGRATION_LINKS=[
 ('world-ingest->v8-production-preparer',8,100),
 ('v8-preparer->source-lock->manifest',8,100),
 ('shared-runtime->near-field-lossless-optimizer',8,100),
 ('meshlet-metadata->webgpu-indirect-kernel',5,99),
 ('world-loader->byte-identical-glb-range-assembler',5,100),
 ('webgpu-hzb->safe-webgl2-fallback',5,100),
 ('offline-bakes->runtime-source-sha-validation',5,100),
 ('dynamic-environment->swept-mesh-collision->player',6,100),
 ('production-telemetry->global-fingerprint->quarantine',7,100),
 ('incident-memory->compiled-protection-pack',8,100),
 ('protection-pack->quality-genome',7,100),
 ('quality-genome->transactional-rollout',7,100),
 ('self-heal->full-tests->rollback',6,100),
 ('upgrade-installer->history-preservation->autopilot',6,100),
 ('unknown-fix-task->desktop-code-executor',4,97),
 ('browser-golden-tests->release-wall',4,99),
 ('world-ingest->distributed-bake-queue',8,100),
 ('quality-ratchet->release-wall',7,100),
 ('incident->rule->test->protection->consumer-graph',8,100),
 ('bake-farm->sha-cache->derived-artifact-materializer',5,100),
 ('webgpu-pbr-material-audit->authority-gate',5,99),
 ('wasm-thread-pool->compatible-fastpath-registry',4,100),
 ('device-farm->renderer-promotion-gate',5,100),
 ('neon-evidence->pattern-promotion-gate',5,100),
 ('representative-canary->rollout->consumer-drift-audit',6,100),
 ('sandbox-fix->proof->ratchet->rollout',6,100),
 ('cross-origin-isolation->shared-memory-decode->safe-fallback',5,100),
 ('exact-material-table->clustered-lighting->webgpu-authority-gate',5,99),
 ('virtual-texture-residency->near-field-quality-lock',5,100),
 ('portal-visibility->fail-visible->near-bypass',4,100),
 ('screen-space-animation->interaction-boundary-exactness',4,100),
 ('physics-broadphase->player-contact-awake',4,100),
 ('lossless-network-delta->local-player-authority',4,100),
 ('device-evidence->safe-schedule-learner->quality-ratchet',5,100),
 ('pattern-evidence->applicability-firewall->consumer-propagation',5,100),
 ('frame-times->p99-hitch-gate->release-wall',4,100),
 ('derived-artifact->content-hash->local-r2-cas',4,99),
 ('source-hash->incremental-compiler->affected-systems-only',6,100),
 ('cpu-pvs->hierarchical-grid->occlusion-cache->near-fail-visible',6,100),
 ('player-motion-camera->predictive-streaming-v2->near-residency',5,100),
 ('changed-bounds->incremental-cpu-light-bake->static-shadow-cache',5,100),
 ('source-sha-params->nav-collision-cache->world-preparer',4,100),
 ('cpu-profiler->safe-autotuner->p99-hitch-ratchet',6,100),
 ('production-replay->incident-fingerprint->mandatory-regression',6,100),
 ('desktop-ai-diagnose->fix->retest-loop->release-wall',5,100),
 ('threaded-import->exact-fallback->source-sha-gate',5,100),
 ('mmap-window->content-defined-chunks->lossless-cache-codec',5,100),
 ('semantic-pvs->near-fail-visible->visibility-runtime',5,100),
 ('cell-input-hash->incremental-gi-reuse->lighting-ratchet',5,100),
 ('service-worker->shared-worker->sha-version-isolation',4,100),
 ('cpu-flamegraph->safe-autotuner->ratchet',4,100),
 ('network-physics-replay-farm->fingerprint->permanent-regression',5,100),
 ('dependency-graph->incremental-impact->release-wall',6,100),

]

def main():
    weight=sum(w for _,w,_,_,_ in SYSTEMS)
    impl=round(sum(w*i for _,w,i,_,_ in SYSTEMS)/weight,1)
    ver=round(sum(w*v for _,w,_,v,_ in SYSTEMS)/weight,1)
    iw=sum(w for _,w,_ in INTEGRATION_LINKS)
    connectivity=round(sum(w*v for _,w,v in INTEGRATION_LINKS)/iw,1)
    static=read_json(QUALITY/'reports/static-validation.json',{}).get('score')
    pipe=read_json(QUALITY/'reports/quality-pipeline.json',{})
    report={
      'schemaVersion':10,'runtime':'WORLD_FACTORY_QUALITY_CORE_V10',
      'implementationReadinessPercent':impl,'integrationConnectivityPercent':connectivity,'verifiedEndToEndPercent':ver,
      'staticQualityGatePercent':static,'localQualityPipelinePass':pipe.get('pass'),
      'systems':[{'id':sid,'weight':w,'implementedPercent':i,'verifiedPercent':v,'note':n} for sid,w,i,v,n in SYSTEMS],
      'integrationLinks':[{'id':sid,'weight':w,'connectedPercent':v} for sid,w,v in INTEGRATION_LINKS],
      'connectivityMeaning':'internal shared-core wiring. External GitHub/Vercel/Neon consumer execution is deliberately represented in verifiedEndToEndPercent instead of inflating connectivity.',
      'verificationMeaning':'verifiedPercent counts actual execution possible in this environment; real browser/WebGPU, durable Neon DB, external code executor, heavy distributed GI shard, and external consumer canary runs remain lower until connected.'
    }
    write_json(QUALITY/'reports/implementation-status.json',report);print(json.dumps(report,ensure_ascii=False,indent=2))
if __name__=='__main__':main()
