begin;
create table if not exists public.quality_canary_runtime_state (
  project_id text primary key check (char_length(project_id) between 1 and 120),
  enabled boolean not null default false,
  candidate_url text not null default '',
  traffic_percent numeric(5,2) not null default 0 check (traffic_percent between 0 and 100),
  release_id text not null default 'unknown',
  stage_index integer not null default 0 check (stage_index between 0 and 100),
  updated_at timestamptz not null default now()
);
alter table public.quality_canary_runtime_state enable row level security;
revoke all on table public.quality_canary_runtime_state from anon, authenticated;
drop policy if exists quality_canary_runtime_service_only on public.quality_canary_runtime_state;
create policy quality_canary_runtime_service_only on public.quality_canary_runtime_state for all to service_role using (true) with check (true);

create table if not exists public.quality_worker_jobs (
  id bigint generated by default as identity primary key,
  job_key text not null unique,
  kind text not null,
  priority integer not null default 0,
  required_capabilities jsonb not null default '[]'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'queued' check (status in ('queued','running','complete','failed','cancelled')),
  attempts integer not null default 0,
  max_attempts integer not null default 3,
  lease_owner text,
  lease_expires_at timestamptz,
  result jsonb,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists quality_worker_jobs_queue_idx on public.quality_worker_jobs(status,priority desc,created_at);
alter table public.quality_worker_jobs enable row level security;
revoke all on table public.quality_worker_jobs from anon, authenticated;
revoke all on sequence public.quality_worker_jobs_id_seq from anon, authenticated;
drop policy if exists quality_worker_jobs_service_only on public.quality_worker_jobs;
create policy quality_worker_jobs_service_only on public.quality_worker_jobs for all to service_role using (true) with check (true);

create table if not exists public.quality_deterministic_replays (
  replay_id text primary key,
  project_id text not null,
  release_id text not null,
  replay jsonb not null,
  status text not null default 'recorded',
  last_result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists quality_replays_project_idx on public.quality_deterministic_replays(project_id,created_at desc);
alter table public.quality_deterministic_replays enable row level security;
revoke all on table public.quality_deterministic_replays from anon, authenticated;
drop policy if exists quality_replays_service_only on public.quality_deterministic_replays;
create policy quality_replays_service_only on public.quality_deterministic_replays for all to service_role using (true) with check (true);

create table if not exists public.quality_visual_oracle_results (
  id bigint generated by default as identity primary key,
  project_id text not null,
  release_id text not null,
  baseline_score numeric not null,
  candidate_score numeric not null,
  decision text not null check (decision in ('accept','reject','hold')),
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists quality_visual_oracle_project_idx on public.quality_visual_oracle_results(project_id,created_at desc);
alter table public.quality_visual_oracle_results enable row level security;
revoke all on table public.quality_visual_oracle_results from anon, authenticated;
revoke all on sequence public.quality_visual_oracle_results_id_seq from anon, authenticated;
drop policy if exists quality_visual_oracle_service_only on public.quality_visual_oracle_results;
create policy quality_visual_oracle_service_only on public.quality_visual_oracle_results for all to service_role using (true) with check (true);
commit;
