from pathlib import Path
root=Path(__file__).resolve().parents[1]
def rep(rel,old,new):
 p=root/rel; t=p.read_text(encoding='utf-8-sig')
 if new in t: print('[skip]',rel); return
 if old not in t: raise SystemExit(f'anchor missing: {rel}')
 p.write_text(t.replace(old,new,1),encoding='utf-8'); print('[ok]',rel)
rep('apps/dreamfog-world/client.js',"const player={x:0,y:1.72,z:7,yaw:0,pitch:-.04,vy:0,grounded:true};","const player={x:0,y:1.72,z:7,yaw:0,pitch:-.04,vy:0,grounded:true};\nwindow.GamePlayableRuntime={stats:()=>({player:{x:player.x,y:player.y,z:player.z,yaw:player.yaw,pitch:player.pitch}})};")
rep('apps/ink-glyph-world/index.html','  <script src="../../shared/ink-glyph-world-core.js"></script>','  <link rel="stylesheet" href="/shared/golden-ui-shell.css">\n  <script src="/shared/ai3d-playable-runtime.js"></script>\n  <script src="/shared/golden-experience-controls.js"></script>\n  <script src="/shared/golden-ui-shell.js"></script>\n  <script src="../../shared/ink-glyph-world-core.js"></script>')
rep('apps/pixel-panorama-360/index.html','<link rel="stylesheet" href="./styles.css">','<link rel="stylesheet" href="./styles.css">\n<link rel="stylesheet" href="/shared/golden-ui-shell.css">')
rep('apps/pixel-panorama-360/index.html','<script type="module" src="./client.js"></script>','<script src="/shared/ai3d-playable-runtime.js"></script>\n<script src="/shared/golden-experience-controls.js"></script>\n<script src="/shared/golden-ui-shell.js"></script>\n<script type="module" src="./client.js"></script>')
rep('apps/ink-glyph-world/client.js',"function updateCamera(){pitch=Core.clamp(pitch,.18,1.42);distance=Core.clamp(distance,15,175);const cp=Math.cos(pitch);camera.position.set(target.x+Math.sin(yaw)*cp*distance,target.y+Math.sin(pitch)*distance,target.z+Math.cos(yaw)*cp*distance);camera.lookAt(target)}","function updateCamera(){pitch=Core.clamp(pitch,.18,1.42);distance=Core.clamp(distance,15,175);const cp=Math.cos(pitch);camera.position.set(target.x+Math.sin(yaw)*cp*distance,target.y+Math.sin(pitch)*distance,target.z+Math.cos(yaw)*cp*distance);camera.lookAt(target)}\nwindow.GoldenExperienceControls?.install({stats:()=>({x:target.x,y:target.y,z:target.z,yaw,pitch}),move:(forward,side,dt)=>{const speed=12*dt;target.x+=(Math.sin(yaw)*-forward+Math.cos(yaw)*side)*speed;target.z+=(Math.cos(yaw)*-forward-Math.sin(yaw)*side)*speed;updateCamera();},look:(dx,dy)=>{yaw-=dx*.005;pitch+=dy*.004;updateCamera();}});")
rep('apps/pixel-panorama-360/client.js',"function updateCamera(){S.pitch=clamp(S.pitch,-Math.PI/2+.001,Math.PI/2-.001);S.camera.rotation.order='YXZ';S.camera.rotation.y=S.yaw;S.camera.rotation.x=S.pitch}","function updateCamera(){S.pitch=clamp(S.pitch,-Math.PI/2+.001,Math.PI/2-.001);S.camera.rotation.order='YXZ';S.camera.rotation.y=S.yaw;S.camera.rotation.x=S.pitch}\nlet goldenX=0,goldenZ=0;window.GoldenExperienceControls?.install({stats:()=>({x:goldenX,y:0,z:goldenZ,yaw:S.yaw,pitch:S.pitch}),move:(forward,side,dt)=>{const step=2.4*dt;goldenX+=Math.sin(S.yaw)*forward*step+Math.cos(S.yaw)*side*step;goldenZ+=Math.cos(S.yaw)*forward*step-Math.sin(S.yaw)*side*step;S.yaw-=side*1.8*dt;S.pitch=clamp(S.pitch+forward*.7*dt,-1.45,1.45);updateCamera();},look:(dx,dy)=>{S.yaw-=dx*.0055;S.pitch-=dy*.0045;updateCamera();}});")
