-- WORLD SERVER V8 quality telemetry. Server-side writes only.
create table if not exists public.quality_telemetry (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  app text not null,
  event_type text not null,
  path text,
  load_ms integer,
  dom_ms integer,
  fps integer,
  error_count integer,
  coarse boolean,
  viewport_w integer,
  viewport_h integer,
  dpr numeric,
  message text
);

alter table public.quality_telemetry enable row level security;

create index if not exists quality_telemetry_created_at_idx
  on public.quality_telemetry(created_at desc);
create index if not exists quality_telemetry_app_created_at_idx
  on public.quality_telemetry(app, created_at desc);

comment on table public.quality_telemetry is
  'Privacy-minimal aggregate runtime quality telemetry. No user identity, IP, email, account id or free-form payload is stored.';
