-- V11 Silent CPU Quality Autopilot
create table if not exists public.quality_projects (
  project_key text primary key,
  enabled boolean not null default true,
  autopilot_mode text not null default 'candidate_autoimprove',
  user_priority integer not null default 50,
  current_quality numeric not null default 0,
  target_quality numeric not null default 80,
  activity_score numeric not null default 0,
  release_blockers integer not null default 0,
  last_improved_at timestamptz,
  last_scanned_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.quality_autopilot_queue (
  id bigint generated by default as identity primary key,
  project_key text not null references public.quality_projects(project_key) on delete cascade,
  task_kind text not null,
  task_payload jsonb not null default '{}'::jsonb,
  status text not null default 'queued',
  priority numeric not null default 0,
  estimated_cpu_seconds integer not null default 60,
  estimated_paid_cost numeric not null default 0,
  requires_gpu boolean not null default false,
  attempts integer not null default 0,
  run_after timestamptz not null default now(),
  locked_by text,
  locked_at timestamptz,
  created_at timestamptz not null default now(),
  finished_at timestamptz,
  result jsonb
);
create index if not exists quality_autopilot_queue_claim_idx
  on public.quality_autopilot_queue(status, run_after, priority desc, id);

create table if not exists public.quality_improvement_memory (
  fingerprint text primary key,
  project_key text,
  action_kind text not null,
  system_area text,
  attempts integer not null default 0,
  successes integer not null default 0,
  failures integer not null default 0,
  cumulative_delta numeric not null default 0,
  average_delta numeric not null default 0,
  never_retry boolean not null default false,
  last_failure_reason text,
  last_outcome jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.quality_learning_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  project_key text,
  fingerprint text,
  action_kind text not null,
  system_area text,
  features jsonb not null default '{}'::jsonb,
  quality_before numeric,
  quality_after numeric,
  quality_delta numeric,
  passed_all_gates boolean,
  transferred_from_project text,
  outcome jsonb
);

create table if not exists public.quality_nightly_runs (
  run_id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running',
  projects_scanned integer not null default 0,
  jobs_enqueued integer not null default 0,
  jobs_completed integer not null default 0,
  cpu_seconds integer not null default 0,
  paid_cost numeric not null default 0,
  quality_delta numeric not null default 0,
  summary jsonb not null default '{}'::jsonb
);

alter table public.quality_projects enable row level security;
alter table public.quality_autopilot_queue enable row level security;
alter table public.quality_improvement_memory enable row level security;
alter table public.quality_learning_events enable row level security;
alter table public.quality_nightly_runs enable row level security;

create or replace function public.claim_quality_autopilot_job(p_worker text,p_max_cpu_seconds integer default 3600)
returns setof public.quality_autopilot_queue
language plpgsql security definer set search_path=public as $$
declare v_id bigint;
begin
  select id into v_id from public.quality_autopilot_queue
  where status='queued' and run_after<=now()
    and requires_gpu=false and estimated_paid_cost<=0
    and estimated_cpu_seconds<=greatest(1,p_max_cpu_seconds)
  order by priority desc,created_at asc
  for update skip locked limit 1;
  if v_id is null then return; end if;
  update public.quality_autopilot_queue
  set status='running',locked_by=p_worker,locked_at=now(),attempts=attempts+1
  where id=v_id;
  return query select * from public.quality_autopilot_queue where id=v_id;
end;
$$;
