const test=require('node:test');
const assert=require('node:assert/strict');
const Core=require('../shared/ink-glyph-world-core.js');
function rectMask(w,h,x0=2,y0=2,x1=w-2,y1=h-2){const a=new Uint8Array(w*h);for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)a[y*w+x]=255;return a}

test('cleanMask removes isolated noise',()=>{const a=new Uint8Array(25);a[12]=255;const out=Core.cleanMask(a,5,5,{threshold:.2,minNeighbors:1});assert.equal(out[12],0)});
test('cleanMask keeps connected stroke',()=>{const a=new Uint8Array(25);a[12]=255;a[13]=255;const out=Core.cleanMask(a,5,5,{threshold:.2,minNeighbors:1});assert.equal(out[12],255);assert.equal(out[13],255)});
test('distanceField grows inside stroke',()=>{const w=9,h=9,a=rectMask(w,h,1,1,8,8);const d=Core.distanceField(a,w,h);assert.ok(d[4*w+4]>d[1*w+1]);assert.equal(d[0],0)});
test('maskToWorld is deterministic, bounded and semantic',()=>{const w=48,h=48,a=rectMask(w,h,15,5,33,43);const one=Core.maskToWorld(a,w,h,{seed:'龍',preset:'city',maxCells:700,maxHeight:9,scatter:0});const two=Core.maskToWorld(a,w,h,{seed:'龍',preset:'city',maxCells:700,maxHeight:9,scatter:0});assert.deepEqual(one,two);assert.ok(one.cells.length>0&&one.cells.length<=750);assert.ok(one.cells.every(c=>c.height<=9&&c.height>0));assert.ok((one.roles.road||0)+(one.roles.wall||0)+(one.roles.building||0)+(one.roles.tower||0)>0)});
test('presets produce distinct deterministic worlds',()=>{const w=32,h=32,a=new Uint8Array(w*h).fill(255);const city=Core.maskToWorld(a,w,h,{seed:'x',preset:'city',maxCells:500,scatter:0});const mountain=Core.maskToWorld(a,w,h,{seed:'x',preset:'mountain',maxCells:500,scatter:0});assert.notDeepEqual(city.cells.map(c=>c.height),mountain.cells.map(c=>c.height))});
test('sampler caps dense masks',()=>{const w=128,h=128,a=new Uint8Array(w*h).fill(255);const r=Core.sampleMask(a,w,h,{maxCells:1000});assert.ok(r.sampled.length<=1100);assert.ok(r.step>1)});
test('recipe keys are stable and parameter-sensitive',()=>{const a=Core.recipeKey({font:'a',glyph:'龍',p:1}),b=Core.recipeKey({glyph:'龍',p:1,font:'a'}),c=Core.recipeKey({font:'a',glyph:'龍',p:2});assert.equal(a,b);assert.notEqual(a,c)});
test('stroke order uses real median ordering when data exists',()=>{const cells=[{sourceX:2,sourceY:8,kind:'stroke'},{sourceX:8,sourceY:2,kind:'stroke'}];const data={medians:[[[100,100],[200,100]],[[800,800],[900,800]]]};const r=Core.assignStrokeOrder(cells,data,10,10);assert.equal(r.source,'hanzi-writer-data');assert.equal(r.strokeCount,2);assert.notEqual(cells[0].strokeIndex,cells[1].strokeIndex);assert.ok(cells.every(c=>c.drawOrder>=0&&c.drawOrder<=1))});
test('procedural stroke order is a safe fallback',()=>{const cells=[{sourceX:1,sourceY:1,kind:'stroke'},{sourceX:1,sourceY:8,kind:'stroke'}];const r=Core.assignStrokeOrder(cells,null,10,10);assert.equal(r.source,'procedural');assert.ok(cells[1].drawOrder>cells[0].drawOrder)});
test('navigation graph and A* path are generated',()=>{const cells=[];for(let x=0;x<12;x++)cells.push({x,z:0,height:.3,role:'road',kind:'stroke'});const graph=Core.buildNavGraph({cells},{maxNavNodes:100});assert.ok(graph.nodeCount>=10);const path=Core.findPath(graph,0,graph.nodeCount-1);assert.ok(path.length>=2);assert.equal(path[0],0);assert.equal(path.at(-1),graph.nodeCount-1)});
test('LOD levels reduce instance counts while preserving towers',()=>{const cells=[];for(let i=0;i<1000;i++)cells.push({x:i%40,z:(i/40)|0,height:1,role:i%97===0?'tower':i%3===0?'road':'building',kind:'stroke'});const lod=Core.buildLodLevels({cells});assert.ok(lod.lowCount<lod.mediumCount);assert.ok(lod.mediumCount<lod.fullCount);for(let i=0;i<cells.length;i++)if(cells[i].role==='tower')assert.ok(lod.lowIndices.includes(i))});
test('quality score is normalized',()=>{const w=40,h=40,a=rectMask(w,h,6,6,34,34);const world=Core.maskToWorld(a,w,h,{seed:'quality',maxCells:700,scatter:0});assert.ok(world.quality.score>=0&&world.quality.score<=100);assert.equal(typeof world.navigation.componentCoverage,'number')});
test('quality tournament is deterministic and reports candidates',()=>{const w=44,h=44,a=rectMask(w,h,7,5,37,39),opts={seed:'tournament',preset:'city',maxCells:650,scatter:.02,qualityTournament:true,candidateCount:3};const a1=Core.tournamentMaskToWorld(a,w,h,opts),a2=Core.tournamentMaskToWorld(a,w,h,opts);assert.deepEqual(a1,a2);assert.equal(a1.tournament.candidateCount,3);assert.equal(a1.tournament.scores.length,3);assert.ok(a1.quality.score>=Math.min(...a1.tournament.scores.map(x=>x.score)))});

function makeMinimalGlb(){
 const json=Buffer.from(JSON.stringify({asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{name:'InkGlyphWorld'}]}),'utf8');
 const padded=Buffer.alloc((json.length+3)&~3,0x20);json.copy(padded);const total=12+8+padded.length,b=Buffer.alloc(total);b.writeUInt32LE(0x46546c67,0);b.writeUInt32LE(2,4);b.writeUInt32LE(total,8);b.writeUInt32LE(padded.length,12);b.writeUInt32LE(0x4e4f534a,16);padded.copy(b,20);return b;
}
test('GLB validator accepts a structurally valid GLB 2.0',()=>{const {validateBuffer}=require('../scripts/validate-ink-glyph-glb.cjs');const r=validateBuffer(makeMinimalGlb(),{minNodes:1});assert.equal(r.ok,true);assert.equal(r.nodes,1);assert.equal(r.assetVersion,'2.0')});
test('GLB validator rejects corrupted headers',()=>{const {validateBuffer}=require('../scripts/validate-ink-glyph-glb.cjs');const b=makeMinimalGlb();b.writeUInt32LE(0,0);const r=validateBuffer(b);assert.equal(r.ok,false);assert.ok(r.errors.some(e=>e.includes('magic')))});
test('topology grammar detects junction landmarks',()=>{const center={id:0,x:0,y:.3,z:0,cellIndex:0,edges:[1,2,3,4,5,6]},nodes=[center];for(let i=1;i<=6;i++)nodes.push({id:i,x:Math.cos(i)*2,y:.3,z:Math.sin(i)*2,cellIndex:i,edges:[0]});const world={cells:Array.from({length:7},(_,i)=>({x:i,z:0,height:.3,role:'road'})),navigation:{nodes,componentCount:1}};const t=Core.buildTopologyGrammar(world);assert.ok(t.junctionCount>=1);assert.ok(t.landmarks.some(x=>x.type==='plaza'));assert.ok(t.edgeCount>=6)});
test('topology grammar reports cycle rank',()=>{const nodes=[0,1,2,3].map(i=>({id:i,x:i%2,y:.3,z:(i/2)|0,cellIndex:i,edges:[]}));const edges=[[0,1],[1,3],[3,2],[2,0]];for(const[a,b]of edges){nodes[a].edges.push(b);nodes[b].edges.push(a)}const t=Core.buildTopologyGrammar({cells:nodes.map(n=>({x:n.x,z:n.z,height:.3,role:'road'})),navigation:{nodes,componentCount:1}});assert.equal(t.cycleRank,1)});
