#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const path=require('node:path');
const arg=(n,d=null)=>{const i=process.argv.indexOf(n);return i>=0?process.argv[i+1]:d};
const repo=path.resolve(arg('--repo',process.cwd())),patch=path.resolve(arg('--patch-root',path.join(__dirname,'..')));
const report={version:10,generatedAt:new Date().toISOString(),copied:[],preserved:[],updated:[],holds:[]};
const v10Files=['lib/quality/sbom-provenance-v10.js','lib/quality/migration-safety-v10.js','lib/quality/backup-restore-drill-v10.js','lib/quality/cross-region-probe-v10.js','lib/quality/quality-contract-instrumenter-v10.js','lib/quality/webgl-gpu-timer-v10.js','lib/quality/promotion-chain-v10.js','lib/quality/runtime-store-v10.js','shared/quality-webgl-gpu-timer-v10.js','scripts/quality-sbom-v10.js','scripts/quality-migration-safety-v10.js','scripts/quality-backup-restore-drill-v10.js','scripts/quality-contract-instrument-v10.js','scripts/quality-cross-region-probe-v10.js','scripts/quality-promotion-chain-v10.js','scripts/quality-persist-attestation-v10.js','scripts/quality-persist-drill-v10.js','supabase/migrations/20260823153040_quality_autopilot_v10_release_integrity.sql','scripts/quality-readiness-v10.js','test/quality-autopilot-v10.test.js','.github/workflows/quality-autopilot-v10-overlay.yml'];
for(const rel of v10Files){const src=path.join(patch,rel),dst=path.join(repo,rel);if(!fs.existsSync(src))continue;fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(src,dst);report.copied.push(rel);}
// Keep v9 protections if target lacks them; never overwrite a newer/current copy.
const support=['lib/quality/golden-adoption-lock-v9.js','lib/quality/golden-quarantine-v9.js','lib/quality/visual-baseline-quorum-v9.js','lib/quality/near-field-quality-gate-v9.js','lib/quality/slo-anomaly-v9.js','lib/quality/provider-capability-gate-v9.js','lib/quality/promotion-attestation-v9.js','lib/quality/runtime-store-v9.js','lib/quality/external-adapter-gate-v9.js','lib/quality/current-stack-bridge-v9.js','scripts/quality-golden-adoptions-v9.js','scripts/quality-provider-capability-gate-v9.js','scripts/quality-existing-stack-bridge-v9.js'];
for(const rel of support){const src=path.join(patch,rel),dst=path.join(repo,rel);if(fs.existsSync(dst)){report.preserved.push(rel);continue;}if(fs.existsSync(src)){fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(src,dst);report.copied.push(rel);}}
const pkgp=path.join(repo,'package.json');if(fs.existsSync(pkgp)){const pkg=JSON.parse(fs.readFileSync(pkgp,'utf8'));pkg.scripts=pkg.scripts||{};const scripts={'quality:v10:sbom':'node scripts/quality-sbom-v10.js . --require-lock','quality:v10:migrations':'node scripts/quality-migration-safety-v10.js .','quality:v10:backup-drill':'node scripts/quality-backup-restore-drill-v10.js .','quality:v10:contract:plan':'node scripts/quality-contract-instrument-v10.js .','quality:v10:contract:apply':'node scripts/quality-contract-instrument-v10.js . --apply','quality:v10:regions':'node scripts/quality-cross-region-probe-v10.js','quality:v10:chain':'node scripts/quality-promotion-chain-v10.js','quality:v10:chain:verify':'node scripts/quality-promotion-chain-v10.js --verify','quality:v10:persist-attestation':'node scripts/quality-persist-attestation-v10.js','quality:v10:persist-drill':'node scripts/quality-persist-drill-v10.js','quality:v10:readiness':'node scripts/quality-readiness-v10.js','quality:v10:test':'node --test test/quality-autopilot-v10.test.js'};for(const[k,v]of Object.entries(scripts)){if(!pkg.scripts[k]){pkg.scripts[k]=v;report.updated.push(`package.json:${k}`);}else report.preserved.push(`package.json:${k}`);}fs.writeFileSync(pkgp,JSON.stringify(pkg,null,2)+'\n');}
// Candidate-only safe mobile fix: preserve existing viewport values and append viewport-fit=cover if missing.
const mobileHtml=path.join(repo,'apps/ai3d-voxel-city/index.html');if(fs.existsSync(mobileHtml)){let html=fs.readFileSync(mobileHtml,'utf8');if(!/viewport-fit\s*=\s*cover/i.test(html)){const re=/<meta\s+name=["']viewport["']\s+content=["']([^"']*)["'][^>]*>/i;if(re.test(html)){html=html.replace(re,(m,c)=>m.replace(c,c+(c.trim().endsWith(',')?'':',')+'viewport-fit=cover'));fs.writeFileSync(mobileHtml,html);report.updated.push('apps/ai3d-voxel-city/index.html:viewport-fit=cover');}}}
// Contract instrumentation is deliberately PLAN-only during install. Desktop AI may apply only after review.
try{const {instrumentHtml}=require('./../lib/quality/quality-contract-instrumenter-v10');const apps=path.join(repo,'apps');if(fs.existsSync(apps)){let candidates=0;for(const name of fs.readdirSync(apps)){const p=path.join(apps,name,'index.html');if(fs.existsSync(p)&&instrumentHtml(fs.readFileSync(p,'utf8')).changed)candidates++;}if(candidates)report.holds.push({id:'quality-contract-instrumentation',candidates,action:'run quality:v10:contract:apply in candidate branch after review'});}}catch{}
fs.mkdirSync(path.join(repo,'data/quality-autopilot'),{recursive:true});fs.writeFileSync(path.join(repo,'data/quality-autopilot/v10-merge-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
