'use strict';const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {buildGoldenAdoptions,verifyGoldenAdoptions}=require('../lib/quality/golden-adoption-lock-v9');const {evaluateGoldenQuarantine}=require('../lib/quality/golden-quarantine-v9');const {stableVisualBaselineQuorum}=require('../lib/quality/visual-baseline-quorum-v9');const {gateNearFieldQuality}=require('../lib/quality/near-field-quality-gate-v9');const {detectAnomalies}=require('../lib/quality/slo-anomaly-v9');const {evaluateCapabilities}=require('../lib/quality/provider-capability-gate-v9');const {createAttestation,verifyAttestation}=require('../lib/quality/promotion-attestation-v9');const {inspectCurrentStack}=require('../lib/quality/current-stack-bridge-v9');
function tmp(){return fs.mkdtempSync(path.join(os.tmpdir(),'qa-v9-'));}
test('Golden adoption lock hashes canonical file and detects exact adoption',()=>{const r=tmp();fs.mkdirSync(path.join(r,'data'),{recursive:true});fs.mkdirSync(path.join(r,'apps/a'),{recursive:true});fs.mkdirSync(path.join(r,'shared'),{recursive:true});fs.writeFileSync(path.join(r,'shared/golden.js'),'golden');fs.writeFileSync(path.join(r,'apps/a/golden.js'),'golden');fs.writeFileSync(path.join(r,'data/golden-components.json'),JSON.stringify({components:[{id:'move',status:'golden',canonical:'shared/golden.js'}]}));const l=buildGoldenAdoptions(r);assert.equal(l.components[0].verified,true);assert.deepEqual(l.components[0].adoptions,['apps/a/golden.js']);assert.equal(verifyGoldenAdoptions(r,l).ok,true);});
test('Golden drift triggers quarantine and propagation freeze',()=>{const r=tmp();fs.mkdirSync(path.join(r,'data'),{recursive:true});fs.writeFileSync(path.join(r,'golden.js'),'A');fs.writeFileSync(path.join(r,'data/golden-components.json'),JSON.stringify({components:[{id:'x',status:'golden',canonical:'golden.js'}]}));const l=buildGoldenAdoptions(r);fs.writeFileSync(path.join(r,'golden.js'),'B');const v=verifyGoldenAdoptions(r,l),q=evaluateGoldenQuarantine(v,l);assert.equal(v.ok,false);assert.equal(q.quarantined,true);assert.equal(q.action,'FREEZE_GOLDEN_PROPAGATION');});
test('stable visual quorum produces automated candidate but never claims user approval',()=>{const c=[0,1,2].map(i=>({width:1200,height:800,detail:100+i*.1,contrast:40+i*.02,exposure:.5+i*.0005,release:'prod'}));const r=stableVisualBaselineQuorum(c);assert.equal(r.ok,true);assert.equal(r.userApproved,false);assert.equal(r.status,'STABLE_AUTOMATED_BASELINE_CANDIDATE');});
test('visual quorum holds unstable captures',()=>{const r=stableVisualBaselineQuorum([{width:1200,height:800,detail:100,contrast:40,exposure:.5},{width:1200,height:800,detail:60,contrast:40,exposure:.5},{width:1200,height:800,detail:100,contrast:40,exposure:.5}]);assert.equal(r.ok,false);});
test('near-field gate rejects local graphics degradation while allowing distant optimization',()=>{const b={nearDetail:100,nearTextureResolution:2048,nearMeshDensity:1,nearShadowQuality:1},a={nearDetail:100,nearTextureResolution:2048,nearMeshDensity:1,nearShadowQuality:1,farLodAggressiveness:2};assert.equal(gateNearFieldQuality(b,a).ok,true);a.nearDetail=90;assert.equal(gateNearFieldQuality(b,a).ok,false);});
test('SLO anomaly detector rolls back large error-rate regression',()=>{const b={errorRate:[.01,.011,.009,.01,.012,.01,.009]},c={errorRate:.08};const r=detectAnomalies(b,c,{relativeLimit:.2});assert.equal(r.ok,false);assert.equal(r.decision,'ROLLBACK');});
test('provider gate never accepts simulated or unverified provider',()=>{const req=['gpu','mobile'];const p=[{name:'fake',verified:true,simulated:true,capabilities:['gpu','mobile']},{name:'phone',verified:true,capabilities:['mobile']}];const r=evaluateCapabilities(req,p);assert.equal(r.ok,false);assert.equal(r.holds[0].capability,'gpu');});
test('provider gate passes verified real capabilities',()=>{const r=evaluateCapabilities(['gpu','mobile'],[{name:'real',verified:true,capabilities:['gpu','mobile']}]);assert.equal(r.ok,true);});
test('promotion attestation is tamper evident and optionally signed',()=>{const a=createAttestation({commitSha:'abc',evidence:[{name:'gate',value:{ok:true}}]},'secret');assert.equal(verifyAttestation(a,'secret').ok,true);a.commitSha='evil';assert.equal(verifyAttestation(a,'secret').ok,false);});
test('current stack bridge recognizes advanced master scripts without mutating them',()=>{const r=tmp();fs.writeFileSync(path.join(r,'package.json'),JSON.stringify({scripts:{'release:gate':'x','quality:durable-cycle':'y','quality:perceptual':'z','quality:visual-critic':'v'}}));fs.writeFileSync(path.join(r,'QUALITY_MASTER_REPORT.json'),JSON.stringify({overallPercent:98}));const s=inspectCurrentStack(r);assert.equal(s.capabilities.releaseGate,true);assert.equal(s.capabilities.durableCycle,true);assert.equal(s.currentMasterPercent,98);assert.equal(s.preserveExisting,true);});
test('runtime store returns HOLD when server credentials are absent',async()=>{const su='SUPABASE_URL',sk='SUPABASE_'+'SECRET_KEY',sr='SUPABASE_'+'SERVICE_ROLE_KEY';const oldU=process.env[su],oldK=process.env[sk],oldS=process.env[sr];delete process.env[su];delete process.env[sk];delete process.env[sr];const {claimAutopilotLease}=require('../lib/quality/runtime-store-v9');const r=await claimAutopilotLease('x','y',1);assert.equal(r.ok,false);assert.equal(r.status,'HOLD');if(oldU)process.env[su]=oldU;if(oldK)process.env[sk]=oldK;if(oldS)process.env[sr]=oldS;});
test('external adapter is HOLD rather than fake PASS without endpoints',async()=>{const {probeAdapter}=require('../lib/quality/external-adapter-gate-v9');const r=await probeAdapter('x',{});assert.equal(r.ok,false);assert.equal(r.status,'HOLD');});
test('promotion attestation requires secret when marked signed',()=>{const a=createAttestation({commitSha:'abc',evidence:[]},'secret');assert.equal(verifyAttestation(a,'').ok,false);assert.equal(verifyAttestation(a,'').reason,'secret-required');});
