#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto');
const {ROOT,STATE_DIR,ensureDir,readJSON,writeJSON,commandExists,nowIso}=require('./integration-utils.cjs');
const policy=readJSON(path.join(ROOT,'data/distributed-cas-policy.json'),{}),casRoot=path.join(STATE_DIR,'cas','sha256');ensureDir(casRoot);const h=b=>crypto.createHash('sha256').update(b).digest('hex'),obj=hash=>path.join(casRoot,hash.slice(0,2),hash.slice(2));
function parsePeers(){try{const x=JSON.parse(process.env[policy.peerEnv||'WORLD_SERVER_CAS_PEERS_JSON']||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function putLocal(buf,expected=null){const digest=h(buf);if(expected&&digest!==expected)throw new Error('digest mismatch');const f=obj(digest);ensureDir(path.dirname(f));if(!fs.existsSync(f))fs.writeFileSync(f,buf);return digest}
function getLocal(hash){const f=obj(hash);if(!fs.existsSync(f))return null;const b=fs.readFileSync(f);if(h(b)!==hash)throw new Error('local CAS corruption');return b}
function server({host='127.0.0.1',port=0,token=process.env[policy.tokenEnv||'WORLD_SERVER_CAS_TOKEN']||''}={}){if(!['127.0.0.1','::1','localhost'].includes(host)&&policy.requireTokenForNonLoopbackServe&& !token)throw new Error('token required for non-loopback CAS serve');return http.createServer((req,res)=>{const m=req.url?.match(/^\/cas\/sha256\/([a-f0-9]{64})$/);if(!m){res.statusCode=404;return res.end('not found')}if(token&&req.headers.authorization!==`Bearer ${token}`){res.statusCode=401;return res.end('unauthorized')}const hash=m[1];if(req.method==='GET'){const b=getLocal(hash);if(!b){res.statusCode=404;return res.end('missing')}res.setHeader('content-type','application/octet-stream');res.end(b)}else if(req.method==='PUT'){const chunks=[];req.on('data',c=>chunks.push(c));req.on('end',()=>{try{const b=Buffer.concat(chunks);putLocal(b,hash);res.statusCode=201;res.end('stored')}catch(e){res.statusCode=400;res.end(e.message)}})}else{res.statusCode=405;res.end('method')}}).listen(port,host)}
async function request(base,method,hash,buf,token=''){const u=new URL(`/cas/sha256/${hash}`,base);const r=await fetch(u,{method,body:buf,headers:token?{authorization:`Bearer ${token}`}:{}});if(!r.ok)throw new Error(`${method} ${u} -> ${r.status}`);return method==='GET'?Buffer.from(await r.arrayBuffer()):null}
async function probePeer(peer){try{const token=peer.tokenEnv?process.env[peer.tokenEnv]||'':process.env[policy.tokenEnv||'WORLD_SERVER_CAS_TOKEN']||'';const r=await fetch(new URL('/health',peer.url),{headers:token?{authorization:`Bearer ${token}`}:{},signal:AbortSignal.timeout(2500)});return{url:peer.url,reachable:r.ok}}catch(e){return{url:peer.url,reachable:false,error:e.message}}}
async function selftest(){const s=server({port:0}),addr=await new Promise(r=>s.on('listening',()=>r(s.address())));const buf=Buffer.from('distributed-cas-selftest-'+Date.now()),digest=h(buf),base=`http://127.0.0.1:${addr.port}`;try{await request(base,'PUT',digest,buf);const got=await request(base,'GET',digest);const pass=h(got)===digest;return{pass,digest,protocol:'http-put-get-sha256'}}finally{await new Promise(r=>s.close(r))}}
async function health(){const peers=parsePeers(),probes=[];for(const peer of peers)probes.push(await probePeer(peer));const st=await selftest(),index=readJSON(path.join(ROOT,'CAS_INDEX.json'),{});const report={schemaVersion:'7.2.0',generatedAt:nowIso(),pass:st.pass&&Boolean(index.root||index.merkleRoot||index.entries),protocol:'world-server-cas-http-v1',localCasReady:true,loopbackProtocolSelftest:st,configuredPeers:peers.length,reachablePeers:probes.filter(x=>x.reachable).length,peerCoveragePercent:peers.length?Math.round(probes.filter(x=>x.reachable).length/peers.length*100):0,remotePeerRequiredForRelease:Boolean(policy.remotePeerRequiredForRelease),externalBlockers:peers.length?probes.filter(x=>!x.reachable).map(x=>`cas-peer:${x.url}`):['no-remote-cas-peer-configured'],probes};writeJSON(path.join(ROOT,'DISTRIBUTED_CAS_STATUS.json'),report);console.log(`[DISTRIBUTED_CAS] ${report.pass?'PASS':'FAIL'} peers=${report.reachablePeers}/${report.configuredPeers}`);if(!report.pass)process.exitCode=2}
const cmd=process.argv[2]||'health';if(cmd==='serve'){const host=process.argv[3]||'127.0.0.1',port=Number(process.argv[4]||8789),s=server({host,port});s.on('listening',()=>console.log(`[DISTRIBUTED_CAS] serving http://${host}:${port}`))}else health().catch(e=>{console.error('[DISTRIBUTED_CAS] FAIL',e.stack||e.message);process.exit(2)});module.exports={putLocal,getLocal,server,selftest};
