import * as THREE from 'three';
const tmpBox=new THREE.Box3(),tmpCenter=new THREE.Vector3(),tmpSize=new THREE.Vector3();
export class GpuOcclusionManager{
 constructor({renderer,scene,camera,root,manifest,player,atmosphere}){this.renderer=renderer;this.scene=scene;this.camera=camera;this.root=root;this.player=player;this.atmosphere=atmosphere;const c=manifest.graphics?.gpuVisibility||{};this.enabled=c.enabled!==false;this.nearRadius=c.nearBypassRadius??42;this.maxQueries=c.maxQueriesPerFrame??6;this.confirmFrames=c.occludedConfirmFrames??3;this.gl=renderer.getContext();this.supported=this.enabled&&renderer.capabilities.isWebGL2&&!!this.gl?.createQuery;this.proxyScene=new THREE.Scene();this.geom=new THREE.BoxGeometry(1,1,1);this.mat=new THREE.MeshBasicMaterial({colorWrite:false,depthWrite:false,depthTest:true,side:THREE.DoubleSide});this.proxy=new THREE.Mesh(this.geom,this.mat);this.proxyScene.add(this.proxy);this.items=[];this.cursor=0;this.queries=0;this.hidden=0;this._scan();}
 _scan(){if(!this.supported)return;this.root?.traverse?.(o=>{if(!o.isMesh||o.name==='__WORLD_COLLIDER__'||o.isSkinnedMesh||o.userData?.dynamic||o.userData?.qualityNoOcclusion)return;if(!o.geometry?.boundingBox)o.geometry?.computeBoundingBox?.();if(!o.geometry?.boundingBox)return;this.items.push({o,q:null,pending:false,occ:0,visible:true});});}
 _worldBox(o){tmpBox.copy(o.geometry.boundingBox).applyMatrix4(o.matrixWorld);return tmpBox;}
 poll(){if(!this.supported)return;for(const it of this.items){if(!it.pending||!it.q)continue;if(this.gl.getQueryParameter(it.q,this.gl.QUERY_RESULT_AVAILABLE)){const visible=!!this.gl.getQueryParameter(it.q,this.gl.QUERY_RESULT);it.pending=false;if(visible){it.occ=0;if(!it.o.visible){it.o.visible=true;this.hidden=Math.max(0,this.hidden-1)}}else{it.occ++;if(it.occ>=this.confirmFrames&&it.o.visible){it.o.visible=false;this.hidden++;}}}}}
 issue(){if(!this.supported||!this.player?.position)return;const gl=this.gl;let issued=0,visited=0;const oldAuto=this.renderer.autoClear;this.renderer.autoClear=false;try{while(issued<this.maxQueries&&visited<this.items.length){const it=this.items[this.cursor++%this.items.length];visited++;const box=this._worldBox(it.o),center=box.getCenter(tmpCenter),d=center.distanceTo(this.player.position);if(d<this.nearRadius){it.occ=0;if(!it.o.visible){it.o.visible=true;this.hidden=Math.max(0,this.hidden-1)}continue}if(it.pending)continue;box.getSize(tmpSize);this.proxy.position.copy(center);this.proxy.scale.copy(tmpSize);this.proxy.updateMatrixWorld(true);it.q=it.q||gl.createQuery();gl.beginQuery(gl.ANY_SAMPLES_PASSED_CONSERVATIVE,it.q);this.renderer.render(this.proxyScene,this.camera);gl.endQuery(gl.ANY_SAMPLES_PASSED_CONSERVATIVE);it.pending=true;issued++;this.queries++;}}finally{this.renderer.autoClear=oldAuto}}
 update(){this.poll();}
 afterRender(){this.issue();}
 report(){return{enabled:this.enabled,supported:this.supported,mode:'webgl2-conservative-gpu-occlusion-v1',candidates:this.items.length,queries:this.queries,hidden:this.hidden,nearBypassRadius:this.nearRadius,nearFieldNeverOcclusionCulled:true,sourceQualityReduced:false};}
 dispose(){for(const i of this.items)if(i.q)this.gl?.deleteQuery?.(i.q);this.geom.dispose();this.mat.dispose();}
}
