#!/usr/bin/env node
'use strict';
const path=require('path');const {ROOT,readJSON,writeJSON,nowIso}=require('./integration-utils.cjs');
const report=readJSON(path.join(ROOT,'HONEST_100_FUNCTION_REPORT.json'),{}),baseDefs=readJSON(path.join(ROOT,'data/function-contracts.json'),{functions:[]}),gen=readJSON(path.join(ROOT,'data/generated-legacy-function-contracts.json'),{contracts:[]}),defs={functions:[...(baseDefs.functions||[]),...(gen.contracts||[])]},reg=readJSON(path.join(ROOT,'data/system-capability-registry.json'),{capabilities:[]});
const cert=new Set((report.functions||[]).filter(x=>x.status==='CERTIFIED_100').map(x=>x.id)),capToFn=new Map();for(const f of defs.functions||[])for(const c of f.coversCapabilities||[])capToFn.set(c,f.id);
const rows=[];for(const sys of reg.capabilities||[])for(const cap of sys.provides||[]){const fn=capToFn.get(cap)||null;rows.push({capability:cap,systemId:sys.id,owner:sys.owner,contractId:fn,status:fn&&cert.has(fn)?'CERTIFIED_100':'UNVERIFIED'})}
const integrationRows=rows.filter(x=>x.owner==='SYSTEM_INTEGRATION_LAYER_V7'),pct=xs=>xs.length?Math.round(100*xs.filter(x=>x.status==='CERTIFIED_100').length/xs.length):100;
const candidates=rows.filter(x=>x.status!=='CERTIFIED_100').map(x=>({capability:x.capability,owner:x.owner,systemId:x.systemId,status:'NEEDS_EXPLICIT_EVIDENCE_CONTRACT',rule:'Do not auto-certify by name similarity. Add scoped source paths + integration/regression/runtime evidence first.'}));
const out={schemaVersion:'7.5.0',generatedAt:nowIso(),pass:true,globalCapabilityCertificationPercent:pct(rows),integrationOwnedCapabilityCertificationPercent:pct(integrationRows),certifiedCapabilities:rows.filter(x=>x.status==='CERTIFIED_100').length,totalCapabilities:rows.length,integrationOwnedCertified:integrationRows.filter(x=>x.status==='CERTIFIED_100').length,integrationOwnedTotal:integrationRows.length,rows,candidates};writeJSON(path.join(ROOT,'FUNCTION_CERTIFICATION_COVERAGE.json'),out);writeJSON(path.join(ROOT,'FUNCTION_CONTRACT_CANDIDATES.json'),{schemaVersion:'7.5.0',generatedAt:nowIso(),candidates});console.log(`[FUNCTION_COVERAGE] integration=${out.integrationOwnedCapabilityCertificationPercent}% global=${out.globalCapabilityCertificationPercent}% candidates=${candidates.length}`);
