'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {enhanceVoxelWorld,frontProjection,sameFrontProjection}=require('../lib/world-quality-voxel-enhancer');
const {semanticDetailIndex}=require('../lib/world-quality-semantic-detail');
const {profileColor,buildMaterialProfiles}=require('../lib/world-quality-material-profiler');
const {synthesizePbrProfiles,estimateTextureBudget}=require('../lib/world-quality-pbr-synthesizer');
const {computeReadiness,weightedScore}=require('../scripts/world-quality-analyzer');

function sampleWorld(){const v=[];for(let x=0;x<16;x++)v.push([x,0,0,0]);for(let y=1;y<11;y++)for(let x=1;x<15;x++){const window=(y===3||y===6)&&(x===3||x===6||x===9||x===12),c=window?1:0,z=4-(x%5===0?1:0);v.push([x,y,z,c],[x,y,z-1,c])}for(let y=11;y<15;y++)for(let x=6+(y-11);x<=9-(y-11);x++)v.push([x,y,4,2]);return{source:{width:16,height:15},palette:[0x40363a,0xffb45f,0x5a2635,0x222222],voxels:v,performance:{},stats:{logicalVoxels:v.length}}}

test('V4 semantic detail index detects architectural motifs',()=>{const w=sampleWorld(),idx=semanticDetailIndex(w.voxels,w.palette);assert.ok(idx.stats.cells>100);assert.ok(idx.stats.roof>0);assert.ok(idx.stats.windowLike>0);assert.ok(idx.stats.verticalEdge>0);assert.ok(idx.stats.highSaliency>0)});
test('V4 deterministic enhancement preserves exact front projection',()=>{const a=sampleWorld(),b=sampleWorld(),before=[...frontProjection(a.voxels).entries()],opt={seed:42,policy:{maxAddedVoxelRatio:.45,maxAddedVoxelAbsolute:9999,edgeDensity:1,edgeThreshold:.02}};enhanceVoxelWorld(a,opt);enhanceVoxelWorld(b,opt);assert.deepEqual(a.voxels,b.voxels);assert.deepEqual([...frontProjection(a.voxels).entries()],before);assert.equal(a.qualityAutopilot.version,'4.0.0');assert.equal(a.qualityAutopilot.frontProjectionPreserved,true);assert.ok(a.materialProfiles.length===a.palette.length);assert.ok(a.pbrProfiles.length===a.palette.length)});
test('V4 geometry budget remains strict',()=>{const w=sampleWorld(),n=w.voxels.length;enhanceVoxelWorld(w,{seed:1,policy:{maxAddedVoxelRatio:.06,maxAddedVoxelAbsolute:9999,edgeDensity:1,edgeThreshold:.02}});assert.ok(w.voxels.length-n<=Math.floor(n*.06));assert.equal(sameFrontProjection(sampleWorld().voxels,w.voxels),true)});
test('material profiler classifies emissive and metal-like colors',()=>{const warm=profileColor(0xffb45f),dark=profileColor(0x222222),p=buildMaterialProfiles([0xffb45f,0x222222]);assert.equal(warm.materialClass,'emissive');assert.equal(dark.materialClass,'metal');assert.ok(warm.emissiveIntensity>0);assert.ok(dark.metalness>.5);assert.equal(p.length,2)});
test('V4 procedural PBR synthesis is deterministic and budgeted',()=>{const base=buildMaterialProfiles([0xffb45f,0x222222,0x40363a]),a=synthesizePbrProfiles(base,{seed:7}),b=synthesizePbrProfiles(base,{seed:7});assert.deepEqual(a,b);assert.equal(a.length,3);assert.ok(a.every(x=>x.candidateId&&x.destructiveTextureBake===false));const safe=estimateTextureBudget(a,'SAFE'),ultra=estimateTextureBudget(a,'ULTRA');assert.ok(ultra.virtualMegapixels>safe.virtualMegapixels)});
test('runtime V4 exposes pressure, texture and occlusion hooks',()=>{const src=fs.readFileSync(path.join(__dirname,'../shared/world-quality-autopilot.js'),'utf8');for(const token of["version:'4.0.0'",'PerformanceObserver','deviceMemory','hardwareConcurrency','textureBudgetScale','occlusionHz','thermalProxy','registerMaterialAdapter','registerSceneBudgetAdapter'])assert.ok(src.includes(token),token)});
test('V4 retarget contract contains root motion and two-hand constraints',()=>{const src=fs.readFileSync(path.join(__dirname,'../scripts/world-retarget-contract.js'),'utf8');assert.ok(src.includes('rootMotionDirection'));assert.ok(src.includes('twoHandWeapon'));assert.ok(src.includes('LeftFoot'));assert.ok(src.includes('RightHand'))});
test('V4 visibility optimizer is conservative',()=>{const src=fs.readFileSync(path.join(__dirname,'../scripts/world-visibility-optimizer.js'),'utf8');for(const token of['neverCullNearPlayer','neverCullHeroLandmarkByHeuristic','temporalHysteresis','frustumFallback'])assert.ok(src.includes(token))});
test('V4 candidate lab is prediction only before promotion',()=>{const src=fs.readFileSync(path.join(__dirname,'../scripts/world-candidate-lab.js'),'utf8');assert.ok(src.includes('mutationAllowed:false'));assert.ok(src.includes('winnerOnly:true'));assert.ok(src.includes('candidate tournament'))});
test('V4 feedback learner cannot mutate directly',()=>{const src=fs.readFileSync(path.join(__dirname,'../scripts/world-feedback-learner.js'),'utf8');assert.ok(src.includes('automaticMutation:false'));assert.ok(src.includes('candidate tournament'))});
test('baseline promotion remains explicit and cannot self-approve',()=>{const src=fs.readFileSync(path.join(__dirname,'../scripts/world-visual-baseline-promote.js'),'utf8');assert.ok(src.includes('--approve'));assert.ok(src.includes('Refusing baseline mutation on master/main'))});
test('weighted readiness remains evidence based',()=>{const d={detail:[{weight:3,ok:true},{weight:1,ok:false}],graphics:[{weight:1,ok:true}]};assert.equal(weightedScore(d.detail),75);assert.equal(computeReadiness(d,{detail:.5,graphics:.5}).overall,88)});
