'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {buildSbom,evaluateSupplyChain}=require('../lib/quality/sbom-provenance-v10');
const {analyzeMigration}=require('../lib/quality/migration-safety-v10');
const {snapshotFiles,restoreSnapshot}=require('../lib/quality/backup-restore-drill-v10');
const {runCrossRegionProbe}=require('../lib/quality/cross-region-probe-v10');
const {instrumentHtml}=require('../lib/quality/quality-contract-instrumenter-v10');
const {createGpuTimer}=require('../lib/quality/webgl-gpu-timer-v10');
const {appendPromotionRecord,verifyPromotionChain}=require('../lib/quality/promotion-chain-v10');
function tmp(){return fs.mkdtempSync(path.join(os.tmpdir(),'qa-v10-'));}

test('SBOM hashes package and lock and passes pinned dependency',()=>{const r=tmp();fs.writeFileSync(path.join(r,'package.json'),JSON.stringify({name:'x',version:'1.0.0',dependencies:{a:'1.2.3'}}));fs.writeFileSync(path.join(r,'package-lock.json'),'{}');const s=buildSbom(r),g=evaluateSupplyChain(s,{requireLock:true,requirePinned:true});assert.equal(s.ok,true);assert.equal(s.components[0].pinned,true);assert.equal(g.ok,true);});
test('SBOM strict gate holds unpinned dependency',()=>{const r=tmp();fs.writeFileSync(path.join(r,'package.json'),JSON.stringify({dependencies:{a:'^1.2.3'}}));fs.writeFileSync(path.join(r,'package-lock.json'),'{}');const g=evaluateSupplyChain(buildSbom(r),{requireLock:true,requirePinned:true});assert.equal(g.ok,false);assert.equal(g.findings[0].id,'unpinned-dependencies');});
test('migration safety blocks DROP TABLE and requires backup',()=>{const r=analyzeMigration('drop table users;');assert.equal(r.ok,false);assert.equal(r.requiresBackup,true);});
test('migration safety blocks SECURITY DEFINER without execute revoke',()=>{const r=analyzeMigration('create function x() returns void language sql security definer as $$ select 1 $$;');assert.equal(r.ok,false);assert.equal(r.findings.some(x=>x.id==='security-definer-execute-not-revoked'),true);});
test('migration safety allows definer when execute is explicitly revoked',()=>{const r=analyzeMigration('create function x() returns void language sql security definer as $$ select 1 $$; revoke execute on function x() from public, anon, authenticated;');assert.equal(r.ok,true);});
test('backup restore drill reproduces exact hashes',()=>{const r=tmp(),d=tmp();fs.mkdirSync(path.join(r,'data'),{recursive:true});fs.writeFileSync(path.join(r,'data/a.json'),'hello');const s=snapshotFiles(r,['data/a.json']);const v=restoreSnapshot(s,d);assert.equal(v.ok,true);assert.equal(fs.readFileSync(path.join(d,'data/a.json'),'utf8'),'hello');});
test('contract instrumenter is safe and idempotent',()=>{const a=instrumentHtml('<html><body>x</body></html>');assert.equal(a.changed,true);assert.match(a.html,/__QUALITY_AUTOPILOT_CONTRACT__/);const b=instrumentHtml(a.html);assert.equal(b.changed,false);});
test('GPU timer reports unavailable without extension',()=>{const g={getExtension(){return null;}};assert.equal(createGpuTimer(g).available,false);});
test('GPU timer converts nanoseconds to milliseconds',()=>{const ext={TIME_ELAPSED_EXT:1,GPU_DISJOINT_EXT:2};const g={QUERY_RESULT_AVAILABLE:3,QUERY_RESULT:4,getExtension(){return ext;},createQuery(){return{};},beginQuery(){},endQuery(){},getQueryParameter(q,k){return k===3?true:2500000;},getParameter(){return false;}};const t=createGpuTimer(g),q=t.begin();t.end();const r=t.poll(q);assert.equal(r.ready,true);assert.equal(r.gpuMs,2.5);});
test('promotion chain detects tampering and broken links',()=>{const a=appendPromotionRecord(null,{commitSha:'a',evidenceHash:'1',decision:'PASS',createdAt:'2026-01-01T00:00:00Z'},'s');const b=appendPromotionRecord(a.recordHash,{commitSha:'b',evidenceHash:'2',decision:'PASS',createdAt:'2026-01-01T00:01:00Z'},'s');assert.equal(verifyPromotionChain([a,b],'s').ok,true);b.commitSha='evil';assert.equal(verifyPromotionChain([a,b],'s').ok,false);});
test('cross-region probe holds fewer than three real regions',async()=>{const r=await runCrossRegionProbe('https://target',[{region:'us',url:'https://p',verified:true},{region:'eu',url:'https://p2',verified:true}],{minRegions:3});assert.equal(r.ok,false);assert.equal(r.reason,'insufficient-distinct-real-regions');});
test('cross-region probe requires verified successful responses',async()=>{const old=global.fetch;global.fetch=async()=>({ok:true,status:200,json:async()=>({ok:true,latencyMs:10})});try{const p=['us','eu','ap'].map((region,i)=>({region,url:`https://p${i}.example`,verified:true}));const r=await runCrossRegionProbe('https://target.example',p,{minRegions:3});assert.equal(r.ok,true);assert.equal(r.regions.length,3);}finally{global.fetch=old;}});

test('v10 runtime store refuses to fake persistence without server credentials',async()=>{const su='SUPABASE_URL',sk='SUPABASE_SECRET_KEY',sr='SUPABASE_SERVICE_ROLE_KEY';const old=[process.env[su],process.env[sk],process.env[sr]];delete process.env[su];delete process.env[sk];delete process.env[sr];const {persistPromotionAttestation}=require('../lib/quality/runtime-store-v10');const r=await persistPromotionAttestation({});assert.equal(r.ok,false);assert.equal(r.status,'HOLD');if(old[0])process.env[su]=old[0];if(old[1])process.env[sk]=old[1];if(old[2])process.env[sr]=old[2];});
