#!/usr/bin/env node
'use strict';
const path=require('path');
const {ROOT,readJSON,writeJSON,gitBranch,gitCommit,gitStatusFiles,commandExists,run,nowIso}=require('./integration-utils.cjs');
function hasReleaseWire(){const p=readJSON(path.join(ROOT,'package.json'),{});return String(p.scripts?.['release:gate']||'').includes('integration:verify')}
function provenanceValid(){const p=readJSON(path.join(ROOT,'SLSA_PROVENANCE.intoto.json'));return Boolean(p&&p._type==='https://in-toto.io/Statement/v1'&&p.predicateType==='https://slsa.dev/provenance/v1'&&Array.isArray(p.subject)&&p.subject.length&&p.predicate?.buildDefinition&&p.predicate?.runDetails?.builder?.id)}
function pass(file,key='pass'){return readJSON(path.join(ROOT,file),{})?.[key]===true}
function gpuMandatory(){const p=readJSON(path.join(ROOT,'package.json'),{});const s=JSON.stringify(p.scripts||{}).toLowerCase();return process.env.AI3D_GPU_REQUIRED==='true'||s.includes('--require-gpu')||s.includes('gpu_required=true')}
function lastWriterWins(){const pol=readJSON(path.join(ROOT,'data','system-conflict-policy.json'),{});return Boolean(pol.policy&&pol.policy!=='semantic-merge-never-last-writer-wins')}
function unverified100(){const q=readJSON(path.join(ROOT,'QUALITY_MASTER_REPORT.json'),{}),prod=readJSON(path.join(ROOT,'PRODUCTION_100_TRUTH_REPORT.json'),{});const claim=Number(q.overallPercent)===100||Number(q.currentOverall)===100;return Boolean(claim&&!prod.production100Certified)}
function buildInput(){return {schemaVersion:'7.2.0',generatedAt:nowIso(),branch:gitBranch(),commit:gitCommit(),changed_files:gitStatusFiles(),release_gate_wired:hasReleaseWire(),dr_verified:pass('DISASTER_RECOVERY_VERIFY_REPORT.json'),provenance_valid:provenanceValid(),integration_gate_pass:pass('SYSTEM_INTEGRATION_REPORT.json'),project_directives_pass:pass('PROJECT_DIRECTIVE_REPORT.json'),technology_lock_pass:pass('TECHNOLOGY_LOCK_REPORT.json'),graphics_ratchet_pass:pass('GRAPHICS_REGRESSION_GUARD_REPORT.json'),audio_variation_pass:pass('AUDIO_VARIATION_REPORT.json'),gameplay_contract_pass:pass('GAMEPLAY_PHYSICAL_CONTRACT_REPORT.json'),desktop_ai_report_pass:pass('DESKTOP_AI_REPORT_VALIDATION.json'),asset_batching_pass:pass('ASSET_INGESTION_PLAN.json'),sbom_pass:pass('SBOM_STATUS.json'),update_trust_pass:pass('UPDATE_TRUST_STATUS.json'),feature_flags_pass:pass('FEATURE_FLAG_STATUS.json'),config_contract_pass:pass('CONFIG_CONTRACT_STATUS.json'),adapter_sandbox_pass:pass('ADAPTER_SANDBOX_STATUS.json'),reproducible_build_pass:pass('REPRODUCIBLE_BUILD_STATUS.json'),gpu_mandatory:gpuMandatory(),last_writer_wins:lastWriterWins(),unverified_100_claim:unverified100(),cpu_first:true}}
function jsDecision(i){const deny=[];if(!i.release_gate_wired)deny.push('release gate is not wired to integration:verify');if(!i.dr_verified)deny.push('disaster-recovery snapshot is missing or unverified');if(!i.provenance_valid)deny.push('SLSA/in-toto provenance is missing or invalid');if(!i.integration_gate_pass)deny.push('system integration gate failed');if(!i.project_directives_pass)deny.push('project directive constitution gate failed');if(!i.technology_lock_pass)deny.push('user-mandated technology lock failed');if(!i.graphics_ratchet_pass)deny.push('graphics quality ratchet failed');if(!i.audio_variation_pass)deny.push('audio variation gate failed');if(!i.gameplay_contract_pass)deny.push('gameplay physical contract failed');if(!i.desktop_ai_report_pass)deny.push('desktop AI output contract failed');if(!i.asset_batching_pass)deny.push('asset batching/atlas policy failed');if(!i.sbom_pass)deny.push('CycloneDX SBOM generation failed');if(!i.update_trust_pass)deny.push('signed rollback-resistant update trust failed');if(!i.feature_flags_pass)deny.push('feature flag safety contract failed');if(!i.config_contract_pass)deny.push('configuration contract failed');if(!i.adapter_sandbox_pass)deny.push('adapter sandbox fail-closed contract failed');if(!i.reproducible_build_pass)deny.push('reproducible-build gate failed');if(i.gpu_mandatory)deny.push('GPU was made mandatory although CPU-first policy forbids it');if(i.last_writer_wins)deny.push('last-writer-wins detected on a protected integration path');if(i.unverified_100_claim)deny.push('a 100% production claim has no production certification evidence');return {allow:deny.length===0,deny}}
function opaDecision(i){if(!commandExists('opa'))return {available:false,allow:null,deny:[],reason:'opa binary not installed; deterministic JS mirror enforced'};const temp=path.join(ROOT,'.world-server-state','policy-input.json');writeJSON(temp,i);const r=run('opa',['eval','--bundle',path.join(ROOT,'policy','opa-bundle'),'--input',temp,'data.worldserver.integration.decision','--format=json']);if(!r.ok)return {available:true,allow:false,deny:['OPA evaluation failed'],error:r.stderr||r.stdout};try{const j=JSON.parse(r.stdout),v=j.result?.[0]?.expressions?.[0]?.value||{};return {available:true,allow:Boolean(v.allow),deny:Array.isArray(v.deny)?v.deny:[]}}catch(e){return {available:true,allow:false,deny:['OPA result parse failed'],error:e.message}}}
const input=buildInput(),js=jsDecision(input),opa=opaDecision(input),parity=!opa.available||(opa.allow===js.allow&&JSON.stringify([...opa.deny].sort())===JSON.stringify([...js.deny].sort())),passResult=js.allow&&(!opa.available||opa.allow)&&parity;
const report={schemaVersion:'7.2.0',generatedAt:nowIso(),policy:'OPA/Rego + deterministic offline mirror',input,jsDecision:js,opaDecision:opa,decisionParity:parity,pass:passResult,warnings:opa.available?[]:['OPA binary is optional; Rego bundle is installed and the JS mirror enforces the same critical rules offline']};writeJSON(path.join(ROOT,'POLICY_DECISION_REPORT.json'),report);console.log(`[POLICY_V4] ${passResult?'PASS':'FAIL'} js=${js.allow} opa=${opa.available?opa.allow:'offline-mirror'} parity=${parity}`);if(!passResult)process.exitCode=2;
