begin;
create table if not exists public.quality_telemetry (
  id bigint generated by default as identity primary key,
  app text not null check (char_length(app) between 1 and 64),
  event_type text not null check (char_length(event_type) between 1 and 64),
  path text not null default '' check (char_length(path) <= 160),
  load_ms double precision,
  dom_ms double precision,
  fps double precision,
  error_count integer,
  coarse boolean,
  viewport_w integer,
  viewport_h integer,
  dpr double precision,
  message text,
  created_at timestamptz not null default now(),
  check (load_ms is null or load_ms between 0 and 120000),
  check (dom_ms is null or dom_ms between 0 and 120000),
  check (fps is null or fps between 0 and 240),
  check (error_count is null or error_count between 0 and 1000),
  check (viewport_w is null or viewport_w between 1 and 10000),
  check (viewport_h is null or viewport_h between 1 and 10000),
  check (dpr is null or dpr between 0.25 and 8),
  check (message is null or char_length(message) <= 240)
);
create index if not exists quality_telemetry_app_created_idx on public.quality_telemetry(app,created_at desc);
create index if not exists quality_telemetry_type_created_idx on public.quality_telemetry(event_type,created_at desc);
revoke all on table public.quality_telemetry from anon,authenticated;
revoke all on sequence public.quality_telemetry_id_seq from anon,authenticated;
alter table public.quality_telemetry enable row level security;
commit;
