"use strict";
const fs=require('node:fs');const path=require('node:path');const cp=require('node:child_process');
const patchRoot=__dirname,repoRoot=path.resolve(process.argv[2]||process.cwd());
function run(cmd,args,opts={}){const r=cp.spawnSync(cmd,args,{cwd:repoRoot,encoding:'utf8',stdio:opts.capture?'pipe':'inherit'});if(r.status!==0)throw new Error(`${cmd} ${args.join(' ')} failed\n${r.stderr||r.stdout||''}`);return(r.stdout||'').trim();}
function ensureRepo(){for(const f of ['AGENTS.md','package.json','DESKTOP_AI_INSTALL_AND_VERIFY.md'])if(!fs.existsSync(path.join(repoRoot,f)))throw new Error(`Not World_server root: missing ${f}`);}
function ensureBranch(){let b=run('git',['branch','--show-current'],{capture:true});if(!b)throw new Error('Detached HEAD');if(['master','main'].includes(b)){let name='ai/desktop/pixel-animation-system-v3';if(cp.spawnSync('git',['show-ref','--verify','--quiet',`refs/heads/${name}`],{cwd:repoRoot}).status===0)name+=`-${Date.now()}`;run('git',['checkout','-b',name]);b=name;}if(['master','main'].includes(b))throw new Error('Refusing protected base branch');return b;}
function copy(rel){const s=path.join(patchRoot,rel),d=path.join(repoRoot,rel);if(!fs.existsSync(s))throw new Error(`Patch file missing: ${rel}`);fs.mkdirSync(path.dirname(d),{recursive:true});fs.copyFileSync(s,d);}
function register(){const f=path.join(repoRoot,'data/golden-components.json');if(!fs.existsSync(f))throw new Error('Missing data/golden-components.json');const d=JSON.parse(fs.readFileSync(f,'utf8'));d.components=d.components||{};const previous=d.components['pixel-animation-runtime']||{};d.components['pixel-animation-runtime']={...previous,canonical:'shared/pixel-animation-runtime.js',core:'shared/pixel-animation-engine.js',webgpu:'shared/pixel-animation-webgpu.js',gpuCulling:'shared/pixel-animation-gpu-culling.js',worker:'shared/pixel-animation-worker.js',pixi8:'shared/pixel-animation-pixi8-adapter.js',atlasBuilder:'shared/pixel-atlas-builder.js',multiAtlas:'shared/pixel-animation-multi-atlas.js',autoProfile:'shared/pixel-animation-auto-profile.js',regionRig:'shared/pixel-animation-region-rig.js',pipelineCache:'shared/pixel-animation-pipeline-cache.js',visualRegression:'shared/pixel-animation-visual-regression.js',deviceLearning:'shared/pixel-animation-device-learning.js',autoIntegrator:'shared/pixel-animation-auto-integrator.js',status:'candidate',version:'3.0.0',scope:{requiresCapability:'pixel-animation'},rules:['preserve accepted graphics and gameplay','nearest-neighbor pixel rendering','one global animation clock','GPU instancing for mass rich sprites','GPU compute culling only with safe fallback','bounded visible buffers and indirect draw','multi-atlas texture arrays with legacy layer-0 compatibility','Pixi ParticleContainer only for lightweight/far-field layers','spatial culling before rendering fallback','adaptive LOD and device budget','bounded learned quality policy','authenticated telemetry only','no per-object ambient timers','automatic backend fallback','auto-integrate marked game/world canvases only','promote only after desktop/mobile real-browser evidence']};fs.writeFileSync(f,JSON.stringify(d,null,2)+'\n');}
function addScripts(){const f=path.join(repoRoot,'package.json'),p=JSON.parse(fs.readFileSync(f,'utf8'));p.scripts=p.scripts||{};p.scripts['pixel-animation:check']='node scripts/pixel-animation-verify.js && node --test test/pixel-animation-engine.test.js test/pixel-animation-v2.test.js test/pixel-animation-v3.test.js test/pixel-animation-syntax.test.js && node scripts/pixel-animation-visual-regression.js';p.scripts['pixel-animation:bench']='node scripts/pixel-animation-benchmark.js 50000 300';p.scripts['pixel-animation:auto-integrate']='node scripts/pixel-animation-auto-integrate.js .';fs.writeFileSync(f,JSON.stringify(p,null,2)+'\n');}
const files=[
 'shared/pixel-animation-engine.js','shared/pixel-animation-webgpu.js','shared/pixel-animation-runtime.js','shared/pixel-animation-worker.js','shared/pixel-animation-worker-bridge.js','shared/pixel-animation-pixi8-adapter.js','shared/pixel-atlas-builder.js','shared/pixel-animation-auto-profile.js',
 'shared/pixel-animation-gpu-culling.js','shared/pixel-animation-multi-atlas.js','shared/pixel-animation-region-rig.js','shared/pixel-animation-pipeline-cache.js','shared/pixel-animation-visual-regression.js','shared/pixel-animation-device-learning.js','shared/pixel-animation-auto-integrator.js',
 'test/pixel-animation-engine.test.js','test/pixel-animation-v2.test.js','test/pixel-animation-v3.test.js','test/pixel-animation-syntax.test.js',
 'scripts/pixel-animation-benchmark.js','scripts/pixel-animation-verify.js','scripts/pixel-animation-visual-regression.js','scripts/pixel-animation-auto-integrate.js',
 'tools/pixel-animation-lab/index.html',
 'supabase/migrations/20260823163800_pixel_animation_runtime_v1.sql','supabase/migrations/20260824051000_pixel_animation_runtime_v2.sql','supabase/migrations/20260824053500_pixel_animation_runtime_v3.sql','supabase/migrations/20260824053600_pixel_animation_runtime_v3_deny_policy.sql','supabase/migrations/20260824053700_pixel_animation_runtime_v3_remove_unused_indexes.sql',
 'supabase/functions/pixel-animation-config/index.ts','supabase/functions/pixel-animation-telemetry/index.ts','DESKTOP_AI_PIXEL_ANIMATION_V3.md','PIXEL_ANIMATION_V3_STATUS.md'
];
ensureRepo();const branch=ensureBranch();for(const rel of files)copy(rel);register();addScripts();fs.copyFileSync(path.join(patchRoot,'WORK_IN_PROGRESS_PIXEL_ANIMATION.md'),path.join(repoRoot,'WORK_IN_PROGRESS.md'));
run(process.execPath,['scripts/pixel-animation-auto-integrate.js','.']);
const second=run(process.execPath,['scripts/pixel-animation-auto-integrate.js','.'],{capture:true});if(!/"changed"\s*:\s*0/.test(second))throw new Error(`Auto-integrator is not idempotent:\n${second}`);console.log(second);
run(process.execPath,['scripts/pixel-animation-verify.js']);
run(process.execPath,['--test','test/pixel-animation-engine.test.js','test/pixel-animation-v2.test.js','test/pixel-animation-v3.test.js','test/pixel-animation-syntax.test.js']);
run(process.execPath,['scripts/pixel-animation-visual-regression.js']);
run(process.execPath,['scripts/pixel-animation-benchmark.js','50000','300']);
run('git',['diff','--check']);
console.log(`\nPIXEL ANIMATION V3 INSTALLED on ${branch}`);
console.log('MANDATORY NEXT: reconcile Supabase migration history, test config+authenticated telemetry, npm run quality:impact, npm run release:gate, then real desktop/mobile backend matrix.');
console.log('DO NOT STOP while any mandatory test, console/network/runtime error, visual/FPS regression, atlas-layer problem, telemetry/auth failure or device fallback issue remains.');
