(function(root,factory){'use strict';const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.PixelAnimationDeviceLearning=api;})(typeof globalThis!=='undefined'?globalThis:this,function(root){
'use strict';const VERSION='3.0.0';
function hash(text){let h=2166136261>>>0;for(const ch of String(text)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0).toString(16);}
function fingerprint(extra){const n=root.navigator||{};return hash([n.userAgent||'',n.platform||'',n.hardwareConcurrency||0,n.deviceMemory||0,extra&&extra.backend||'',extra&&extra.renderer||''].join('|'));}
function boundedPolicy(base,learned){const out=JSON.parse(JSON.stringify(base||{}));if(!learned)return out;for(const tier of ['low','medium','high','ultra']){if(!out.tiers||!out.tiers[tier]||!learned.tiers||!learned.tiers[tier])continue;const a=out.tiers[tier],b=learned.tiers[tier];if(Number.isFinite(b.maxVisible))a.maxVisible=Math.max(500,Math.min(a.maxVisible*1.5,Math.max(a.maxVisible*0.5,b.maxVisible)));if(Number.isFinite(b.resolutionScale))a.resolutionScale=Math.max(0.5,Math.min(1,b.resolutionScale));if(Number.isFinite(b.farUpdateHz))a.farUpdateHz=Math.max(4,Math.min(30,b.farUpdateHz));}return out;}
class DeviceBaselineTracker{
  constructor(options){this.options=options||{};this.samples=[];this.maxSamples=Math.max(16,Number(this.options.maxSamples)||120);}
  add(sample){const s={fps:Number(sample.fps)||0,visible:Number(sample.visible)||0,tier:sample.tier||'medium',backend:sample.backend||'unknown',frameMs:Number(sample.frameMs)||0,at:Date.now()};this.samples.push(s);if(this.samples.length>this.maxSamples)this.samples.shift();return s;}
  summary(){if(!this.samples.length)return{count:0};const sorted=this.samples.map(s=>s.fps).sort((a,b)=>a-b),q=p=>sorted[Math.min(sorted.length-1,Math.floor((sorted.length-1)*p))];return{count:sorted.length,p10:q(.1),p50:q(.5),p90:q(.9),avg:sorted.reduce((a,b)=>a+b,0)/sorted.length,maxVisible:Math.max(...this.samples.map(s=>s.visible)),backend:this.samples[this.samples.length-1].backend};}
  recommend(basePolicy){const s=this.summary(),out=JSON.parse(JSON.stringify(basePolicy||{}));if(!s.count||!out.tiers)return out;const tier=this.samples[this.samples.length-1].tier||'medium',t=out.tiers[tier];if(!t)return out;if(s.p10<50){t.maxVisible=Math.max(500,Math.floor(t.maxVisible*.85));t.resolutionScale=Math.max(.6,Math.round((t.resolutionScale-.05)*100)/100);}else if(s.p10>58&&s.p50>59){t.maxVisible=Math.floor(t.maxVisible*1.08);}return out;}
  async submit(url,extra){if(!url||typeof fetch!=='function')return{skipped:true};const x=extra||{};if(!x.accessToken)return{skipped:true,reason:'authenticated_user_required'};const body={schema:'pixel-animation-device-sample/v3',fingerprint:fingerprint(x),summary:this.summary(),samples:this.samples.slice(-30),backend:x.backend||this.summary().backend||'unknown',tier:x.tier||'medium'};const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${x.accessToken}`},body:JSON.stringify(body),credentials:'omit'});if(!res.ok)throw new Error(`device baseline submit failed: ${res.status}`);return res.json();}
}
return Object.freeze({VERSION,fingerprint,boundedPolicy,DeviceBaselineTracker});
});
