import * as THREE from 'three';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';

const Core = window.InkGlyphWorldCore;
if (!Core) throw new Error('InkGlyphWorldCore missing');
const $ = id => document.getElementById(id);
const ui = {
  font:$('font'), glyph:$('glyph'), preset:$('preset'), resolution:$('resolution'), height:$('height'), scatter:$('scatter'),
  quality:$('quality'), lod:$('lod'), build:$('build'), animate:$('animate'), nav:$('nav'), exportJson:$('exportJson'), exportGlb:$('exportGlb'), cache:$('cache'), status:$('status')
};
const mobile = matchMedia('(pointer:coarse)').matches;
let registry, currentWorld=null, currentMeta=null, meshes=[], worker=null, workerSeq=0, vectorModulePromise=null, navVisible=true;
let revealPlaying=false, revealStart=0, revealDuration=5600;

const scene=new THREE.Scene(); scene.background=new THREE.Color(0xefe7d6); scene.fog=new THREE.FogExp2(0xefe7d6,.012);
const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,500);
const renderer=new THREE.WebGLRenderer({antialias:!mobile,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.25:1.7)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=!mobile; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; document.body.prepend(renderer.domElement);
window.WorldQualityAutopilot?.registerRenderer?.('ink-glyph-world',renderer,{initialTier:mobile?'BALANCED':'HIGH',targetFps:mobile?40:55,getStats(){return{calls:renderer.info.render.calls,triangles:renderer.info.render.triangles}}});
scene.add(new THREE.HemisphereLight(0xfff7e8,0x6f6557,2));
const sun=new THREE.DirectionalLight(0xffe9c4,3.1); sun.position.set(35,70,20); sun.castShadow=!mobile; sun.shadow.mapSize.set(mobile?512:1024,mobile?512:1024); scene.add(sun);
const floor=new THREE.Mesh(new THREE.BoxGeometry(150,.6,150),new THREE.MeshStandardMaterial({color:0xe8ddc4,roughness:1})); floor.position.y=-.32; floor.receiveShadow=true; scene.add(floor);
const grid=new THREE.GridHelper(150,75,0x968c7a,0xc9bea7); grid.position.y=.01; grid.material.opacity=.16; grid.material.transparent=true; scene.add(grid);
const worldGroup=new THREE.Group(); worldGroup.name='InkGlyphWorld'; scene.add(worldGroup);
const navGroup=new THREE.Group(); navGroup.name='InkGlyphNavigation'; scene.add(navGroup);

let yaw=.68,pitch=.78,distance=67,target=new THREE.Vector3(0,2,0),dragging=false,lastX=0,lastY=0,lastTouchDistance=0;
function updateCamera(){pitch=Core.clamp(pitch,.18,1.42);distance=Core.clamp(distance,15,175);const cp=Math.cos(pitch);camera.position.set(target.x+Math.sin(yaw)*cp*distance,target.y+Math.sin(pitch)*distance,target.z+Math.cos(yaw)*cp*distance);camera.lookAt(target)}
renderer.domElement.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId)});
renderer.domElement.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;yaw-=dx*.008;pitch+=dy*.007;updateCamera()});
renderer.domElement.addEventListener('pointerup',()=>dragging=false);renderer.domElement.addEventListener('pointercancel',()=>dragging=false);
renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance*=Math.exp(e.deltaY*.0012);updateCamera()},{passive:false});
renderer.domElement.addEventListener('touchmove',e=>{if(e.touches.length===2){const a=e.touches[0],b=e.touches[1],d=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);if(lastTouchDistance)distance*=lastTouchDistance/d;lastTouchDistance=d;updateCamera()}},{passive:true});
renderer.domElement.addEventListener('touchend',()=>lastTouchDistance=0);

function setStatus(text,error=false){ui.status.textContent=text;ui.status.classList.toggle('error',error)}
function fontUrl(meta){return `../../assets/fonts/ink-glyph/${meta.file}`}
function fontWebUrl(meta){return `../../assets/fonts/ink-glyph/${meta.webFile||meta.file.replace(/\.ttf$/i,'.woff2')}`}
const woff2Availability=new Map();
async function preferredNativeFontUrl(meta){if(woff2Availability.has(meta.id))return woff2Availability.get(meta.id)?fontWebUrl(meta):fontUrl(meta);let ok=false;try{const r=await fetch(fontWebUrl(meta),{method:'HEAD',cache:'force-cache'});ok=r.ok}catch{}woff2Availability.set(meta.id,ok);return ok?fontWebUrl(meta):fontUrl(meta)}
async function loadRegistry(){const r=await fetch('../../data/ink-glyph-font-registry.json',{cache:'no-store'});if(!r.ok)throw new Error(`font registry HTTP ${r.status}`);registry=await r.json();ui.font.innerHTML='';for(const f of registry.fonts){const o=document.createElement('option');o.value=f.id;o.textContent=f.title;ui.font.append(o)}const qp=new URLSearchParams(location.search);if(qp.get('font')&&registry.fonts.some(x=>x.id===qp.get('font')))ui.font.value=qp.get('font');if(qp.get('glyph'))ui.glyph.value=qp.get('glyph').slice(0,8);if(qp.get('preset'))ui.preset.value=qp.get('preset')}
async function ensureFont(meta){const family=`IGW_${meta.id.replace(/[^a-z0-9]/gi,'_')}`;if(document.fonts.check(`32px "${family}"`))return family;const src=await preferredNativeFontUrl(meta),format=src.endsWith('.woff2')?'woff2':'truetype';const ff=new FontFace(family,`url("${src}") format("${format}")`,{style:'normal',weight:'400'});try{await ff.load();document.fonts.add(ff);return family}catch{throw new Error(`Font ${meta.file} is not installed. Run: npm run fonts:ink:download`)}}
function alphaFromCanvas(c){const rgba=c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,c.width,c.height).data;const alpha=new Uint8Array(c.width*c.height);for(let i=0,j=3;i<alpha.length;i++,j+=4)alpha[i]=rgba[j];return alpha}
async function renderGlyphMaskNative(text,meta,resolution){const family=await ensureFont(meta),c=document.createElement('canvas');c.width=c.height=resolution;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.clearRect(0,0,resolution,resolution);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.textBaseline='middle';let size=Math.floor(resolution*.84);ctx.font=`${size}px "${family}"`;const safe=text?.trim()||'龍',m=ctx.measureText(safe);if(m.width>resolution*.88){size=Math.max(12,Math.floor(size*(resolution*.88/m.width)));ctx.font=`${size}px "${family}"`}ctx.fillText(safe,resolution/2,resolution*.51);return{alpha:alphaFromCanvas(c),mode:'native-font-raster'}}
async function getVectorModule(){if(vectorModulePromise)return vectorModulePromise;vectorModulePromise=(async()=>{try{return await import('../../shared/vendor/opentype.module.js')}catch{return null}})();return vectorModulePromise}
async function renderGlyphMask(text,meta,resolution){const ot=await getVectorModule();if(!ot?.parse)return renderGlyphMaskNative(text,meta,resolution);try{const rb=await fetch(fontUrl(meta),{cache:'force-cache'});if(!rb.ok)throw new Error(`font HTTP ${rb.status}`);const font=ot.parse(await rb.arrayBuffer());const c=document.createElement('canvas');c.width=c.height=resolution;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.fillStyle='#fff';const safe=text?.trim()||'龍';let size=resolution*.82;let path=font.getPath(safe,0,0,size);let box=path.getBoundingBox();const bw=Math.max(1,box.x2-box.x1),bh=Math.max(1,box.y2-box.y1),scale=Math.min(resolution*.84/bw,resolution*.84/bh);size*=scale;path=font.getPath(safe,0,0,size);box=path.getBoundingBox();const x=(resolution-(box.x2-box.x1))/2-box.x1,y=(resolution-(box.y2-box.y1))/2-box.y1;path=font.getPath(safe,x,y,size);path.fill='#fff';path.draw(ctx);return{alpha:alphaFromCanvas(c),mode:'opentype-vector-source'}}catch(e){console.warn('Vector glyph path fallback:',e);return renderGlyphMaskNative(text,meta,resolution)}}

function strokeFile(text){const chars=[...(text||'').trim()];if(chars.length!==1)return null;return `U+${chars[0].codePointAt(0).toString(16).toUpperCase().padStart(4,'0')}.json`}
async function loadStrokeData(text){const file=strokeFile(text);if(!file)return null;try{const r=await fetch(`../../assets/hanzi-strokes/${file}`,{cache:'force-cache'});if(!r.ok)return null;const data=await r.json();return Array.isArray(data.medians)&&data.medians.length?{medians:data.medians,sourceFile:file}:null}catch{return null}}

function openDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return resolve(null);const r=indexedDB.open('ink-glyph-world-cache',2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('recipes'))r.result.createObjectStore('recipes')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function cacheGet(key){try{const db=await openDb();if(!db)return null;return await new Promise((res,rej)=>{const t=db.transaction('recipes','readonly').objectStore('recipes').get(key);t.onsuccess=()=>res(t.result||null);t.onerror=()=>rej(t.error)})}catch{return null}}
async function cacheSet(key,value){try{const db=await openDb();if(!db)return;await new Promise((res,rej)=>{const t=db.transaction('recipes','readwrite');t.objectStore('recipes').put(value,key);t.oncomplete=res;t.onerror=()=>rej(t.error)})}catch{}}
async function cacheClear(){try{const db=await openDb();if(!db)return;await new Promise((res,rej)=>{const t=db.transaction('recipes','readwrite');t.objectStore('recipes').clear();t.oncomplete=res;t.onerror=()=>rej(t.error)});setStatus('Recipe cache cleared.')}catch(e){setStatus(`Cache clear failed: ${e.message}`,true)}}
function generateInWorker(alpha,width,height,options){if(!('Worker'in window)){const mask=Core.cleanMask(alpha,width,height,{threshold:.20,minNeighbors:1});return Promise.resolve(options.qualityTournament?Core.tournamentMaskToWorld(mask,width,height,options):Core.maskToWorld(mask,width,height,options))}if(!worker)worker=new Worker('./worker.js');return new Promise((resolve,reject)=>{const id=++workerSeq;const onMessage=e=>{if(e.data?.id!==id)return;worker.removeEventListener('message',onMessage);e.data.ok?resolve(e.data.world):reject(new Error(e.data.error||'worker failed'))};worker.addEventListener('message',onMessage);worker.postMessage({id,alpha,width,height,options},[alpha.buffer])})}

function disposeMeshes(){for(const mesh of meshes){worldGroup.remove(mesh);mesh.geometry?.dispose();mesh.material?.dispose()}meshes=[];while(navGroup.children.length){const c=navGroup.children.pop();c.geometry?.dispose();c.material?.dispose()}}
const roleStyle={road:{color:0x3b3127,y:.13,scale:.88},wall:{color:0x1e1a17,y:0,scale:.96},building:{color:0x151310,y:0,scale:.92},tower:{color:0x7d1d16,y:0,scale:.88},splatter:{color:0x221d18,y:0,scale:.52}};
function setCellMatrix(mesh,c,i,visibility=1){const st=mesh.userData.igwStyle,dummy=mesh.userData.igwDummy||new THREE.Object3D();mesh.userData.igwDummy=dummy;const sy=Math.max(.001,c.height*visibility);dummy.position.set(c.x,st.y+sy/2,c.z);dummy.scale.set(st.scale,sy,st.scale);dummy.rotation.set(0,c.role==='splatter'?(Core.hashString(`${c.x}/${c.z}`)%628)/100:0,0);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix)}
function buildRoleMesh(cells,role){const filtered=cells.filter(c=>c.role===role);if(!filtered.length)return;const st=roleStyle[role]||roleStyle.building,geo=new THREE.BoxGeometry(.92,1,.92),mat=new THREE.MeshStandardMaterial({color:st.color,roughness:role==='tower'?.72:.91,metalness:0});const mesh=new THREE.InstancedMesh(geo,mat,filtered.length);mesh.name=`IGW_${role}`;mesh.castShadow=!mobile&&role!=='road';mesh.receiveShadow=true;mesh.userData.igwCells=filtered;mesh.userData.igwStyle=st;const color=new THREE.Color();filtered.forEach((c,i)=>{setCellMatrix(mesh,c,i,1);const ink=.04+.10*(1-c.alpha);if(role==='tower')color.setRGB(.34+ink,.05+ink*.3,.035+ink*.2);else color.setRGB(ink,ink*.94,ink*.86);mesh.setColorAt(i,color)});mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;worldGroup.add(mesh);meshes.push(mesh)}
function lodCells(world){const mode=ui.lod.value||'auto',effective=mode==='auto'?(mobile?'low':'medium'):mode;if(effective==='full'||!world.lod)return world.cells;const ids=effective==='low'?world.lod.lowIndices:world.lod.mediumIndices;return(ids||[]).map(i=>world.cells[i]).filter(Boolean)}
function buildNavPreview(world){const nav=world.navigation;if(!nav?.previewPath?.length)return;const pts=nav.previewPath.map(id=>nav.nodes[id]).filter(Boolean).map(n=>new THREE.Vector3(n.x,n.y+.18,n.z));if(pts.length<2)return;const geo=new THREE.BufferGeometry().setFromPoints(pts),mat=new THREE.LineBasicMaterial({color:0xb3261e,transparent:true,opacity:.92});const line=new THREE.Line(geo,mat);line.name='IGW_NAV_PREVIEW';navGroup.add(line);navGroup.visible=navVisible}
function applyWorld(world){disposeMeshes();const selected=lodCells(world);for(const role of ['road','wall','building','tower','splatter'])buildRoleMesh(selected,role);buildNavPreview(world);const stats=Core.worldStats(world),span=Math.max(stats.bounds?stats.bounds.maxX-stats.bounds.minX:20,stats.bounds?stats.bounds.maxZ-stats.bounds.minZ:20);distance=Core.clamp(span*1.32,30,125);target.set(0,stats.maxHeight*.18,0);updateCamera();worldGroup.userData={generator:'InkGlyphWorld',generatorVersion:Core.GENERATOR_VERSION,glyph:(ui.glyph.value||'龍').trim(),font:currentMeta?.id,preset:world.preset,qualityScore:world.quality?.score,strokeSource:world.stroke?.source};return{stats,rendered:selected.length}}

async function build(){ui.build.disabled=true;try{const meta=registry.fonts.find(f=>f.id===ui.font.value)||registry.fonts[0],glyph=(ui.glyph.value||'龍').trim().slice(0,8)||'龍',resolution=Core.clamp(Number(ui.resolution.value)||80,48,mobile?96:160),preset=ui.preset.value||'city',height=Core.clamp(Number(ui.height.value)||8,2,20),scatter=Core.clamp(Number(ui.scatter.value)||0,0,.2),strokeData=await loadStrokeData(glyph),qualityTournament=ui.quality.checked;const key=Core.recipeKey({font:meta.id,fontBlob:meta.sourceGitBlobSha,glyph,resolution,preset,height,scatter,vector:'opentype-2.0.0',stroke:strokeData?'hanzi-writer-data-2.0.1':'procedural',qualityTournament});let world=await cacheGet(key),source='cache',renderMode='cached';if(!world){const rendered=await renderGlyphMask(glyph,meta,resolution);renderMode=rendered.mode;world=await generateInWorker(rendered.alpha,resolution,resolution,{seed:`${meta.id}:${glyph}:${resolution}:${preset}`,preset,maxCells:mobile?4200:9000,minHeight:1.2,maxHeight:height,scatter,threshold:.20,strokeData:strokeData?{medians:strokeData.medians}:null,qualityTournament,candidateCount:mobile?2:3,maxNavNodes:mobile?1200:2600});await cacheSet(key,world);source='generated'}currentWorld=world;currentMeta=meta;const applied=applyWorld(world),u=new URL(location.href);u.searchParams.set('font',meta.id);u.searchParams.set('glyph',glyph);u.searchParams.set('preset',preset);history.replaceState(null,'',u);document.documentElement.dataset.inkGlyphReady='1';document.documentElement.dataset.inkGlyphNavReady=String(world.navigation?.nodeCount>0?1:0);document.documentElement.dataset.inkGlyphTopologyReady=String(world.topology?.landmarkCount>0?1:0);setStatus(`${meta.title} · ${glyph} · ${preset}\n${world.instanceCount.toLocaleString()} generated / ${applied.rendered.toLocaleString()} rendered · ${source} · ${renderMode}\nquality ${world.quality?.score??'—'}/100 · strokes ${world.stroke?.strokeCount||1} (${world.stroke?.source||'procedural'}) · nav ${world.navigation?.nodeCount||0} nodes / ${(100*(world.navigation?.componentCoverage||0)).toFixed(0)}% connected · landmarks ${world.topology?.landmarkCount||0} / cycles ${world.topology?.cycleRank||0}${world.tournament?` · tournament ${world.tournament.candidateCount}→#${world.tournament.selectedIndex}`:''}`)}catch(e){console.error(e);document.documentElement.dataset.inkGlyphReady='0';setStatus(e.message||String(e),true)}finally{ui.build.disabled=false}}

function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}
function exportWorld(){if(!currentWorld)return;const data={...currentWorld,font:{id:currentMeta.id,title:currentMeta.title,file:currentMeta.file,license:'SIL OFL 1.1'},glyph:(ui.glyph.value||'龍').trim(),strokeProvenance:currentWorld.stroke?.source==='hanzi-writer-data'?{package:'hanzi-writer-data',version:'2.0.1',license:'Arphic Public License'}:null,createdAt:new Date().toISOString()};downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),`ink-glyph-${currentMeta.id}-${encodeURIComponent(ui.glyph.value||'glyph')}.json`)}
async function exportGlb(){if(!currentWorld)return;ui.exportGlb.disabled=true;try{const exporter=new GLTFExporter(),result=await exporter.parseAsync(worldGroup,{binary:true,trs:true,onlyVisible:true,maxTextureSize:1024});const blob=new Blob([result],{type:'model/gltf-binary'});downloadBlob(blob,`ink-glyph-${currentMeta.id}-${encodeURIComponent(ui.glyph.value||'glyph')}.glb`);setStatus(`${ui.status.textContent}\nGLB exported ${(blob.size/1024).toFixed(1)} KiB. Optional: npm run ink:glyph:glb:optimize -- <input.glb>`)}catch(e){console.error(e);setStatus(`GLB export failed: ${e.message}`,true)}finally{ui.exportGlb.disabled=false}}
function startStrokeAnimation(){if(!currentWorld)return;revealPlaying=true;revealStart=performance.now();ui.animate.disabled=true}
function updateReveal(now){if(!revealPlaying)return;const p=Core.clamp((now-revealStart)/revealDuration,0,1);for(const mesh of meshes){const cells=mesh.userData.igwCells||[];for(let i=0;i<cells.length;i++){const order=Number(cells[i].drawOrder??0),visibility=Core.clamp((p-order)*36,0,1);setCellMatrix(mesh,cells[i],i,visibility)}mesh.instanceMatrix.needsUpdate=true}if(p>=1){revealPlaying=false;ui.animate.disabled=false}}
function toggleNav(){navVisible=!navVisible;navGroup.visible=navVisible;ui.nav.textContent=navVisible?'Hide path':'Show path'}

ui.build.addEventListener('click',build);ui.animate.addEventListener('click',startStrokeAnimation);ui.nav.addEventListener('click',toggleNav);ui.exportJson.addEventListener('click',exportWorld);ui.exportGlb.addEventListener('click',exportGlb);ui.cache.addEventListener('click',cacheClear);ui.font.addEventListener('change',build);ui.preset.addEventListener('change',build);ui.lod.addEventListener('change',()=>currentWorld&&applyWorld(currentWorld));ui.quality.addEventListener('change',build);ui.glyph.addEventListener('keydown',e=>{if(e.key==='Enter')build()});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
function animate(now){requestAnimationFrame(animate);updateReveal(now);if(!dragging)yaw+=.0003;updateCamera();renderer.render(scene,camera)}
try{await loadRegistry();if(mobile){ui.resolution.value='64';ui.lod.value='auto'}await build();requestAnimationFrame(animate)}catch(e){console.error(e);setStatus(e.message||String(e),true);requestAnimationFrame(animate)}
