-- Unified Autonomous Game Factory v1
-- Additive migration: preserves all existing quality/runtime tables and workers.
-- Rollback strategy: disable factory APIs/workers first; drop factory_* RPCs/tables; remove only additive quality_worker_jobs columns.

create table if not exists public.factory_licenses (
  license_key text primary key,
  display_name text not null,
  production_policy text not null default 'review' check (production_policy in ('allow','review','deny')),
  commercial_use boolean,
  derivatives boolean,
  attribution_required boolean,
  copyleft boolean,
  source_url text,
  notes text,
  updated_at timestamptz not null default now()
);

insert into public.factory_licenses(license_key,display_name,production_policy,commercial_use,derivatives,attribution_required,copyleft,notes)
values
 ('USER-OWNED','User owned / original','allow',true,true,false,false,'Declared original or owned by the project'),
 ('CC0-1.0','Creative Commons Zero 1.0','allow',true,true,false,false,null),
 ('MIT','MIT License','allow',true,true,true,false,null),
 ('Apache-2.0','Apache License 2.0','allow',true,true,true,false,null),
 ('BSD-3-Clause','BSD 3-Clause','allow',true,true,true,false,null),
 ('UNKNOWN','Unknown / unverified','deny',null,null,null,null,'Fail closed: cannot enter production')
on conflict (license_key) do nothing;

create table if not exists public.factory_assets (
  id uuid primary key default gen_random_uuid(),
  asset_key text not null unique,
  asset_type text not null check (asset_type in ('model','texture','apng','sound','animation','3dgs','video','image','mesh','material','scene','dataset','other')),
  display_name text not null,
  current_version text,
  lifecycle_state text not null default 'draft' check (lifecycle_state in ('draft','active','deprecated','quarantined','deleted')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.factory_asset_versions (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid not null references public.factory_assets(id) on delete cascade,
  version text not null,
  sha256 text check (sha256 is null or sha256 ~ '^[0-9a-f]{64}$'),
  storage_uri text,
  media_type text,
  bytes bigint check (bytes is null or bytes >= 0),
  lod jsonb not null default '{}'::jsonb,
  quality jsonb not null default '{}'::jsonb,
  compatibility jsonb not null default '{}'::jsonb,
  license_key text not null default 'UNKNOWN' references public.factory_licenses(license_key),
  status text not null default 'draft' check (status in ('draft','validated','quarantined','production','deprecated')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(asset_id,version)
);
create index if not exists factory_asset_versions_sha_idx on public.factory_asset_versions(sha256) where sha256 is not null;

create table if not exists public.factory_asset_dependencies (
  asset_version_id uuid not null references public.factory_asset_versions(id) on delete cascade,
  depends_on_version_id uuid not null references public.factory_asset_versions(id) on delete restrict,
  relation_kind text not null default 'depends_on',
  metadata jsonb not null default '{}'::jsonb,
  primary key(asset_version_id,depends_on_version_id,relation_kind),
  check (asset_version_id <> depends_on_version_id)
);

create table if not exists public.factory_provenance_events (
  id bigint generated by default as identity primary key,
  output_asset_version_id uuid references public.factory_asset_versions(id) on delete cascade,
  input_refs jsonb not null default '[]'::jsonb,
  tool_name text not null,
  tool_version text,
  parameters jsonb not null default '{}'::jsonb,
  transformations jsonb not null default '[]'::jsonb,
  environment jsonb not null default '{}'::jsonb,
  reproducibility_hash text,
  created_at timestamptz not null default now()
);
create index if not exists factory_provenance_output_idx on public.factory_provenance_events(output_asset_version_id,created_at desc);

create table if not exists public.factory_graph_nodes (
  id uuid primary key default gen_random_uuid(),
  node_key text not null unique,
  node_type text not null check (node_type in ('file','asset','system','scene','game','deployment','dataset','gamespec','factory','test','service','other')),
  ref text,
  fingerprint text,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.factory_graph_edges (
  from_node_id uuid not null references public.factory_graph_nodes(id) on delete cascade,
  to_node_id uuid not null references public.factory_graph_nodes(id) on delete cascade,
  edge_kind text not null,
  metadata jsonb not null default '{}'::jsonb,
  primary key(from_node_id,to_node_id,edge_kind),
  check (from_node_id <> to_node_id)
);
create index if not exists factory_graph_edges_to_idx on public.factory_graph_edges(to_node_id,edge_kind);

create table if not exists public.factory_game_specs (
  id uuid primary key default gen_random_uuid(),
  spec_key text not null unique,
  source_prompt text not null,
  schema_version text not null,
  compiler_version text not null,
  spec jsonb not null,
  fingerprint text not null,
  status text not null default 'compiled' check (status in ('compiled','validated','rejected','superseded')),
  validation jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.factory_requests (
  id uuid primary key default gen_random_uuid(),
  task_key text not null unique,
  prompt text not null,
  game_spec_id uuid references public.factory_game_specs(id) on delete set null,
  status text not null default 'planned' check (status in ('planned','queued','running','blocked','complete','failed','cancelled')),
  release_channel text not null default 'experimental' check (release_channel in ('dev','experimental','preview','canary','production')),
  correlation_id uuid not null default gen_random_uuid(),
  plan jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.factory_knowledge_entities (
  id uuid primary key default gen_random_uuid(),
  entity_key text not null unique,
  entity_type text not null check (entity_type in ('character','item','biome','mechanic','rule','animation','asset','scene','world','game','system','other')),
  name text not null,
  attributes jsonb not null default '{}'::jsonb,
  source_ref text,
  updated_at timestamptz not null default now()
);

create table if not exists public.factory_knowledge_relations (
  from_entity_id uuid not null references public.factory_knowledge_entities(id) on delete cascade,
  to_entity_id uuid not null references public.factory_knowledge_entities(id) on delete cascade,
  relation_kind text not null,
  attributes jsonb not null default '{}'::jsonb,
  primary key(from_entity_id,to_entity_id,relation_kind),
  check (from_entity_id <> to_entity_id)
);

create table if not exists public.factory_datasets (
  id uuid primary key default gen_random_uuid(),
  dataset_key text not null unique,
  name text not null,
  version text not null,
  purpose text,
  license_key text not null default 'UNKNOWN' references public.factory_licenses(license_key),
  fingerprint text,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'draft' check (status in ('draft','validated','production','quarantined','deprecated')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.factory_dataset_items (
  dataset_id uuid not null references public.factory_datasets(id) on delete cascade,
  item_key text not null,
  source_uri text,
  sha256 text check (sha256 is null or sha256 ~ '^[0-9a-f]{64}$'),
  kind text not null check (kind in ('reference_image','video','audio','generated_asset','example','annotation','other')),
  license_key text not null default 'UNKNOWN' references public.factory_licenses(license_key),
  metadata jsonb not null default '{}'::jsonb,
  primary key(dataset_id,item_key)
);

create table if not exists public.factory_benchmarks (
  benchmark_key text primary key,
  name text not null,
  category text not null check (category in ('fps','cpu','ram','load','graphics','physics','animation','regression','factory')),
  thresholds jsonb not null default '{}'::jsonb,
  fixture_ref text,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.factory_benchmark_runs (
  id bigint generated by default as identity primary key,
  benchmark_key text not null references public.factory_benchmarks(benchmark_key) on delete cascade,
  candidate_ref text,
  baseline_ref text,
  metrics jsonb not null default '{}'::jsonb,
  regression jsonb not null default '{}'::jsonb,
  passed boolean not null,
  environment jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists factory_benchmark_runs_key_idx on public.factory_benchmark_runs(benchmark_key,created_at desc);

insert into public.factory_benchmarks(benchmark_key,name,category,thresholds,fixture_ref)
values
 ('world-runtime','World runtime quality','regression','{"minimumPercent":95}'::jsonb,'WORLD_RUNTIME_QUALITY_REPORT.json'),
 ('world-animation','World animation semantics','animation','{"minimumPercent":95}'::jsonb,'WORLD_ANIMATION_SEMANTIC_REPORT.json'),
 ('factory-disaster','Factory disaster recovery','factory','{"minimumPassRate":1}'::jsonb,'FACTORY_DISASTER_REPORT.json')
on conflict (benchmark_key) do nothing;

create table if not exists public.factory_feature_flags (
  flag_key text primary key,
  description text,
  release_channel text not null default 'dev' check (release_channel in ('dev','experimental','preview','canary','production')),
  enabled boolean not null default false,
  rollout_percent integer not null default 0 check (rollout_percent between 0 and 100),
  rules jsonb not null default '{}'::jsonb,
  candidate_ref text,
  expires_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.factory_backup_snapshots (
  id uuid primary key default gen_random_uuid(),
  snapshot_key text not null unique,
  scope text[] not null default array['database','assets','config']::text[],
  provider_refs jsonb not null default '{}'::jsonb,
  manifest jsonb not null default '{}'::jsonb,
  manifest_hash text,
  status text not null default 'requested' check (status in ('requested','snapshotting','available','restore_testing','verified','failed','expired')),
  verified boolean not null default false,
  restore_hash text,
  last_error text,
  created_at timestamptz not null default now(),
  verified_at timestamptz
);

create table if not exists public.factory_disaster_scenarios (
  scenario_key text primary key,
  description text not null,
  severity text not null default 'high' check (severity in ('low','medium','high','critical')),
  recovery_contract jsonb not null default '{}'::jsonb,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.factory_disaster_runs (
  id bigint generated by default as identity primary key,
  scenario_key text not null references public.factory_disaster_scenarios(scenario_key) on delete cascade,
  candidate_ref text,
  passed boolean not null,
  recovery_seconds numeric,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.factory_disaster_scenarios(scenario_key,description,severity,recovery_contract)
values
 ('worker_crash','Worker dies during a leased multi-step job','critical','{"mustResumeFromCheckpoint":true,"mustNotDuplicate":true}'::jsonb),
 ('connection_loss','Worker loses network connection','high','{"mustRetry":true,"mustPreserveCheckpoint":true}'::jsonb),
 ('corrupt_asset','Asset checksum or parser validation fails','high','{"mustQuarantine":true,"mustBlockProduction":true}'::jsonb),
 ('bad_migration','Schema migration fails compatibility validation','critical','{"mustBlockPromotion":true,"mustProvideRollback":true}'::jsonb),
 ('failed_deployment','Candidate deployment fails or violates SLO','critical','{"mustKeepPreviousProduction":true,"mustRollbackChannel":true}'::jsonb),
 ('low_memory','Worker reaches memory pressure threshold','high','{"mustThrottle":true,"mustReduceParallelism":true}'::jsonb)
on conflict (scenario_key) do nothing;

create table if not exists public.factory_secret_inventory (
  secret_key text primary key,
  provider text not null,
  service_identity text not null,
  required boolean not null default true,
  rotation_days integer not null default 90 check (rotation_days between 1 and 3650),
  last_rotated_at timestamptz,
  fingerprint text,
  scopes jsonb not null default '[]'::jsonb,
  status text not null default 'unverified' check (status in ('unverified','healthy','rotation_due','revoked','missing')),
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.factory_service_identities (
  service_key text primary key,
  role_name text not null,
  scopes jsonb not null default '[]'::jsonb,
  enabled boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.factory_service_identities(service_key,role_name,scopes)
values
 ('control-plane','factory_controller','["factory:submit","jobs:enqueue","registry:write","release:request"]'::jsonb),
 ('worker','factory_worker','["jobs:claim","jobs:checkpoint","jobs:complete","assets:write"]'::jsonb),
 ('backup','factory_backup','["backup:write","restore:test"]'::jsonb),
 ('release','factory_release','["release:promote","flags:write"]'::jsonb)
on conflict (service_key) do update set role_name=excluded.role_name,scopes=excluded.scopes,updated_at=now();

insert into public.factory_secret_inventory(secret_key,provider,service_identity,required,rotation_days,scopes)
values
 ('FACTORY_CONTROL_TOKEN','Vercel','control-plane',true,60,'["factory:submit","jobs:enqueue"]'::jsonb),
 ('FACTORY_WORKER_TOKEN','Vercel','worker',true,60,'["jobs:claim","jobs:checkpoint","jobs:complete"]'::jsonb),
 ('FACTORY_RELEASE_TOKEN','Vercel','release',true,30,'["release:promote","flags:write"]'::jsonb),
 ('FACTORY_BACKUP_TOKEN','Vercel','backup',true,30,'["backup:write","restore:test"]'::jsonb),
 ('CRON_SECRET','Vercel','backup',true,30,'["maintenance:run"]'::jsonb),
 ('SUPABASE_SECRET_KEY','Supabase','control-plane',true,30,'["database:service-role"]'::jsonb),
 ('AI3D_SHARED_SECRET','Vercel','worker',false,60,'["ai3d:invoke"]'::jsonb)
on conflict (secret_key) do update set provider=excluded.provider,service_identity=excluded.service_identity,required=excluded.required,rotation_days=excluded.rotation_days,scopes=excluded.scopes,updated_at=now();

create table if not exists public.factory_schema_contracts (
  component_key text primary key,
  schema_version text not null,
  minimum_compatible_version text,
  migration_name text not null,
  rollback_plan jsonb not null,
  compatibility_test text not null,
  migration_hash text,
  status text not null default 'active' check (status in ('active','superseded','blocked')),
  updated_at timestamptz not null default now()
);

insert into public.factory_schema_contracts(component_key,schema_version,minimum_compatible_version,migration_name,rollback_plan,compatibility_test)
values ('unified-factory','1.0.0','1.0.0','unified_autonomous_game_factory_v1',
        '{"strategy":"additive","disableBeforeDrop":true,"preserveLegacyQualityQueue":true}'::jsonb,
        'npm run factory:migrations')
on conflict (component_key) do update set schema_version=excluded.schema_version,minimum_compatible_version=excluded.minimum_compatible_version,migration_name=excluded.migration_name,rollback_plan=excluded.rollback_plan,compatibility_test=excluded.compatibility_test,updated_at=now();

alter table public.quality_worker_jobs add column if not exists idempotency_key text;
alter table public.quality_worker_jobs add column if not exists checkpoint jsonb not null default '{}'::jsonb;
alter table public.quality_worker_jobs add column if not exists next_attempt_at timestamptz not null default now();
alter table public.quality_worker_jobs add column if not exists dead_lettered_at timestamptz;
alter table public.quality_worker_jobs add column if not exists parent_job_id bigint references public.quality_worker_jobs(id) on delete set null;
alter table public.quality_worker_jobs add column if not exists correlation_id uuid not null default gen_random_uuid();
alter table public.quality_worker_jobs add column if not exists cancel_requested boolean not null default false;
alter table public.quality_worker_jobs add column if not exists timeout_seconds integer not null default 900 check (timeout_seconds between 30 and 86400);
alter table public.quality_worker_jobs add column if not exists resource_class text not null default 'cpu-small' check (resource_class in ('cpu-tiny','cpu-small','cpu-medium','cpu-large','io','sandbox'));
alter table public.quality_worker_jobs add column if not exists factory_request_id uuid references public.factory_requests(id) on delete set null;

create unique index if not exists quality_worker_jobs_idempotency_idx on public.quality_worker_jobs(idempotency_key) where idempotency_key is not null;
create index if not exists quality_worker_jobs_factory_claim_idx on public.quality_worker_jobs(status,next_attempt_at,priority desc,created_at) where status in ('queued','running');
create index if not exists quality_worker_jobs_factory_request_idx on public.quality_worker_jobs(factory_request_id) where factory_request_id is not null;

create table if not exists public.factory_job_dependencies (
  job_id bigint not null references public.quality_worker_jobs(id) on delete cascade,
  depends_on_job_id bigint not null references public.quality_worker_jobs(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(job_id,depends_on_job_id),
  check (job_id <> depends_on_job_id)
);
create index if not exists factory_job_dependencies_dep_idx on public.factory_job_dependencies(depends_on_job_id);

create table if not exists public.factory_job_events (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.quality_worker_jobs(id) on delete cascade,
  event_type text not null check (event_type in ('queued','claimed','checkpoint','retry','complete','dead_letter','cancelled','reclaimed')),
  worker_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists factory_job_events_job_idx on public.factory_job_events(job_id,created_at);

create table if not exists public.factory_job_dead_letters (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.quality_worker_jobs(id) on delete cascade,
  job_key text not null,
  kind text not null,
  attempts integer not null,
  error text,
  checkpoint jsonb not null default '{}'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(job_id)
);

create or replace function public.factory_enqueue_job_v1(
  p_job_key text,
  p_kind text,
  p_priority integer default 0,
  p_required_capabilities jsonb default '[]'::jsonb,
  p_payload jsonb default '{}'::jsonb,
  p_max_attempts integer default 5,
  p_idempotency_key text default null,
  p_resource_class text default 'cpu-small',
  p_timeout_seconds integer default 900,
  p_factory_request_id uuid default null,
  p_parent_job_id bigint default null
) returns bigint
language plpgsql security invoker set search_path='public','pg_temp'
as $$
declare v_id bigint; v_idempotency text;
begin
  if p_job_key is null or char_length(trim(p_job_key)) < 3 then raise exception 'job key required'; end if;
  if p_kind is null or char_length(trim(p_kind)) < 2 then raise exception 'job kind required'; end if;
  if jsonb_typeof(coalesce(p_required_capabilities,'[]'::jsonb)) <> 'array' then raise exception 'capabilities must be array'; end if;
  v_idempotency := nullif(left(trim(coalesce(p_idempotency_key,'')),180),'');
  if v_idempotency is not null then
    select id into v_id from public.quality_worker_jobs where idempotency_key=v_idempotency limit 1;
    if found then return v_id; end if;
  end if;
  insert into public.quality_worker_jobs(
    job_key,kind,priority,required_capabilities,payload,status,max_attempts,idempotency_key,
    next_attempt_at,resource_class,timeout_seconds,factory_request_id,parent_job_id
  ) values (
    left(trim(p_job_key),180),left(trim(p_kind),80),greatest(-100,least(coalesce(p_priority,0),100)),
    coalesce(p_required_capabilities,'[]'::jsonb),coalesce(p_payload,'{}'::jsonb),'queued',
    greatest(1,least(coalesce(p_max_attempts,5),20)),v_idempotency,now(),
    case when p_resource_class in ('cpu-tiny','cpu-small','cpu-medium','cpu-large','io','sandbox') then p_resource_class else 'cpu-small' end,
    greatest(30,least(coalesce(p_timeout_seconds,900),86400)),p_factory_request_id,p_parent_job_id
  )
  on conflict(job_key) do update set
    priority=excluded.priority,
    required_capabilities=excluded.required_capabilities,
    payload=excluded.payload,
    max_attempts=greatest(public.quality_worker_jobs.attempts,excluded.max_attempts),
    resource_class=excluded.resource_class,
    timeout_seconds=excluded.timeout_seconds,
    factory_request_id=coalesce(excluded.factory_request_id,public.quality_worker_jobs.factory_request_id),
    parent_job_id=coalesce(excluded.parent_job_id,public.quality_worker_jobs.parent_job_id),
    idempotency_key=coalesce(public.quality_worker_jobs.idempotency_key,excluded.idempotency_key),
    status=case when public.quality_worker_jobs.status in ('complete','running') then public.quality_worker_jobs.status else 'queued' end,
    next_attempt_at=case when public.quality_worker_jobs.status in ('complete','running') then public.quality_worker_jobs.next_attempt_at else now() end,
    updated_at=now()
  returning id into v_id;
  insert into public.factory_job_events(job_id,event_type,payload) values(v_id,'queued',jsonb_build_object('kind',p_kind,'priority',p_priority)) ;
  return v_id;
end;
$$;

create or replace function public.factory_claim_job_v1(
  p_worker text,
  p_capabilities jsonb default '[]'::jsonb,
  p_kinds jsonb default '[]'::jsonb,
  p_lease_seconds integer default 300
) returns setof public.quality_worker_jobs
language plpgsql security invoker set search_path='public','pg_temp'
as $$
declare v_job_id bigint; v_reclaimed boolean;
begin
  if p_worker is null or char_length(trim(p_worker)) < 3 then raise exception 'worker id required'; end if;
  if jsonb_typeof(coalesce(p_capabilities,'[]'::jsonb)) <> 'array' then raise exception 'capabilities must be array'; end if;
  if jsonb_typeof(coalesce(p_kinds,'[]'::jsonb)) <> 'array' or jsonb_array_length(coalesce(p_kinds,'[]'::jsonb))=0 then raise exception 'at least one allowed kind required'; end if;
  select j.id,(j.status='running') into v_job_id,v_reclaimed
  from public.quality_worker_jobs j
  where j.attempts < j.max_attempts
    and not j.cancel_requested
    and j.next_attempt_at <= now()
    and j.required_capabilities <@ coalesce(p_capabilities,'[]'::jsonb)
    and exists(select 1 from jsonb_array_elements_text(p_kinds) k(kind) where k.kind=j.kind)
    and (j.status='queued' or (j.status='running' and j.lease_expires_at is not null and j.lease_expires_at < now()))
    and not exists(
      select 1 from public.factory_job_dependencies d
      join public.quality_worker_jobs dep on dep.id=d.depends_on_job_id
      where d.job_id=j.id and dep.status <> 'complete'
    )
  order by j.priority desc,j.created_at asc
  for update skip locked
  limit 1;
  if v_job_id is null then return; end if;
  update public.quality_worker_jobs j
  set status='running',attempts=j.attempts+1,lease_owner=p_worker,
      lease_expires_at=now()+make_interval(secs=>greatest(30,least(p_lease_seconds,3600))),
      updated_at=now(),error=case when v_reclaimed then 'reclaimed-expired-lease' else j.error end
  where j.id=v_job_id;
  insert into public.factory_job_events(job_id,event_type,worker_id,payload)
  values(v_job_id,case when v_reclaimed then 'reclaimed' else 'claimed' end,p_worker,jsonb_build_object('leaseSeconds',greatest(30,least(p_lease_seconds,3600))));
  return query select * from public.quality_worker_jobs where id=v_job_id;
end;
$$;

create or replace function public.factory_checkpoint_job_v1(
  p_id bigint,p_worker text,p_checkpoint jsonb default '{}'::jsonb
) returns boolean
language plpgsql security invoker set search_path='public','pg_temp'
as $$
declare v_rows integer;
begin
  if jsonb_typeof(coalesce(p_checkpoint,'{}'::jsonb)) <> 'object' then raise exception 'checkpoint must be object'; end if;
  update public.quality_worker_jobs
  set checkpoint=checkpoint || coalesce(p_checkpoint,'{}'::jsonb),updated_at=now()
  where id=p_id and status='running' and lease_owner=p_worker and lease_expires_at > now();
  get diagnostics v_rows=row_count;
  if v_rows=1 then insert into public.factory_job_events(job_id,event_type,worker_id,payload) values(p_id,'checkpoint',p_worker,coalesce(p_checkpoint,'{}'::jsonb)); end if;
  return v_rows=1;
end;
$$;

create or replace function public.factory_complete_job_v1(
  p_id bigint,p_worker text,p_ok boolean,p_result jsonb default '{}'::jsonb,p_error text default null
) returns text
language plpgsql security invoker set search_path='public','pg_temp'
as $$
declare v_job public.quality_worker_jobs%rowtype; v_delay integer; v_state text;
begin
  select * into v_job from public.quality_worker_jobs where id=p_id and status='running' and lease_owner=p_worker for update;
  if not found then return 'not_owner_or_not_running'; end if;
  if v_job.cancel_requested then
    update public.quality_worker_jobs set status='cancelled',lease_owner=null,lease_expires_at=null,updated_at=now() where id=p_id;
    insert into public.factory_job_events(job_id,event_type,worker_id,payload) values(p_id,'cancelled',p_worker,'{}'::jsonb);
    return 'cancelled';
  end if;
  if p_ok then
    update public.quality_worker_jobs
    set status='complete',result=coalesce(p_result,'{}'::jsonb),error=null,lease_owner=null,lease_expires_at=null,updated_at=now()
    where id=p_id;
    insert into public.factory_job_events(job_id,event_type,worker_id,payload) values(p_id,'complete',p_worker,coalesce(p_result,'{}'::jsonb));
    return 'complete';
  end if;
  if v_job.attempts < v_job.max_attempts then
    v_delay:=least(3600,(5*power(2,greatest(0,v_job.attempts-1)))::integer);
    update public.quality_worker_jobs
    set status='queued',error=left(coalesce(p_error,'worker failed'),500),lease_owner=null,lease_expires_at=null,
        next_attempt_at=now()+make_interval(secs=>v_delay),updated_at=now()
    where id=p_id;
    insert into public.factory_job_events(job_id,event_type,worker_id,payload)
    values(p_id,'retry',p_worker,jsonb_build_object('delaySeconds',v_delay,'error',left(coalesce(p_error,'worker failed'),500)));
    return 'retry';
  end if;
  update public.quality_worker_jobs
  set status='failed',error=left(coalesce(p_error,'worker failed'),500),lease_owner=null,lease_expires_at=null,dead_lettered_at=now(),updated_at=now()
  where id=p_id;
  insert into public.factory_job_dead_letters(job_id,job_key,kind,attempts,error,checkpoint,payload)
  values(v_job.id,v_job.job_key,v_job.kind,v_job.attempts,left(coalesce(p_error,'worker failed'),500),v_job.checkpoint,v_job.payload)
  on conflict(job_id) do update set attempts=excluded.attempts,error=excluded.error,checkpoint=excluded.checkpoint,payload=excluded.payload,created_at=now();
  insert into public.factory_job_events(job_id,event_type,worker_id,payload)
  values(p_id,'dead_letter',p_worker,jsonb_build_object('error',left(coalesce(p_error,'worker failed'),500)));
  return 'dead_letter';
end;
$$;

create or replace function public.factory_cancel_job_v1(p_id bigint) returns boolean
language plpgsql security invoker set search_path='public','pg_temp'
as $$
declare v_rows integer;
begin
  update public.quality_worker_jobs
  set cancel_requested=true,status=case when status='queued' then 'cancelled' else status end,updated_at=now()
  where id=p_id and status in ('queued','running');
  get diagnostics v_rows=row_count;
  if v_rows=1 then insert into public.factory_job_events(job_id,event_type,payload) values(p_id,'cancelled','{"requested":true}'::jsonb); end if;
  return v_rows=1;
end;
$$;

-- Fail closed for all new exposed tables. All access goes through server-side service identities.
do $$
declare t text;
begin
  foreach t in array array[
    'factory_licenses','factory_assets','factory_asset_versions','factory_asset_dependencies','factory_provenance_events',
    'factory_graph_nodes','factory_graph_edges','factory_game_specs','factory_requests','factory_knowledge_entities','factory_knowledge_relations',
    'factory_datasets','factory_dataset_items','factory_benchmarks','factory_benchmark_runs','factory_feature_flags','factory_backup_snapshots',
    'factory_disaster_scenarios','factory_disaster_runs','factory_secret_inventory','factory_service_identities','factory_schema_contracts',
    'factory_job_dependencies','factory_job_events','factory_job_dead_letters'
  ] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('revoke all on table public.%I from anon, authenticated',t);
    execute format('grant select,insert,update,delete on table public.%I to service_role',t);
  end loop;
end $$;

revoke execute on function public.factory_enqueue_job_v1(text,text,integer,jsonb,jsonb,integer,text,text,integer,uuid,bigint) from public,anon,authenticated;
revoke execute on function public.factory_claim_job_v1(text,jsonb,jsonb,integer) from public,anon,authenticated;
revoke execute on function public.factory_checkpoint_job_v1(bigint,text,jsonb) from public,anon,authenticated;
revoke execute on function public.factory_complete_job_v1(bigint,text,boolean,jsonb,text) from public,anon,authenticated;
revoke execute on function public.factory_cancel_job_v1(bigint) from public,anon,authenticated;
grant execute on function public.factory_enqueue_job_v1(text,text,integer,jsonb,jsonb,integer,text,text,integer,uuid,bigint) to service_role;
grant execute on function public.factory_claim_job_v1(text,jsonb,jsonb,integer) to service_role;
grant execute on function public.factory_checkpoint_job_v1(bigint,text,jsonb) to service_role;
grant execute on function public.factory_complete_job_v1(bigint,text,boolean,jsonb,text) to service_role;
grant execute on function public.factory_cancel_job_v1(bigint) to service_role;

insert into private.quality_control_plane_meta(singleton,version,config,updated_at)
values(true,'13.0.0',jsonb_build_object(
  'unifiedFactory',jsonb_build_object(
    'schemaVersion','1.0.0','cpuFirst',true,'gpuRequired',false,
    'releaseChannels',jsonb_build_array('dev','experimental','preview','canary','production'),
    'registries',jsonb_build_array('assets','provenance','datasets','licenses','knowledge'),
    'queue',jsonb_build_object('priority',true,'retry',true,'checkpointResume',true,'deadLetter',true,'idempotency',true),
    'productionFailClosed',true
  )
),now())
on conflict(singleton) do update set
  version='13.0.0',
  config=coalesce(private.quality_control_plane_meta.config,'{}'::jsonb) || excluded.config,
  updated_at=now();
