begin;

create table if not exists public.quality_telemetry_samples (
  id bigint generated by default as identity primary key,
  project_id text not null check (char_length(project_id) between 1 and 120),
  release_id text not null default 'unknown' check (char_length(release_id) between 1 and 160),
  session_id text not null check (char_length(session_id) between 8 and 160),
  source text not null default 'web' check (char_length(source) between 1 and 40),
  metrics jsonb not null default '{}'::jsonb,
  tags jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists quality_telemetry_project_release_created_idx
  on public.quality_telemetry_samples (project_id, release_id, created_at desc);

create index if not exists quality_telemetry_session_created_idx
  on public.quality_telemetry_samples (session_id, created_at desc);

revoke all on table public.quality_telemetry_samples from anon, authenticated;
revoke all on sequence public.quality_telemetry_samples_id_seq from anon, authenticated;

alter table public.quality_telemetry_samples enable row level security;

commit;
