create table if not exists private.quality_github_bridge_events (
  id bigint generated by default as identity primary key,
  action text not null,
  repository text not null,
  sha text,
  workflow_ref text,
  actor text,
  ref text,
  subject text,
  ok boolean not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists quality_github_bridge_events_created_idx on private.quality_github_bridge_events(created_at desc);
alter table private.quality_github_bridge_events enable row level security;
revoke all on private.quality_github_bridge_events from public, anon, authenticated;

create or replace function public.quality_record_github_bridge_event(p_event jsonb)
returns bigint
language plpgsql
security definer
set search_path = private, public, pg_temp
as $$
declare v_id bigint;
begin
  insert into private.quality_github_bridge_events(action,repository,sha,workflow_ref,actor,ref,subject,ok,detail)
  values(
    left(coalesce(nullif(trim(p_event->>'action'),''),'unknown'),80),
    left(coalesce(nullif(trim(p_event->>'repository'),''),'unknown'),180),
    left(nullif(trim(p_event->>'sha'),''),80),
    left(nullif(trim(p_event->>'workflowRef'),''),300),
    left(nullif(trim(p_event->>'actor'),''),180),
    left(nullif(trim(p_event->>'ref'),''),220),
    left(nullif(trim(p_event->>'subject'),''),500),
    coalesce((p_event->>'ok')::boolean,false),
    coalesce(p_event->'detail','{}'::jsonb)
  ) returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.quality_record_github_bridge_event(jsonb) from public, anon, authenticated;
grant execute on function public.quality_record_github_bridge_event(jsonb) to service_role;

create or replace function public.quality_github_bridge_status()
returns jsonb
language sql
security definer
set search_path = private, public, pg_temp
as $$
select jsonb_build_object(
  'version','v12',
  'events24h',count(*) filter(where created_at>=now()-interval '24 hours'),
  'failed24h',count(*) filter(where created_at>=now()-interval '24 hours' and not ok),
  'lastEventAt',max(created_at),
  'lastSuccessAt',max(created_at) filter(where ok),
  'recent',coalesce((select jsonb_agg(x) from (select jsonb_build_object('id',id,'action',action,'repository',repository,'sha',sha,'workflowRef',workflow_ref,'actor',actor,'ref',ref,'ok',ok,'createdAt',created_at) x from private.quality_github_bridge_events order by created_at desc limit 20) q),'[]'::jsonb)
) from private.quality_github_bridge_events;
$$;
revoke all on function public.quality_github_bridge_status() from public, anon, authenticated;
grant execute on function public.quality_github_bridge_status() to service_role;

update private.quality_runtime_state set version='2026-08-24.v12.1',updated_at=now() where singleton=true;
