begin;
create table if not exists private.quality_provider_jobs_v6 (
  id bigint generated by default as identity primary key,
  job_key text not null unique,
  provider text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'queued' check(status in ('queued','running','completed','failed')),
  attempts integer not null default 0,
  max_attempts integer not null default 3,
  lease_owner text,
  lease_expires_at timestamptz,
  result jsonb,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
revoke all on table private.quality_provider_jobs_v6 from public,anon,authenticated;

drop function if exists public.quality_enqueue_provider_job_v6(text,text,jsonb,integer);
create function public.quality_enqueue_provider_job_v6(p_job_key text,p_provider text,p_payload jsonb default '{}'::jsonb,p_max_attempts integer default 3)
returns bigint language plpgsql security definer set search_path=private,public as $$
declare v_id bigint;
begin
 insert into private.quality_provider_jobs_v6(job_key,provider,payload,max_attempts)
 values(left(p_job_key,180),left(p_provider,80),coalesce(p_payload,'{}'::jsonb),greatest(1,least(coalesce(p_max_attempts,3),10)))
 on conflict(job_key) do update set payload=excluded.payload,updated_at=now()
 returning id into v_id;
 return v_id;
end $$;
revoke all on function public.quality_enqueue_provider_job_v6(text,text,jsonb,integer) from public,anon,authenticated;
grant execute on function public.quality_enqueue_provider_job_v6(text,text,jsonb,integer) to service_role;

drop function if exists public.quality_claim_provider_job_v6(text,text,integer);
create function public.quality_claim_provider_job_v6(p_provider text,p_owner text,p_lease_seconds integer default 300)
returns table(id bigint,job_key text,provider text,payload jsonb,attempts integer) language plpgsql security definer set search_path=private,public as $$
begin
 return query
 with pick as (
   select j.id from private.quality_provider_jobs_v6 j
   where j.provider=p_provider and j.attempts<j.max_attempts and (j.status='queued' or (j.status='running' and j.lease_expires_at<now()))
   order by j.created_at for update skip locked limit 1
 ), upd as (
   update private.quality_provider_jobs_v6 j set status='running',attempts=j.attempts+1,lease_owner=left(p_owner,160),lease_expires_at=now()+make_interval(secs=>greatest(30,least(coalesce(p_lease_seconds,300),3600))),updated_at=now(),error=case when j.status='running' then 'reclaimed-expired-lease' else null end
   from pick where j.id=pick.id returning j.id,j.job_key,j.provider,j.payload,j.attempts
 ) select * from upd;
end $$;
revoke all on function public.quality_claim_provider_job_v6(text,text,integer) from public,anon,authenticated;
grant execute on function public.quality_claim_provider_job_v6(text,text,integer) to service_role;

drop function if exists public.quality_complete_provider_job_v6(bigint,text,boolean,jsonb,text);
create function public.quality_complete_provider_job_v6(p_id bigint,p_owner text,p_ok boolean,p_result jsonb default '{}'::jsonb,p_error text default null)
returns boolean language plpgsql security definer set search_path=private,public as $$
declare n integer;
begin
 update private.quality_provider_jobs_v6 set status=case when p_ok then 'completed' else 'failed' end,result=coalesce(p_result,'{}'::jsonb),error=left(p_error,1000),lease_owner=null,lease_expires_at=null,updated_at=now()
 where id=p_id and status='running' and lease_owner=p_owner;
 get diagnostics n=row_count;return n=1;
end $$;
revoke all on function public.quality_complete_provider_job_v6(bigint,text,boolean,jsonb,text) from public,anon,authenticated;
grant execute on function public.quality_complete_provider_job_v6(bigint,text,boolean,jsonb,text) to service_role;
commit;
