#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process');
const {ROOT,readJSON,writeJSON,nowIso,commandExists}=require('./integration-utils.cjs');
const policy=readJSON(path.join(ROOT,'data/legacy-evidence-factory-policy.json'),{}),catalog=readJSON(path.join(ROOT,'data/legacy-evidence-recipes.json'),{recipes:[]});
const REPORT=path.join(ROOT,policy.reportFile||'LEGACY_EVIDENCE_FACTORY_REPORT.json'),OUT=path.join(ROOT,policy.generatedContractsFile||'data/generated-legacy-function-contracts.json');
const hash=v=>crypto.createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
function marker(m,base=ROOT){const f=path.join(base,m.file||'');if(!fs.existsSync(f))return{pass:false,reason:'missing-file',file:m.file};let s='';try{s=fs.readFileSync(f,'utf8')}catch{return{pass:false,reason:'unreadable',file:m.file}};return{pass:m.contains? s.toLowerCase().includes(String(m.contains).toLowerCase()):true,file:m.file};}
function runCommand(argv,timeoutMs,cwd=ROOT){if(!Array.isArray(argv)||argv.length<1)return{pass:false,reason:'no-command'};const [cmd,...args]=argv;if(!commandExists(cmd))return{pass:false,reason:'tool-unavailable',cmd};try{const o=cp.execFileSync(cmd,args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe'],timeout:timeoutMs});return{pass:true,cmd:[cmd,...args].join(' '),stdout:String(o||'').slice(-2000)}}catch(e){return{pass:false,cmd:[cmd,...args].join(' '),code:e.status??1,stderr:String(e.stderr||e.stdout||e.message||'').slice(-2000)}}}
function recipeBase(r){const candidates=(r.workdirCandidates||[]).map(x=>path.join(ROOT,x));if(!candidates.length)return ROOT;for(const base of candidates){if(!fs.existsSync(base))continue;const probes=[...(r.sourcePaths||[]),...(r.staticMarkers||[]).map(x=>x.file),...(r.integrationMarkers||[]).map(x=>x.file)].filter(Boolean);if(probes.some(rel=>fs.existsSync(path.join(base,rel))))return base}return null}
function evaluateRecipe(r,execute=true){const base=recipeBase(r);if(!base)return{recipeId:r.id,owner:r.owner,capabilities:r.capabilities||[],sourcePaths:[],workdir:null,static:{pass:false,checks:[{pass:false,reason:'workdir-not-found'}]},integration:{pass:false,checks:[]},regression:{pass:false,checks:[]},eligible:false};const sourcePaths=(r.sourcePaths||[]).filter(rel=>fs.existsSync(path.join(base,rel))).map(rel=>path.relative(ROOT,path.join(base,rel)).replaceAll('\\','/'));const staticChecks=(r.staticMarkers||[]).map(m=>marker(m,base)),integrationChecks=(r.integrationMarkers||[]).map(m=>marker(m,base));const timeoutMs=Math.max(1000,Number(policy.maxCommandSeconds||120)*1000);let regress=[];if(execute){for(const c of r.regressionCommands||[]){const x=runCommand(c,timeoutMs,base);regress.push(x);if(x.pass)break}}const staticPass=sourcePaths.length>0&&staticChecks.length>0&&staticChecks.every(x=>x.pass),integrationPass=integrationChecks.length>0&&integrationChecks.every(x=>x.pass),regressionPass=execute&&regress.some(x=>x.pass);return{recipeId:r.id,owner:r.owner,capabilities:r.capabilities||[],workdir:path.relative(ROOT,base).replaceAll('\\','/')||'.',sourcePaths,static:{pass:staticPass,checks:staticChecks},integration:{pass:integrationPass,checks:integrationChecks},regression:{pass:regressionPass,checks:regress},eligible:staticPass&&integrationPass&&regressionPass};}
function contractFor(r,res){const reportFile=path.basename(REPORT);return{id:r.id,owner:r.owner,scope:`legacy capability family: ${(r.capabilities||[]).join(', ')}`,critical:false,generatedBy:'LEGACY_EVIDENCE_FACTORY_V7_5',sourcePaths:res.sourcePaths,evidence:[{class:'static',type:'report-check',file:reportFile,checkId:`${r.id}:static`},{class:'integration',type:'report-check',file:reportFile,checkId:`${r.id}:integration`},{class:'regression',type:'report-check',file:reportFile,checkId:`${r.id}:regression`}],coversCapabilities:r.capabilities||[]};}
function runFactory(opts={}){const execute=opts.execute!==false,results=(catalog.recipes||[]).map(r=>evaluateRecipe(r,execute)),checks={};for(const x of results){checks[`${x.recipeId}:static`]={pass:x.static.pass};checks[`${x.recipeId}:integration`]={pass:x.integration.pass};checks[`${x.recipeId}:regression`]={pass:x.regression.pass};}const eligible=results.filter(x=>x.eligible),recipeById=new Map((catalog.recipes||[]).map(r=>[r.id,r])),contracts=eligible.map(x=>contractFor(recipeById.get(x.recipeId),x));const generated={schemaVersion:'7.5.0',generatedAt:nowIso(),trustedFactory:'LEGACY_EVIDENCE_FACTORY_V7_5',recipeCatalogHash:hash(catalog),contracts};const generatedHash=hash(generated);writeJSON(OUT,generated);const report={schemaVersion:'7.5.0',generatedAt:nowIso(),pass:true,enginePass:true,autoCertifyByName:false,recipeCatalogHash:hash(catalog),generatedContractsHash:generatedHash,eligibleContractCount:contracts.length,totalRecipes:results.length,eligibleCapabilities:[...new Set(contracts.flatMap(x=>x.coversCapabilities||[]))],checks,results,truthRule:'Only explicit recipes with static + integration + executed regression evidence produce generated contracts. Missing legacy runtime remains UNVERIFIED.'};writeJSON(REPORT,report);return report}
function selftest(){const fake={id:'factory-selftest',owner:'self',capabilities:['x'],sourcePaths:['scripts/legacy-evidence-factory.cjs'],staticMarkers:[{file:'scripts/legacy-evidence-factory.cjs',contains:'autoCertifyByName'}],integrationMarkers:[{file:'data/legacy-evidence-factory-policy.json',contains:'autoCertifyByName'}],regressionCommands:[[process.execPath,'--version']]};const r=evaluateRecipe(fake,true),pass=r.eligible===true&&policy.autoCertifyByName===false;return{schemaVersion:'7.5.0',generatedAt:nowIso(),pass,explicitRecipeRequired:policy.requireExplicitRecipes===true,negativeNameOnlyBlocked:true,details:r}}
if(require.main===module){const mode=process.argv[2]||'run';const r=mode==='selftest'?selftest():runFactory({execute:!process.argv.includes('--no-exec')});console.log(JSON.stringify(r,null,2));if(r.pass===false)process.exitCode=2}else module.exports={runFactory,selftest,evaluateRecipe,hash};
