from __future__ import annotations
from pathlib import Path
import base64, json, struct
import numpy as np


def _pack(scene: dict, chunk_size: float):
    p=scene['points']; n=scene['normals']; c=np.clip(scene['colors']*255,0,255).astype(np.uint8)
    a=np.clip(scene['alpha']*255,0,255).astype(np.uint8); su=scene['scale_u']; sv=scene['scale_v']; conf=scene['confidence']
    ck=np.floor(p[:,[0,2]]/chunk_size).astype(np.int32); groups={}
    for idx,k in enumerate(map(tuple,ck.tolist())): groups.setdefault(k,[]).append(idx)
    order=[]; chunks=[]; off=0
    for k,ids in sorted(groups.items()):
        ids=np.asarray(ids,np.int32); order.extend(ids.tolist()); center=np.mean(p[ids],axis=0); radius=float(np.max(np.linalg.norm(p[ids]-center,axis=1)))
        chunks.append({'offset':off,'count':int(len(ids)),'center':[float(x) for x in center],'radius':radius}); off+=len(ids)
    order=np.asarray(order,np.int32); p=p[order];n=n[order];c=c[order];a=a[order];su=su[order];sv=sv[order];conf=conf[order]
    buf=bytearray(len(p)*32)
    for i in range(len(p)):
        o=i*32; struct.pack_into('<fff',buf,o,*map(float,p[i])); ni=np.clip(np.round(n[i]*127),-127,127).astype(np.int8)
        struct.pack_into('<bbbb',buf,o+12,int(ni[0]),int(ni[1]),int(ni[2]),0); struct.pack_into('<BBBB',buf,o+16,int(c[i,0]),int(c[i,1]),int(c[i,2]),int(a[i])); struct.pack_into('<ff',buf,o+20,float(su[i]),float(sv[i])); struct.pack_into('<f',buf,o+28,float(conf[i]))
    return base64.b64encode(buf).decode('ascii'),chunks


def write_ewa_viewer(path: Path, scene: dict, meta: dict, chunk_size: float):
    data,chunks=_pack(scene,chunk_size); m=dict(meta);m['count']=len(scene['points']);m['chunks']=chunks
    mj=json.dumps(m,ensure_ascii=False,separators=(',',':'))
    html=r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover,user-scalable=no"><title>Pixel 3DGS CPU V3 EWA</title><style>
html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#02050a;color:#eef;font-family:system-ui,-apple-system,sans-serif;touch-action:none}canvas{position:fixed;inset:0;width:100%;height:100%;display:block}#hud{position:fixed;top:max(10px,env(safe-area-inset-top));left:10px;z-index:5;background:#050913cc;border:1px solid #58d5ff66;border-radius:12px;padding:9px 11px;font-size:12px;line-height:1.4;backdrop-filter:blur(8px)}#start{position:fixed;inset:0;z-index:10;display:grid;place-items:center;background:radial-gradient(circle,#10233acc,#010205f5)}#card{padding:24px;text-align:center;border:1px solid #58d5ff66;border-radius:18px;background:#050814e8}button{border:0;border-radius:14px;padding:14px 20px;font-weight:800;color:white;background:linear-gradient(135deg,#18c1ff,#173d8f)}#joy,#look,#jump{display:none;position:fixed;z-index:7}#joy{left:20px;bottom:25px;width:118px;height:118px;border-radius:50%;border:1px solid #fff3;background:#07101d66}#knob{position:absolute;left:35px;top:35px;width:48px;height:48px;border-radius:50%;background:#35b8ff77}#look{right:0;bottom:0;width:48vw;height:48vh}#jump{right:24px;bottom:155px;width:60px;height:60px;border-radius:50%}@media(pointer:coarse){#joy,#look,#jump{display:block}}</style></head><body><canvas id="gl"></canvas><div id="hud"><b>PIXEL 3DGS CPU V3</b><br>__COUNT__ EWA splats · weighted OIT<br>hierarchical chunk culling · CPU reconstruction<br>WASD/стрелки · мышь/тач · Space</div><div id="start"><div id="card"><h2>Pixel 3DGS V3</h2><button id="go">ВОЙТИ В МИР</button></div></div><div id="joy"><div id="knob"></div></div><div id="look"></div><button id="jump">↑</button><script>
'use strict';const META=__META__,DATA="__DATA__";const cvs=document.getElementById('gl'),gl=cvs.getContext('webgl2',{antialias:false,alpha:false,powerPreference:'high-performance'});if(!gl)alert('WebGL2 required');const ext=gl.getExtension('EXT_color_buffer_float');
function sh(t,s){let x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x));return x}function prog(v,f){let p=gl.createProgram();gl.attachShader(p,sh(gl.VERTEX_SHADER,v));gl.attachShader(p,sh(gl.FRAGMENT_SHADER,f));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p}
const VS=`#version 300 es
precision highp float;layout(location=0)in vec2 corner;layout(location=2)in vec3 center;layout(location=3)in vec4 normal4;layout(location=4)in vec4 color;layout(location=5)in vec2 scaleUV;layout(location=6)in float confidence;uniform mat4 uView,uProj;out vec2 vQ;out vec4 vColor;void main(){vec3 pc=(uView*vec4(center,1.0)).xyz;vec4 clip=uProj*vec4(pc,1.0);if(pc.z>-0.06){gl_Position=vec4(2,2,2,1);vQ=corner;vColor=vec4(0);return;}vec3 n=normalize(mat3(uView)*normal4.xyz);vec3 ref=abs(n.y)>0.92?vec3(1,0,0):vec3(0,1,0);vec3 t=normalize(cross(ref,n));vec3 b=normalize(cross(n,t));float sn=min(scaleUV.x,scaleUV.y)*0.18;mat3 C=outerProduct(t,t)*scaleUV.x*scaleUV.x+outerProduct(b,b)*scaleUV.y*scaleUV.y+outerProduct(n,n)*sn*sn;float iz=1.0/max(-pc.z,0.001),z2=max(pc.z*pc.z,0.001);vec3 jx=vec3(uProj[0][0]*iz,0.0,uProj[0][0]*pc.x/z2);vec3 jy=vec3(0.0,uProj[1][1]*iz,uProj[1][1]*pc.y/z2);float A=dot(jx,C*jx)+1e-7,B=dot(jx,C*jy),D=dot(jy,C*jy)+1e-7;float tr=A+D,disc=sqrt(max((A-D)*(A-D)+4.0*B*B,0.0));float l1=max((tr+disc)*0.5,1e-7),l2=max((tr-disc)*0.5,1e-7);float ang=0.5*atan(2.0*B,A-D);vec2 e1=vec2(cos(ang),sin(ang)),e2=vec2(-sin(ang),cos(ang));vec2 off=(e1*sqrt(l1)*corner.x+e2*sqrt(l2)*corner.y)*3.0;vec2 ndc=clip.xy/clip.w+off;gl_Position=vec4(ndc*clip.w,clip.z,clip.w);vQ=corner*3.0;vColor=vec4(color.rgb,color.a*clamp(confidence*1.12,0.22,1.0));}`;
const FA=`#version 300 es
precision highp float;in vec2 vQ;in vec4 vColor;out vec4 o;void main(){float a=vColor.a*exp(-0.5*dot(vQ,vQ));if(a<0.008)discard;float w=clamp(0.03/(1e-5+pow(1.0-a,3.0)),0.03,3.0);o=vec4(vColor.rgb*a*w,a*w);}`;
const FR=`#version 300 es
precision highp float;in vec2 vQ;in vec4 vColor;out vec4 o;void main(){float a=vColor.a*exp(-0.5*dot(vQ,vQ));if(a<0.008)discard;o=vec4(a,a,a,a);}`;
const VC=`#version 300 es
precision highp float;layout(location=0)in vec2 p;out vec2 uv;void main(){uv=p*.5+.5;gl_Position=vec4(p,0,1);}`;const FC=`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D accumTex,revealTex;out vec4 o;void main(){vec4 a=texture(accumTex,uv);float rev=texture(revealTex,uv).r;float alpha=clamp(1.0-rev,0.0,1.0);vec3 col=a.rgb/max(a.a,1e-5);vec3 bg=vec3(.003,.007,.015);o=vec4(mix(bg,col,alpha),1);}`;const pA=prog(VS,FA),pR=prog(VS,FR),pC=prog(VC,FC);
const quad=new Float32Array([-1,-1,1,-1,-1,1,1,1]);const qbo=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,qbo);gl.bufferData(gl.ARRAY_BUFFER,quad,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,8,0);const raw=atob(DATA),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const ibo=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,ibo);gl.bufferData(gl.ARRAY_BUFFER,bytes,gl.STATIC_DRAW);for(const l of [2,3,4,5,6]){gl.enableVertexAttribArray(l);gl.vertexAttribDivisor(l,1)}function ptr(base){gl.bindBuffer(gl.ARRAY_BUFFER,ibo);gl.vertexAttribPointer(2,3,gl.FLOAT,false,32,base);gl.vertexAttribPointer(3,4,gl.BYTE,true,32,base+12);gl.vertexAttribPointer(4,4,gl.UNSIGNED_BYTE,true,32,base+16);gl.vertexAttribPointer(5,2,gl.FLOAT,false,32,base+20);gl.vertexAttribPointer(6,1,gl.FLOAT,false,32,base+28)}
let fboA=gl.createFramebuffer(),fboR=gl.createFramebuffer(),texA=gl.createTexture(),texR=gl.createTexture(),w0=0,h0=0;function texSetup(tex,internal){gl.bindTexture(gl.TEXTURE_2D,tex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texStorage2D(gl.TEXTURE_2D,1,internal,cvs.width,cvs.height)}function targets(){if(w0===cvs.width&&h0===cvs.height)return;w0=cvs.width;h0=cvs.height;gl.deleteTexture(texA);gl.deleteTexture(texR);texA=gl.createTexture();texR=gl.createTexture();texSetup(texA,ext?gl.RGBA16F:gl.RGBA8);texSetup(texR,gl.RGBA8);gl.bindFramebuffer(gl.FRAMEBUFFER,fboA);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texA,0);gl.bindFramebuffer(gl.FRAMEBUFFER,fboR);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texR,0);gl.bindFramebuffer(gl.FRAMEBUFFER,null)}
function persp(o,f,a,n,fa){let q=1/Math.tan(f/2),nf=1/(n-fa);o.set([q/a,0,0,0,0,q,0,0,0,0,(fa+n)*nf,-1,0,0,2*fa*n*nf,0])}function look(o,e,y,p){let cp=Math.cos(p),sp=Math.sin(p),sy=Math.sin(y),cy=Math.cos(y),fx=sy*cp,fy=sp,fz=cy*cp;let zx=-fx,zy=-fy,zz=-fz,zl=Math.hypot(zx,zy,zz);zx/=zl;zy/=zl;zz/=zl;let xx=zz,xz=-zx,xl=Math.hypot(xx,xz);xx/=xl;xz/=xl;let yx=zy*xz,yy=zz*xx-zx*xz,yz=-zy*xx;o.set([xx,yx,zx,0,0,yy,zy,0,xz,yz,zz,0,-(xx*e[0]+xz*e[2]),-(yx*e[0]+yy*e[1]+yz*e[2]),-(zx*e[0]+zy*e[1]+zz*e[2]),1])}
let pos=[0,1.65,-7],yaw=0,pitch=0,vy=0,ground=true,started=false,keys={},joyX=0,joyY=0;addEventListener('keydown',e=>{keys[e.code]=1;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Space'&&ground){vy=4.9;ground=false}});addEventListener('keyup',e=>keys[e.code]=0);document.getElementById('go').onclick=()=>{started=true;document.getElementById('start').style.display='none';if(matchMedia('(pointer:fine)').matches)cvs.requestPointerLock?.()};document.addEventListener('mousemove',e=>{if(document.pointerLockElement===cvs){yaw-=e.movementX*.0024;pitch=Math.max(-1.5,Math.min(1.5,pitch-e.movementY*.0021))}});cvs.onclick=()=>{if(started&&matchMedia('(pointer:fine)').matches)cvs.requestPointerLock?.()};const joy=document.getElementById('joy'),knob=document.getElementById('knob');let jid=null;function ju(x,y){let r=joy.getBoundingClientRect(),dx=x-(r.left+r.width/2),dy=y-(r.top+r.height/2),m=Math.hypot(dx,dy),mx=42;if(m>mx){dx*=mx/m;dy*=mx/m}joyX=dx/mx;joyY=dy/mx;knob.style.transform=`translate(${dx}px,${dy}px)`}joy.addEventListener('touchstart',e=>{let t=e.changedTouches[0];jid=t.identifier;ju(t.clientX,t.clientY);e.preventDefault()},{passive:false});joy.addEventListener('touchmove',e=>{for(let t of e.changedTouches)if(t.identifier===jid)ju(t.clientX,t.clientY);e.preventDefault()},{passive:false});joy.addEventListener('touchend',e=>{joyX=joyY=0;knob.style.transform='';jid=null},{passive:false});const lz=document.getElementById('look');let lid=null,lx=0,ly=0;lz.addEventListener('touchstart',e=>{let t=e.changedTouches[0];lid=t.identifier;lx=t.clientX;ly=t.clientY;e.preventDefault()},{passive:false});lz.addEventListener('touchmove',e=>{for(let t of e.changedTouches)if(t.identifier===lid){yaw-=(t.clientX-lx)*.004;pitch=Math.max(-1.5,Math.min(1.5,pitch-(t.clientY-ly)*.0038));lx=t.clientX;ly=t.clientY}e.preventDefault()},{passive:false});document.getElementById('jump').addEventListener('touchstart',e=>{if(ground){vy=4.9;ground=false}e.preventDefault()},{passive:false});
function resize(){let d=Math.min(devicePixelRatio||1,1.7),w=Math.floor(innerWidth*d),h=Math.floor(innerHeight*d);if(cvs.width!==w||cvs.height!==h){cvs.width=w;cvs.height=h;gl.viewport(0,0,w,h);targets()}}let last=performance.now(),P=new Float32Array(16),V=new Float32Array(16);function visible(){let sy=Math.sin(yaw),cy=Math.cos(yaw),f=[sy,0,cy];return META.chunks.filter(c=>{let dx=c.center[0]-pos[0],dz=c.center[2]-pos[2],d=Math.hypot(dx,dz);if(d>150+c.radius)return false;if(d<12)return true;return (dx*f[0]+dz*f[2])/Math.max(d,1e-5)>-0.35})}function useScene(p){gl.useProgram(p);gl.uniformMatrix4fv(gl.getUniformLocation(p,'uView'),false,V);gl.uniformMatrix4fv(gl.getUniformLocation(p,'uProj'),false,P)}function draw(cs){for(const c of cs){ptr(c.offset*32);gl.drawArraysInstanced(gl.TRIANGLE_STRIP,0,4,c.count)}}function frame(now){resize();let dt=Math.min(.035,(now-last)/1000);last=now;if(started){let f=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0)-joyY,s=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+joyX,l=Math.hypot(f,s);if(l>1){f/=l;s/=l}let sy=Math.sin(yaw),cy=Math.cos(yaw);pos[0]+=(sy*f+cy*s)*3*dt;pos[2]+=(cy*f-sy*s)*3*dt;vy-=10.5*dt;pos[1]+=vy*dt;if(pos[1]<=1.65){pos[1]=1.65;vy=0;ground=true}}persp(P,Math.PI/2.7,cvs.width/cvs.height,.05,180);look(V,pos,yaw,pitch);let cs=visible();gl.disable(gl.DEPTH_TEST);
 gl.bindFramebuffer(gl.FRAMEBUFFER,fboA);gl.viewport(0,0,cvs.width,cvs.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);useScene(pA);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE);draw(cs);
 gl.bindFramebuffer(gl.FRAMEBUFFER,fboR);gl.clearColor(1,1,1,1);gl.clear(gl.COLOR_BUFFER_BIT);useScene(pR);gl.enable(gl.BLEND);gl.blendFunc(gl.ZERO,gl.ONE_MINUS_SRC_ALPHA);draw(cs);
 gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.disable(gl.BLEND);gl.useProgram(pC);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texA);gl.uniform1i(gl.getUniformLocation(pC,'accumTex'),0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,texR);gl.uniform1i(gl.getUniformLocation(pC,'revealTex'),1);gl.bindBuffer(gl.ARRAY_BUFFER,qbo);gl.vertexAttribPointer(0,2,gl.FLOAT,false,8,0);gl.drawArrays(gl.TRIANGLE_STRIP,0,4);requestAnimationFrame(frame)}requestAnimationFrame(frame);
</script></body></html>'''
    html=html.replace('__COUNT__',f"{len(scene['points']):,}").replace('__META__',mj).replace('__DATA__',data)
    path.write_text(html,encoding='utf-8')
