#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const path=require('node:path');const {spawnSync}=require('node:child_process');
const here=__dirname;const root=path.resolve(process.argv[2]||process.cwd());
function pythonCheck(){const opts=process.platform==='win32'?[[path.join(here,'.venv','Scripts','python.exe'),[]],['python',[]],['py',['-3']]]:[[path.join(here,'.venv','bin','python'),[]],['python3',[]],['python',[]]];for(const [cmd,prefix] of opts){if((cmd.includes('/')||cmd.includes('\\'))&&!fs.existsSync(cmd))continue;const r=spawnSync(cmd,[...prefix,'-c','import numpy,PIL; print("ok")'],{encoding:'utf8'});if(r.status===0)return{pass:true,cmd,prefix};}return{pass:false};}
const py=pythonCheck();const required=['gs360_pipeline.py','quality-gate.py','artifact-audit.py','capture-coach.py','input-quality.py','synthetic-consistency.py','autopilot.cjs','backend-registry.cjs','depth-registry.cjs','license-gate.cjs','next-action.cjs','resource-benchmark.cjs','trainer-runner.cjs','job-queue.cjs','doctor.cjs','storage-manager.cjs','splat-optimizer.cjs','consistency.cjs','fingerprint.cjs','resource-advisor.cjs','wait-and-verify.cjs','run.cjs','setup.cjs','test.cjs','quality.cjs','opensource-catalog.json'].map(name=>({name,exists:fs.existsSync(path.join(here,name))}));
function tool(script,file){const r=spawnSync(process.execPath,[path.join(here,script),root],{encoding:'utf8'});let data={};try{data=JSON.parse(r.stdout||'{}')}catch{}return{pass:r.status===0,data,file:path.join(root,file)}}
const reg=tool('backend-registry.cjs','GS360_BACKEND_REGISTRY.json');const dep=tool('depth-registry.cjs','GS360_DEPTH_REGISTRY.json');const lic=tool('license-gate.cjs','GS360_LICENSE_GATE.json');
const splatTransform=!!((process.platform==='win32'?spawnSync('where',['splat-transform'],{stdio:'ignore'}):spawnSync('which',['splat-transform'],{stdio:'ignore'})).status===0);
const report={schema:'world-server.gs360-health/v4',pass:py.pass&&required.every(x=>x.exists)&&reg.pass&&dep.pass&&lic.pass,generatedAt:new Date().toISOString(),python:py,files:required,backendRegistry:reg.data,depthRegistry:dep.data,licenseGate:lic.data,optional:{colmap:!!reg.data?.colmap?.available,nvidia:!!reg.data?.gpu?.available,selectedTrainer:reg.data?.selected||null,selectedDepth:dep.data?.selected||'proxy',splatTransform},recommendations:[]};
if(!py.pass)report.recommendations.push('Run npm run gs360:setup');if(!report.optional.colmap)report.recommendations.push('Install COLMAP for multi-view pose estimation; CPU mode is supported but slower.');if(report.optional.selectedDepth==='proxy')report.recommendations.push('Benchmark OpenVINO + a permissively licensed depth model on CPU.');if(!report.optional.selectedTrainer)report.recommendations.push('No true trainer detected; review OpenSplat licensing/build or wire another existing trainer.');if(!splatTransform)report.recommendations.push('Install MIT-licensed @playcanvas/splat-transform for safe cleanup, SPZ/SOG compression, LOD and HTML delivery exports.');
const out=path.join(root,'GS360_HEALTH_REPORT.json');fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n','utf8');console.log(JSON.stringify(report,null,2));process.exit(report.pass?0:1);
