#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {spawnSync}=require('node:child_process');
const here=__dirname;const root=path.resolve(process.argv[2]||process.cwd());
function findPython(){const opts=process.platform==='win32'?[[path.join(here,'.venv','Scripts','python.exe'),[]],['python',[]],['py',['-3']]]:[[path.join(here,'.venv','bin','python'),[]],['python3',[]],['python',[]]];for(const [c,p] of opts){if((c.includes('/')||c.includes('\\'))&&!fs.existsSync(c))continue;const r=spawnSync(c,[...p,'-c','import sys'],{stdio:'ignore'});if(r.status===0)return{cmd:c,prefix:p};}return null;}
function imp(py,m){if(!py)return false;const code='import importlib.util; print(1 if importlib.util.find_spec('+JSON.stringify(m)+') else 0)';const r=spawnSync(py.cmd,[...py.prefix,'-c',code],{encoding:'utf8',timeout:5000});return r.status===0&&String(r.stdout||'').trim()==='1';}
function which(name){try{const r=spawnSync(process.platform==='win32'?'where':'which',[name],{encoding:'utf8'});return r.status===0&&r.stdout.trim()?r.stdout.trim().split(/\r?\n/)[0]:null;}catch{return null;}}
const py=findPython();const cat=JSON.parse(fs.readFileSync(path.join(here,'opensource-catalog.json'),'utf8'));
const daRoot=process.env.GS360_DEPTH_ANYTHING_ROOT?path.resolve(process.env.GS360_DEPTH_ANYTHING_ROOT):null;const daCkpt=process.env.GS360_DEPTH_ANYTHING_CHECKPOINT?path.resolve(process.env.GS360_DEPTH_ANYTHING_CHECKPOINT):null;const detected={openvino:imp(py,'openvino'),onnxruntime:imp(py,'onnxruntime'),torch:!!(daRoot&&daCkpt&&imp(py,'torch')),colmap:!!which('colmap'),opensplat:!!(which('opensplat')||which('opensplat.exe')||process.env.GS360_OPENSPLAT),depthOpenvinoModel:!!process.env.GS360_DEPTH_OPENVINO&&fs.existsSync(process.env.GS360_DEPTH_OPENVINO),depthOnnxModel:!!process.env.GS360_DEPTH_ONNX&&fs.existsSync(process.env.GS360_DEPTH_ONNX),depthAnythingV2Small:!!(daRoot&&daCkpt&&fs.existsSync(path.join(daRoot,'depth_anything_v2','dpt.py'))&&fs.existsSync(daCkpt)),splatTransform:!!(which(process.platform==='win32'?'splat-transform.cmd':'splat-transform')||which('splat-transform'))};
const recs=[];
for(const r of cat.resources||[]){let installed=false;if(r.id==='openvino')installed=detected.openvino;if(r.id==='colmap')installed=detected.colmap;if(r.id==='opensplat')installed=detected.opensplat;if(r.id==='midas')installed=detected.depthOpenvinoModel||detected.depthOnnxModel;if(r.id==='depth_anything_v2_small')installed=detected.depthAnythingV2Small;if(r.id==='splat_transform')installed=detected.splatTransform;if(r.id==='niantic_spz')installed=detected.splatTransform;if(r.id==='supersplat')installed=true;recs.push({...r,installed,action:installed?'reuse_and_benchmark':(r.policy==='auto_allowed'?'download_install_verify':(r.policy==='auto_allowed_with_model_license_check'?'verify_model_license_then_install':'review_before_install'))});}
const highImpact=recs.filter(r=>['openvino','colmap','depth_anything_v2_small','opensplat','splat_transform'].includes(r.id));
const plan={schema:'world-server.gs360-resource-plan/v6',generatedAt:new Date().toISOString(),root,detected,policy:'permissive-commercial-safe',notes:[
 'Install only missing free resources from official sources; reuse existing tools.',
 'Never claim a >50% gain until measured on this machine and representative inputs.',
 'Depth Anything V2 Small is the permissive automatic candidate; Base/Large/Giant are non-commercial licensed and blocked by default.',
 'OpenSplat is AGPL-3.0: free/open-source and CPU-capable, but requires license review before deep integration/vendoring.',
 'PlayCanvas SplatTransform is MIT-licensed and is the preferred automatic delivery optimizer for cleanup, SPZ/SOG/LOD and HTML export.',
 'After every install: benchmark before/after, run gs360 tests, run health, then one approximate and one accurate smoke.'
],recommendations:recs,highImpactCandidates:highImpact.map(r=>r.id),permissiveAutoQueue:recs.filter(r=>!r.installed&&r.policy==='auto_allowed'&&r.automatic_install!==false).map(r=>({id:r.id,url:r.official_url,install_hint:r.install_hint,verify:r.verify})),reviewQueue:recs.filter(r=>!r.installed&&r.policy!=='auto_allowed').map(r=>({id:r.id,license:r.license,policy:r.policy,url:r.official_url}))};
const jp=path.join(root,'GS360_RESOURCE_PLAN.json'),mp=path.join(root,'GS360_RESOURCE_PLAN.md');fs.writeFileSync(jp,JSON.stringify(plan,null,2)+'\n');
const md=['# GS360 V6 free open-source resource plan','',`Generated: ${plan.generatedAt}`,'','## Detected',...Object.entries(detected).map(([k,v])=>`- ${k}: ${v?'YES':'NO'}`),'','## Permissive automatic queue',...(plan.permissiveAutoQueue.length?plan.permissiveAutoQueue.map(x=>`- **${x.id}** — ${x.url} — ${x.install_hint}`):['- Nothing missing.']),'','## Review queue',...(plan.reviewQueue.length?plan.reviewQueue.map(x=>`- **${x.id}** — ${x.license} — ${x.policy} — ${x.url}`):['- Empty.']),'','## Non-stop verification rule','For each installed resource: verify binary/model → benchmark → run tests → run health → run smoke → fix root cause → rerun until PASS. If a change needs propagation time, use `gs360:wait` instead of stopping.',''].join('\n');fs.writeFileSync(mp,md);console.log(JSON.stringify({pass:true,jsonPath:jp,mdPath:mp,detected,autoQueue:plan.permissiveAutoQueue.map(x=>x.id),reviewQueue:plan.reviewQueue.map(x=>x.id)},null,2));
