#!/usr/bin/env node
'use strict';
const fs=require('node:fs');const path=require('node:path');
const argv=process.argv.slice(2);const action=argv[0]||'report';function val(n,f=null){const i=argv.indexOf(n);return i>=0&&i+1<argv.length?argv[i+1]:f;}const root=path.resolve(val('--root',process.cwd()));
function load(p,d={}){try{return JSON.parse(fs.readFileSync(p,'utf8'));}catch{return d;}}function size(p){if(!fs.existsSync(p))return 0;const st=fs.statSync(p);if(st.isFile())return st.size;let n=0;for(const e of fs.readdirSync(p,{withFileTypes:true})){n+=size(path.join(p,e.name));}return n;}function fmt(n){const u=['B','KB','MB','GB','TB'];let i=0,x=n;while(x>=1024&&i<u.length-1){x/=1024;i++;}return`${x.toFixed(i?2:0)} ${u[i]}`;}
function knownOutputs(){const q=load(path.join(root,'.world-server','gs360','JOB_QUEUE.json'),{jobs:[]});return [...new Set((q.jobs||[]).map(j=>j?.spec?.output).filter(Boolean))];}
if(action==='compact'){
 const outArg=val('--output');if(!outArg){console.error('storage-manager.cjs compact --output <dir>');process.exit(2);}const out=path.resolve(outArg);const m=load(path.join(out,'GS360_MANIFEST.json'),null);const a=load(path.join(out,'GS360_ARTIFACT_AUDIT.json'),null);if(!m||!a||a.status==='FAIL'){console.error('[GS360 STORAGE] refuse compact: missing/failed manifest or artifact audit');process.exit(3);}const before=size(out);const removable=['trainer_input_colmap','dataset/depth'];const removed=[];for(const rel of removable){const p=path.join(out,...rel.split('/'));if(fs.existsSync(p)){const bytes=size(p);fs.rmSync(p,{recursive:true,force:true});removed.push({path:p,bytes});}}const after=size(out);const rep={schema:'world-server.gs360-storage/v1',pass:true,action:'compact',output:out,beforeBytes:before,afterBytes:after,savedBytes:before-after,savedHuman:fmt(before-after),removed};fs.writeFileSync(path.join(out,'GS360_STORAGE_REPORT.json'),JSON.stringify(rep,null,2)+'\n');console.log(JSON.stringify(rep,null,2));process.exit(0);
}
const outputs=knownOutputs().map(p=>({path:p,exists:fs.existsSync(p),bytes:size(p)}));const total=outputs.reduce((a,b)=>a+b.bytes,0);console.log(JSON.stringify({schema:'world-server.gs360-storage/v1',pass:true,action:'report',root,totalBytes:total,totalHuman:fmt(total),outputs:outputs.map(x=>({...x,human:fmt(x.bytes)}))},null,2));
