#!/usr/bin/env python3
from __future__ import annotations
import argparse, math, shutil, subprocess, tempfile
from pathlib import Path

import numpy as np
from scipy import ndimage
from skimage import measure
import trimesh

from quality_common import inspect_asset, sample_ply_xyz
from spz_bridge import decode_positions

DEFAULT_MAX_FACES = 220_000
DEFAULT_GRID_LONGEST = 176


def _sample_visual(path: Path, info: dict, max_points: int = 500_000) -> np.ndarray:
    kind = info['type']
    if kind == 'ply-splat':
        return sample_ply_xyz(path, max_points=max_points)
    if kind in ('ply-mesh', 'glb'):
        loaded = trimesh.load(path, process=False, force='scene' if kind == 'glb' else None)
        if isinstance(loaded, trimesh.Scene):
            meshes = [g for g in loaded.geometry.values() if isinstance(g, trimesh.Trimesh) and len(g.faces)]
            if not meshes: raise ValueError('No triangle meshes found for collider generation')
            mesh = trimesh.util.concatenate(meshes)
        else:
            mesh = loaded
        if not isinstance(mesh, trimesh.Trimesh) or len(mesh.vertices) == 0:
            raise ValueError('Unsupported mesh for collider generation')
        # Surface samples preserve floors/walls much better than blindly subsetting vertices.
        area = float(max(mesh.area, 1e-6))
        n = min(max_points, max(80_000, min(len(mesh.faces) * 2, max_points)))
        pts, _ = trimesh.sample.sample_surface(mesh, n)
        # Include original vertices (subsampled) to protect hard edges/corners.
        step = max(1, math.ceil(len(mesh.vertices) / max(1, max_points // 4)))
        verts = np.asarray(mesh.vertices[::step], dtype=np.float32)
        return np.vstack([np.asarray(pts, dtype=np.float32), verts])
    raise ValueError(f'Auto collider requires mesh/PLY splat input, got {kind}')


def _run_spz_decoder(path: Path, command: str | None) -> Path:
    if not command:
        raise RuntimeError('SPZ auto collider needs an SPZ decoder. Set --spz-decoder "command {input} {output}". The source SPZ remains untouched.')
    tmp = Path(tempfile.mkdtemp(prefix='world-spz-')) / 'decoded.ply'
    cmd = command.format(input=str(path), output=str(tmp))
    subprocess.run(cmd, shell=True, check=True)
    if not tmp.exists(): raise RuntimeError('SPZ decoder did not create output PLY')
    return tmp


def build_proxy_from_points(points: np.ndarray, output: Path, max_faces: int = DEFAULT_MAX_FACES,
                            longest_cells: int = DEFAULT_GRID_LONGEST) -> dict:
    points = np.asarray(points, dtype=np.float32)
    points = points[np.isfinite(points).all(axis=1)]
    if len(points) < 1000:
        raise ValueError(f'Not enough points for collider reconstruction ({len(points)})')

    mn = points.min(axis=0); mx = points.max(axis=0); ext = mx - mn
    longest = float(ext.max())
    if longest <= 1e-6: raise ValueError('Degenerate point cloud')

    # Retry with coarser grids until face budget is respected.
    attempts = []
    cells = int(max(72, longest_cells))
    final_mesh = None
    while cells >= 56:
        pitch = longest / cells
        pad = pitch * 3.0
        origin = mn - pad
        dims = np.ceil((mx - mn + pad * 2) / pitch).astype(int) + 1
        # Keep memory bounded even for bizarre aspect ratios.
        if np.prod(dims, dtype=np.int64) > 18_000_000:
            cells = int(cells * 0.82); continue

        idx = np.floor((points - origin) / pitch).astype(np.int32)
        idx = np.clip(idx, 0, dims - 1)
        occ = np.zeros(tuple(dims.tolist()), dtype=bool)
        occ[idx[:,0], idx[:,1], idx[:,2]] = True

        # Connect small sampling gaps while keeping corridors/doorways. One-cell shell gives robust capsule collision.
        occ = ndimage.binary_dilation(occ, iterations=1)
        occ = ndimage.binary_closing(occ, iterations=1)
        # Remove isolated noise generated by stray splats.
        labels, count = ndimage.label(occ)
        if count > 1:
            sizes = np.bincount(labels.ravel())
            keep = sizes >= max(8, int(sizes[1:].max() * 0.0008))
            keep[0] = False
            occ = keep[labels]

        if not occ.any(): raise RuntimeError('Collider occupancy became empty')
        verts, faces, normals, values = measure.marching_cubes(occ.astype(np.uint8), level=0.5, spacing=(pitch,pitch,pitch))
        verts += origin
        mesh = trimesh.Trimesh(vertices=verts, faces=faces, process=True, validate=True)
        # Drop tiny disconnected shards.
        parts = mesh.split(only_watertight=False)
        if parts:
            areas = np.array([max(float(p.area), 0.0) for p in parts])
            cutoff = max(float(areas.max()) * 0.0007, pitch * pitch * 8)
            good = [p for p,a in zip(parts,areas) if a >= cutoff]
            if good: mesh = trimesh.util.concatenate(good)
        attempts.append({'cells':cells,'pitch':pitch,'faces':int(len(mesh.faces)),'vertices':int(len(mesh.vertices))})
        final_mesh = mesh
        if len(mesh.faces) <= max_faces:
            break
        cells = int(cells * 0.82)

    if final_mesh is None: raise RuntimeError('Could not reconstruct collision mesh')
    if len(final_mesh.faces) > max_faces:
        raise RuntimeError(f'Auto collider still exceeds face budget: {len(final_mesh.faces):,} > {max_faces:,}')

    output.parent.mkdir(parents=True, exist_ok=True)
    final_mesh.export(output, file_type='ply', encoding='binary_little_endian')
    return {
        'generator':'voxel-surface-v2',
        'sourcePoints':int(len(points)),
        'vertices':int(len(final_mesh.vertices)),
        'faces':int(len(final_mesh.faces)),
        'watertight':bool(final_mesh.is_watertight),
        'bounds':{'min':final_mesh.bounds[0].astype(float).tolist(),'max':final_mesh.bounds[1].astype(float).tolist()},
        'attempts':attempts,
    }


def generate_auto_collider(visual: Path, output: Path, *, max_faces: int = DEFAULT_MAX_FACES,
                           longest_cells: int = DEFAULT_GRID_LONGEST, spz_decoder: str | None = None) -> dict:
    info = inspect_asset(visual)
    if info['type'] == 'spz':
        points,decoder_meta=decode_positions(visual,spz_decoder,max_points=700_000)
        stats=build_proxy_from_points(points,output,max_faces=max_faces,longest_cells=longest_cells)
        stats['inputType']='spz';stats['spzDecoder']=decoder_meta
        return stats
    points = _sample_visual(visual, info)
    stats = build_proxy_from_points(points, output, max_faces=max_faces, longest_cells=longest_cells)
    stats['inputType'] = info['type']
    return stats


def main():
    ap = argparse.ArgumentParser(description='Generate a non-destructive physics proxy from a world visual.')
    ap.add_argument('visual', type=Path)
    ap.add_argument('output', type=Path)
    ap.add_argument('--max-faces', type=int, default=DEFAULT_MAX_FACES)
    ap.add_argument('--grid', type=int, default=DEFAULT_GRID_LONGEST)
    ap.add_argument('--spz-decoder', default=None)
    args = ap.parse_args()
    stats = generate_auto_collider(args.visual.resolve(), args.output.resolve(), max_faces=args.max_faces,
                                   longest_cells=args.grid, spz_decoder=args.spz_decoder)
    import json
    print(json.dumps(stats, ensure_ascii=False, indent=2))

if __name__ == '__main__': main()
